services:
  zcashd:
    image: electriccoinco/zcashd:latest
    platform: linux/amd64
    entrypoint: ["zcashd"]
    command:
      - "-printtoconsole"
      - "-conf=/etc/zcash/zcash.conf"
      - "-datadir=/var/lib/zcash/.zcash"
    ports:
      - "18232:18232"
      - "9067:9067"
    volumes:
      - ./.regtest/zcashd:/var/lib/zcash/.zcash
      - ./scripts/regtest/zcash.conf:/etc/zcash/zcash.conf:ro

  lightwalletd:
    image: electriccoinco/lightwalletd:latest
    platform: linux/amd64
    entrypoint: ["lightwalletd"]
    command:
      - "--no-tls-very-insecure"
      - "--grpc-bind-addr"
      - "0.0.0.0:9067"
      - "--zcash-conf-path"
      - "/etc/zcash/lightwalletd-zcash.conf"
      - "--data-dir"
      - "/var/lib/lightwalletd"
      - "--log-file"
      - "/dev/stdout"
    depends_on:
      - zcashd
    network_mode: "service:zcashd"
    volumes:
      - ./.regtest/zcashd:/var/lib/zcash/.zcash:ro
      - ./.regtest/lightwalletd:/var/lib/lightwalletd
      - ./scripts/regtest/lightwalletd-zcash.conf:/etc/zcash/lightwalletd-zcash.conf:ro
