// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/keystone.dart';
import 'api/secret.dart';
import 'api/simple.dart';
import 'api/sync.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'wallet/keystone.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ApiMempoolTxEvent>
  dco_decode_StreamSink_api_mempool_tx_event_Sse(dynamic raw);

  @protected
  RustStreamSink<ApiSyncProgressEvent>
  dco_decode_StreamSink_api_sync_progress_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountCreationResult dco_decode_account_creation_result(dynamic raw);

  @protected
  AccountInfo dco_decode_account_info(dynamic raw);

  @protected
  AddressValidationResult dco_decode_address_validation_result(dynamic raw);

  @protected
  ApiMempoolTxEvent dco_decode_api_mempool_tx_event(dynamic raw);

  @protected
  ApiSyncProgressEvent dco_decode_api_sync_progress_event(dynamic raw);

  @protected
  BlockMetaInfo dco_decode_block_meta_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ExchangeTransparentAddressResult
  dco_decode_exchange_transparent_address_result(dynamic raw);

  @protected
  ExecuteProposalResult dco_decode_execute_proposal_result(dynamic raw);

  @protected
  ExtractAndBroadcastPcztResult dco_decode_extract_and_broadcast_pczt_result(
    dynamic raw,
  );

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeystoneAccountInfo dco_decode_keystone_account_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountInfo> dco_decode_list_account_info(dynamic raw);

  @protected
  List<BlockMetaInfo> dco_decode_list_block_meta_info(dynamic raw);

  @protected
  List<KeystoneAccountInfo> dco_decode_list_keystone_account_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ScanRangeInfo> dco_decode_list_scan_range_info(dynamic raw);

  @protected
  List<SubtreeRoot> dco_decode_list_subtree_root(dynamic raw);

  @protected
  List<TransactionDetailOutput> dco_decode_list_transaction_detail_output(
    dynamic raw,
  );

  @protected
  List<TransactionInfo> dco_decode_list_transaction_info(dynamic raw);

  @protected
  List<TxDataRequest> dco_decode_list_tx_data_request(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ProposalResult dco_decode_proposal_result(dynamic raw);

  @protected
  ScanRangeInfo dco_decode_scan_range_info(dynamic raw);

  @protected
  ScanResult dco_decode_scan_result(dynamic raw);

  @protected
  SendMaxEstimateResult dco_decode_send_max_estimate_result(dynamic raw);

  @protected
  ShieldTransparentPcztResult dco_decode_shield_transparent_pczt_result(
    dynamic raw,
  );

  @protected
  ShieldTransparentResult dco_decode_shield_transparent_result(dynamic raw);

  @protected
  ShieldTransparentStatus dco_decode_shield_transparent_status(dynamic raw);

  @protected
  SubtreeIndices dco_decode_subtree_indices(dynamic raw);

  @protected
  SubtreeRoot dco_decode_subtree_root(dynamic raw);

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw);

  @protected
  TransactionDetail dco_decode_transaction_detail(dynamic raw);

  @protected
  TransactionDetailOutput dco_decode_transaction_detail_output(dynamic raw);

  @protected
  TransactionInfo dco_decode_transaction_info(dynamic raw);

  @protected
  TxDataRequest dco_decode_tx_data_request(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UrDecodeResult dco_decode_ur_decode_result(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletBalance dco_decode_wallet_balance(dynamic raw);

  @protected
  WalletCreationResult dco_decode_wallet_creation_result(dynamic raw);

  @protected
  WalletImportResult dco_decode_wallet_import_result(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ApiMempoolTxEvent>
  sse_decode_StreamSink_api_mempool_tx_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<ApiSyncProgressEvent>
  sse_decode_StreamSink_api_sync_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountCreationResult sse_decode_account_creation_result(
    SseDeserializer deserializer,
  );

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer);

  @protected
  AddressValidationResult sse_decode_address_validation_result(
    SseDeserializer deserializer,
  );

  @protected
  ApiMempoolTxEvent sse_decode_api_mempool_tx_event(
    SseDeserializer deserializer,
  );

  @protected
  ApiSyncProgressEvent sse_decode_api_sync_progress_event(
    SseDeserializer deserializer,
  );

  @protected
  BlockMetaInfo sse_decode_block_meta_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ExchangeTransparentAddressResult
  sse_decode_exchange_transparent_address_result(SseDeserializer deserializer);

  @protected
  ExecuteProposalResult sse_decode_execute_proposal_result(
    SseDeserializer deserializer,
  );

  @protected
  ExtractAndBroadcastPcztResult sse_decode_extract_and_broadcast_pczt_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeystoneAccountInfo sse_decode_keystone_account_info(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountInfo> sse_decode_list_account_info(SseDeserializer deserializer);

  @protected
  List<BlockMetaInfo> sse_decode_list_block_meta_info(
    SseDeserializer deserializer,
  );

  @protected
  List<KeystoneAccountInfo> sse_decode_list_keystone_account_info(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ScanRangeInfo> sse_decode_list_scan_range_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SubtreeRoot> sse_decode_list_subtree_root(SseDeserializer deserializer);

  @protected
  List<TransactionDetailOutput> sse_decode_list_transaction_detail_output(
    SseDeserializer deserializer,
  );

  @protected
  List<TransactionInfo> sse_decode_list_transaction_info(
    SseDeserializer deserializer,
  );

  @protected
  List<TxDataRequest> sse_decode_list_tx_data_request(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ProposalResult sse_decode_proposal_result(SseDeserializer deserializer);

  @protected
  ScanRangeInfo sse_decode_scan_range_info(SseDeserializer deserializer);

  @protected
  ScanResult sse_decode_scan_result(SseDeserializer deserializer);

  @protected
  SendMaxEstimateResult sse_decode_send_max_estimate_result(
    SseDeserializer deserializer,
  );

  @protected
  ShieldTransparentPcztResult sse_decode_shield_transparent_pczt_result(
    SseDeserializer deserializer,
  );

  @protected
  ShieldTransparentResult sse_decode_shield_transparent_result(
    SseDeserializer deserializer,
  );

  @protected
  ShieldTransparentStatus sse_decode_shield_transparent_status(
    SseDeserializer deserializer,
  );

  @protected
  SubtreeIndices sse_decode_subtree_indices(SseDeserializer deserializer);

  @protected
  SubtreeRoot sse_decode_subtree_root(SseDeserializer deserializer);

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer);

  @protected
  TransactionDetail sse_decode_transaction_detail(SseDeserializer deserializer);

  @protected
  TransactionDetailOutput sse_decode_transaction_detail_output(
    SseDeserializer deserializer,
  );

  @protected
  TransactionInfo sse_decode_transaction_info(SseDeserializer deserializer);

  @protected
  TxDataRequest sse_decode_tx_data_request(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UrDecodeResult sse_decode_ur_decode_result(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletBalance sse_decode_wallet_balance(SseDeserializer deserializer);

  @protected
  WalletCreationResult sse_decode_wallet_creation_result(
    SseDeserializer deserializer,
  );

  @protected
  WalletImportResult sse_decode_wallet_import_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_mempool_tx_event_Sse(
    RustStreamSink<ApiMempoolTxEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_sync_progress_event_Sse(
    RustStreamSink<ApiSyncProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_creation_result(
    AccountCreationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer);

  @protected
  void sse_encode_address_validation_result(
    AddressValidationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_mempool_tx_event(
    ApiMempoolTxEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_sync_progress_event(
    ApiSyncProgressEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_block_meta_info(BlockMetaInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_exchange_transparent_address_result(
    ExchangeTransparentAddressResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_execute_proposal_result(
    ExecuteProposalResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_extract_and_broadcast_pczt_result(
    ExtractAndBroadcastPcztResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_keystone_account_info(
    KeystoneAccountInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_info(
    List<AccountInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_block_meta_info(
    List<BlockMetaInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_keystone_account_info(
    List<KeystoneAccountInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scan_range_info(
    List<ScanRangeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_subtree_root(
    List<SubtreeRoot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_detail_output(
    List<TransactionDetailOutput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_info(
    List<TransactionInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tx_data_request(
    List<TxDataRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proposal_result(
    ProposalResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_range_info(ScanRangeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_scan_result(ScanResult self, SseSerializer serializer);

  @protected
  void sse_encode_send_max_estimate_result(
    SendMaxEstimateResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shield_transparent_pczt_result(
    ShieldTransparentPcztResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shield_transparent_result(
    ShieldTransparentResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shield_transparent_status(
    ShieldTransparentStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtree_indices(
    SubtreeIndices self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtree_root(SubtreeRoot self, SseSerializer serializer);

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_detail(
    TransactionDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_detail_output(
    TransactionDetailOutput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_info(
    TransactionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tx_data_request(TxDataRequest self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_ur_decode_result(
    UrDecodeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_balance(WalletBalance self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_creation_result(
    WalletCreationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_import_result(
    WalletImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
