// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/keystone.dart';
import 'api/secret.dart';
import 'api/simple.dart';
import 'api/sync.dart';
import 'api/voting.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'third_party/zcash_voting/wire.dart';
import 'wallet/keystone.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<ApiDelegationProofEvent>
  dco_decode_StreamSink_api_delegation_proof_event_Sse(dynamic raw);

  @protected
  RustStreamSink<ApiMempoolTxEvent>
  dco_decode_StreamSink_api_mempool_tx_event_Sse(dynamic raw);

  @protected
  RustStreamSink<ApiSyncProgressEvent>
  dco_decode_StreamSink_api_sync_progress_event_Sse(dynamic raw);

  @protected
  RustStreamSink<ApiVoteCommitEvent>
  dco_decode_StreamSink_api_vote_commit_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountCreationResult dco_decode_account_creation_result(dynamic raw);

  @protected
  AccountInfo dco_decode_account_info(dynamic raw);

  @protected
  AddressValidationResult dco_decode_address_validation_result(dynamic raw);

  @protected
  ApiDelegationPirPrecomputeResult
  dco_decode_api_delegation_pir_precompute_result(dynamic raw);

  @protected
  ApiDelegationProofEvent dco_decode_api_delegation_proof_event(dynamic raw);

  @protected
  ApiDraftVote dco_decode_api_draft_vote(dynamic raw);

  @protected
  ApiKeystoneDelegationRequest dco_decode_api_keystone_delegation_request(
    dynamic raw,
  );

  @protected
  ApiKeystoneSignatureRecord dco_decode_api_keystone_signature_record(
    dynamic raw,
  );

  @protected
  ApiMempoolTxEvent dco_decode_api_mempool_tx_event(dynamic raw);

  @protected
  ApiSignedDelegationPayload dco_decode_api_signed_delegation_payload(
    dynamic raw,
  );

  @protected
  ApiSignedVoteCommitment dco_decode_api_signed_vote_commitment(dynamic raw);

  @protected
  ApiSignedVoteCommitments dco_decode_api_signed_vote_commitments(dynamic raw);

  @protected
  ApiSyncProgressEvent dco_decode_api_sync_progress_event(dynamic raw);

  @protected
  ApiVanWitness dco_decode_api_van_witness(dynamic raw);

  @protected
  ApiVoteCommitEvent dco_decode_api_vote_commit_event(dynamic raw);

  @protected
  ApiVoteRecord dco_decode_api_vote_record(dynamic raw);

  @protected
  ApiVotingBundleSetupResult dco_decode_api_voting_bundle_setup_result(
    dynamic raw,
  );

  @protected
  ApiVotingNoteRef dco_decode_api_voting_note_ref(dynamic raw);

  @protected
  ApiVotingNoteSelectionResult dco_decode_api_voting_note_selection_result(
    dynamic raw,
  );

  @protected
  BlockMetaInfo dco_decode_block_meta_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApiSignedDelegationPayload
  dco_decode_box_autoadd_api_signed_delegation_payload(dynamic raw);

  @protected
  ApiSignedVoteCommitments dco_decode_box_autoadd_api_signed_vote_commitments(
    dynamic raw,
  );

  @protected
  ApiVanWitness dco_decode_box_autoadd_api_van_witness(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  ShareDelegationRecordView dco_decode_box_autoadd_share_delegation_record_view(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  VoteCommitmentWire dco_decode_box_autoadd_vote_commitment_wire(dynamic raw);

  @protected
  VoteShareWire dco_decode_box_autoadd_vote_share_wire(dynamic raw);

  @protected
  VotingRoundParams dco_decode_box_autoadd_voting_round_params(dynamic raw);

  @protected
  CommitmentBundleRecoveryView dco_decode_commitment_bundle_recovery_view(
    dynamic raw,
  );

  @protected
  DelegationRecoveryView dco_decode_delegation_recovery_view(dynamic raw);

  @protected
  DelegationSubmissionWire dco_decode_delegation_submission_wire(dynamic raw);

  @protected
  ExecuteProposalResult dco_decode_execute_proposal_result(dynamic raw);

  @protected
  ExtractAndBroadcastPcztResult dco_decode_extract_and_broadcast_pczt_result(
    dynamic raw,
  );

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeystoneAccountInfo dco_decode_keystone_account_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountInfo> dco_decode_list_account_info(dynamic raw);

  @protected
  List<ApiDraftVote> dco_decode_list_api_draft_vote(dynamic raw);

  @protected
  List<ApiKeystoneSignatureRecord>
  dco_decode_list_api_keystone_signature_record(dynamic raw);

  @protected
  List<ApiSignedVoteCommitment> dco_decode_list_api_signed_vote_commitment(
    dynamic raw,
  );

  @protected
  List<ApiVoteRecord> dco_decode_list_api_vote_record(dynamic raw);

  @protected
  List<ApiVotingNoteRef> dco_decode_list_api_voting_note_ref(dynamic raw);

  @protected
  List<BlockMetaInfo> dco_decode_list_block_meta_info(dynamic raw);

  @protected
  List<CommitmentBundleRecoveryView>
  dco_decode_list_commitment_bundle_recovery_view(dynamic raw);

  @protected
  List<DelegationRecoveryView> dco_decode_list_delegation_recovery_view(
    dynamic raw,
  );

  @protected
  List<KeystoneAccountInfo> dco_decode_list_keystone_account_info(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<NextStepView> dco_decode_list_next_step_view(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ScanRangeInfo> dco_decode_list_scan_range_info(dynamic raw);

  @protected
  List<ShareDelegationRecordView> dco_decode_list_share_delegation_record_view(
    dynamic raw,
  );

  @protected
  List<ShareSubmissionPlanView> dco_decode_list_share_submission_plan_view(
    dynamic raw,
  );

  @protected
  List<ShareWorkflowRecoveryView> dco_decode_list_share_workflow_recovery_view(
    dynamic raw,
  );

  @protected
  List<SubtreeRoot> dco_decode_list_subtree_root(dynamic raw);

  @protected
  List<TransactionDetailOutput> dco_decode_list_transaction_detail_output(
    dynamic raw,
  );

  @protected
  List<TransactionInfo> dco_decode_list_transaction_info(dynamic raw);

  @protected
  List<TxDataRequest> dco_decode_list_tx_data_request(dynamic raw);

  @protected
  List<VoteRecoveryView> dco_decode_list_vote_recovery_view(dynamic raw);

  @protected
  List<VoteShareWire> dco_decode_list_vote_share_wire(dynamic raw);

  @protected
  List<WireEncryptedShareJson> dco_decode_list_wire_encrypted_share_json(
    dynamic raw,
  );

  @protected
  NextStepView dco_decode_next_step_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApiSignedDelegationPayload?
  dco_decode_opt_box_autoadd_api_signed_delegation_payload(dynamic raw);

  @protected
  ApiSignedVoteCommitments?
  dco_decode_opt_box_autoadd_api_signed_vote_commitments(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ProposalResult dco_decode_proposal_result(dynamic raw);

  @protected
  RoundPlanView dco_decode_round_plan_view(dynamic raw);

  @protected
  RoundRecoveryStateView dco_decode_round_recovery_state_view(dynamic raw);

  @protected
  ScanRangeInfo dco_decode_scan_range_info(dynamic raw);

  @protected
  ScanResult dco_decode_scan_result(dynamic raw);

  @protected
  SendMaxEstimateResult dco_decode_send_max_estimate_result(dynamic raw);

  @protected
  ShareDelegationRecordView dco_decode_share_delegation_record_view(
    dynamic raw,
  );

  @protected
  ShareSubmissionPlanView dco_decode_share_submission_plan_view(dynamic raw);

  @protected
  ShareWorkflowRecoveryView dco_decode_share_workflow_recovery_view(
    dynamic raw,
  );

  @protected
  ShieldTransparentPcztResult dco_decode_shield_transparent_pczt_result(
    dynamic raw,
  );

  @protected
  ShieldTransparentResult dco_decode_shield_transparent_result(dynamic raw);

  @protected
  ShieldTransparentStatus dco_decode_shield_transparent_status(dynamic raw);

  @protected
  SubtreeIndices dco_decode_subtree_indices(dynamic raw);

  @protected
  SubtreeRoot dco_decode_subtree_root(dynamic raw);

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw);

  @protected
  TransactionDetail dco_decode_transaction_detail(dynamic raw);

  @protected
  TransactionDetailOutput dco_decode_transaction_detail_output(dynamic raw);

  @protected
  TransactionInfo dco_decode_transaction_info(dynamic raw);

  @protected
  TxDataRequest dco_decode_tx_data_request(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UrDecodeResult dco_decode_ur_decode_result(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VoteCommitmentWire dco_decode_vote_commitment_wire(dynamic raw);

  @protected
  VoteRecoveryView dco_decode_vote_recovery_view(dynamic raw);

  @protected
  VoteShareWire dco_decode_vote_share_wire(dynamic raw);

  @protected
  VotingRoundParams dco_decode_voting_round_params(dynamic raw);

  @protected
  WalletBalance dco_decode_wallet_balance(dynamic raw);

  @protected
  WalletCreationResult dco_decode_wallet_creation_result(dynamic raw);

  @protected
  WalletImportResult dco_decode_wallet_import_result(dynamic raw);

  @protected
  WireEncryptedShareJson dco_decode_wire_encrypted_share_json(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<ApiDelegationProofEvent>
  sse_decode_StreamSink_api_delegation_proof_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiMempoolTxEvent>
  sse_decode_StreamSink_api_mempool_tx_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<ApiSyncProgressEvent>
  sse_decode_StreamSink_api_sync_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiVoteCommitEvent>
  sse_decode_StreamSink_api_vote_commit_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountCreationResult sse_decode_account_creation_result(
    SseDeserializer deserializer,
  );

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer);

  @protected
  AddressValidationResult sse_decode_address_validation_result(
    SseDeserializer deserializer,
  );

  @protected
  ApiDelegationPirPrecomputeResult
  sse_decode_api_delegation_pir_precompute_result(SseDeserializer deserializer);

  @protected
  ApiDelegationProofEvent sse_decode_api_delegation_proof_event(
    SseDeserializer deserializer,
  );

  @protected
  ApiDraftVote sse_decode_api_draft_vote(SseDeserializer deserializer);

  @protected
  ApiKeystoneDelegationRequest sse_decode_api_keystone_delegation_request(
    SseDeserializer deserializer,
  );

  @protected
  ApiKeystoneSignatureRecord sse_decode_api_keystone_signature_record(
    SseDeserializer deserializer,
  );

  @protected
  ApiMempoolTxEvent sse_decode_api_mempool_tx_event(
    SseDeserializer deserializer,
  );

  @protected
  ApiSignedDelegationPayload sse_decode_api_signed_delegation_payload(
    SseDeserializer deserializer,
  );

  @protected
  ApiSignedVoteCommitment sse_decode_api_signed_vote_commitment(
    SseDeserializer deserializer,
  );

  @protected
  ApiSignedVoteCommitments sse_decode_api_signed_vote_commitments(
    SseDeserializer deserializer,
  );

  @protected
  ApiSyncProgressEvent sse_decode_api_sync_progress_event(
    SseDeserializer deserializer,
  );

  @protected
  ApiVanWitness sse_decode_api_van_witness(SseDeserializer deserializer);

  @protected
  ApiVoteCommitEvent sse_decode_api_vote_commit_event(
    SseDeserializer deserializer,
  );

  @protected
  ApiVoteRecord sse_decode_api_vote_record(SseDeserializer deserializer);

  @protected
  ApiVotingBundleSetupResult sse_decode_api_voting_bundle_setup_result(
    SseDeserializer deserializer,
  );

  @protected
  ApiVotingNoteRef sse_decode_api_voting_note_ref(SseDeserializer deserializer);

  @protected
  ApiVotingNoteSelectionResult sse_decode_api_voting_note_selection_result(
    SseDeserializer deserializer,
  );

  @protected
  BlockMetaInfo sse_decode_block_meta_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApiSignedDelegationPayload
  sse_decode_box_autoadd_api_signed_delegation_payload(
    SseDeserializer deserializer,
  );

  @protected
  ApiSignedVoteCommitments sse_decode_box_autoadd_api_signed_vote_commitments(
    SseDeserializer deserializer,
  );

  @protected
  ApiVanWitness sse_decode_box_autoadd_api_van_witness(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ShareDelegationRecordView sse_decode_box_autoadd_share_delegation_record_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  VoteCommitmentWire sse_decode_box_autoadd_vote_commitment_wire(
    SseDeserializer deserializer,
  );

  @protected
  VoteShareWire sse_decode_box_autoadd_vote_share_wire(
    SseDeserializer deserializer,
  );

  @protected
  VotingRoundParams sse_decode_box_autoadd_voting_round_params(
    SseDeserializer deserializer,
  );

  @protected
  CommitmentBundleRecoveryView sse_decode_commitment_bundle_recovery_view(
    SseDeserializer deserializer,
  );

  @protected
  DelegationRecoveryView sse_decode_delegation_recovery_view(
    SseDeserializer deserializer,
  );

  @protected
  DelegationSubmissionWire sse_decode_delegation_submission_wire(
    SseDeserializer deserializer,
  );

  @protected
  ExecuteProposalResult sse_decode_execute_proposal_result(
    SseDeserializer deserializer,
  );

  @protected
  ExtractAndBroadcastPcztResult sse_decode_extract_and_broadcast_pczt_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeystoneAccountInfo sse_decode_keystone_account_info(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountInfo> sse_decode_list_account_info(SseDeserializer deserializer);

  @protected
  List<ApiDraftVote> sse_decode_list_api_draft_vote(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiKeystoneSignatureRecord>
  sse_decode_list_api_keystone_signature_record(SseDeserializer deserializer);

  @protected
  List<ApiSignedVoteCommitment> sse_decode_list_api_signed_vote_commitment(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiVoteRecord> sse_decode_list_api_vote_record(
    SseDeserializer deserializer,
  );

  @protected
  List<ApiVotingNoteRef> sse_decode_list_api_voting_note_ref(
    SseDeserializer deserializer,
  );

  @protected
  List<BlockMetaInfo> sse_decode_list_block_meta_info(
    SseDeserializer deserializer,
  );

  @protected
  List<CommitmentBundleRecoveryView>
  sse_decode_list_commitment_bundle_recovery_view(SseDeserializer deserializer);

  @protected
  List<DelegationRecoveryView> sse_decode_list_delegation_recovery_view(
    SseDeserializer deserializer,
  );

  @protected
  List<KeystoneAccountInfo> sse_decode_list_keystone_account_info(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<NextStepView> sse_decode_list_next_step_view(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ScanRangeInfo> sse_decode_list_scan_range_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ShareDelegationRecordView> sse_decode_list_share_delegation_record_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ShareSubmissionPlanView> sse_decode_list_share_submission_plan_view(
    SseDeserializer deserializer,
  );

  @protected
  List<ShareWorkflowRecoveryView> sse_decode_list_share_workflow_recovery_view(
    SseDeserializer deserializer,
  );

  @protected
  List<SubtreeRoot> sse_decode_list_subtree_root(SseDeserializer deserializer);

  @protected
  List<TransactionDetailOutput> sse_decode_list_transaction_detail_output(
    SseDeserializer deserializer,
  );

  @protected
  List<TransactionInfo> sse_decode_list_transaction_info(
    SseDeserializer deserializer,
  );

  @protected
  List<TxDataRequest> sse_decode_list_tx_data_request(
    SseDeserializer deserializer,
  );

  @protected
  List<VoteRecoveryView> sse_decode_list_vote_recovery_view(
    SseDeserializer deserializer,
  );

  @protected
  List<VoteShareWire> sse_decode_list_vote_share_wire(
    SseDeserializer deserializer,
  );

  @protected
  List<WireEncryptedShareJson> sse_decode_list_wire_encrypted_share_json(
    SseDeserializer deserializer,
  );

  @protected
  NextStepView sse_decode_next_step_view(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApiSignedDelegationPayload?
  sse_decode_opt_box_autoadd_api_signed_delegation_payload(
    SseDeserializer deserializer,
  );

  @protected
  ApiSignedVoteCommitments?
  sse_decode_opt_box_autoadd_api_signed_vote_commitments(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ProposalResult sse_decode_proposal_result(SseDeserializer deserializer);

  @protected
  RoundPlanView sse_decode_round_plan_view(SseDeserializer deserializer);

  @protected
  RoundRecoveryStateView sse_decode_round_recovery_state_view(
    SseDeserializer deserializer,
  );

  @protected
  ScanRangeInfo sse_decode_scan_range_info(SseDeserializer deserializer);

  @protected
  ScanResult sse_decode_scan_result(SseDeserializer deserializer);

  @protected
  SendMaxEstimateResult sse_decode_send_max_estimate_result(
    SseDeserializer deserializer,
  );

  @protected
  ShareDelegationRecordView sse_decode_share_delegation_record_view(
    SseDeserializer deserializer,
  );

  @protected
  ShareSubmissionPlanView sse_decode_share_submission_plan_view(
    SseDeserializer deserializer,
  );

  @protected
  ShareWorkflowRecoveryView sse_decode_share_workflow_recovery_view(
    SseDeserializer deserializer,
  );

  @protected
  ShieldTransparentPcztResult sse_decode_shield_transparent_pczt_result(
    SseDeserializer deserializer,
  );

  @protected
  ShieldTransparentResult sse_decode_shield_transparent_result(
    SseDeserializer deserializer,
  );

  @protected
  ShieldTransparentStatus sse_decode_shield_transparent_status(
    SseDeserializer deserializer,
  );

  @protected
  SubtreeIndices sse_decode_subtree_indices(SseDeserializer deserializer);

  @protected
  SubtreeRoot sse_decode_subtree_root(SseDeserializer deserializer);

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer);

  @protected
  TransactionDetail sse_decode_transaction_detail(SseDeserializer deserializer);

  @protected
  TransactionDetailOutput sse_decode_transaction_detail_output(
    SseDeserializer deserializer,
  );

  @protected
  TransactionInfo sse_decode_transaction_info(SseDeserializer deserializer);

  @protected
  TxDataRequest sse_decode_tx_data_request(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UrDecodeResult sse_decode_ur_decode_result(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VoteCommitmentWire sse_decode_vote_commitment_wire(
    SseDeserializer deserializer,
  );

  @protected
  VoteRecoveryView sse_decode_vote_recovery_view(SseDeserializer deserializer);

  @protected
  VoteShareWire sse_decode_vote_share_wire(SseDeserializer deserializer);

  @protected
  VotingRoundParams sse_decode_voting_round_params(
    SseDeserializer deserializer,
  );

  @protected
  WalletBalance sse_decode_wallet_balance(SseDeserializer deserializer);

  @protected
  WalletCreationResult sse_decode_wallet_creation_result(
    SseDeserializer deserializer,
  );

  @protected
  WalletImportResult sse_decode_wallet_import_result(
    SseDeserializer deserializer,
  );

  @protected
  WireEncryptedShareJson sse_decode_wire_encrypted_share_json(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_delegation_proof_event_Sse(
    RustStreamSink<ApiDelegationProofEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_mempool_tx_event_Sse(
    RustStreamSink<ApiMempoolTxEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_sync_progress_event_Sse(
    RustStreamSink<ApiSyncProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_vote_commit_event_Sse(
    RustStreamSink<ApiVoteCommitEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_creation_result(
    AccountCreationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer);

  @protected
  void sse_encode_address_validation_result(
    AddressValidationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_delegation_pir_precompute_result(
    ApiDelegationPirPrecomputeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_delegation_proof_event(
    ApiDelegationProofEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_draft_vote(ApiDraftVote self, SseSerializer serializer);

  @protected
  void sse_encode_api_keystone_delegation_request(
    ApiKeystoneDelegationRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_keystone_signature_record(
    ApiKeystoneSignatureRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_mempool_tx_event(
    ApiMempoolTxEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_signed_delegation_payload(
    ApiSignedDelegationPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_signed_vote_commitment(
    ApiSignedVoteCommitment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_signed_vote_commitments(
    ApiSignedVoteCommitments self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_sync_progress_event(
    ApiSyncProgressEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_van_witness(ApiVanWitness self, SseSerializer serializer);

  @protected
  void sse_encode_api_vote_commit_event(
    ApiVoteCommitEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_vote_record(ApiVoteRecord self, SseSerializer serializer);

  @protected
  void sse_encode_api_voting_bundle_setup_result(
    ApiVotingBundleSetupResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_voting_note_ref(
    ApiVotingNoteRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_voting_note_selection_result(
    ApiVotingNoteSelectionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_block_meta_info(BlockMetaInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_signed_delegation_payload(
    ApiSignedDelegationPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_signed_vote_commitments(
    ApiSignedVoteCommitments self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_van_witness(
    ApiVanWitness self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_share_delegation_record_view(
    ShareDelegationRecordView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_vote_commitment_wire(
    VoteCommitmentWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_vote_share_wire(
    VoteShareWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_voting_round_params(
    VotingRoundParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_commitment_bundle_recovery_view(
    CommitmentBundleRecoveryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delegation_recovery_view(
    DelegationRecoveryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delegation_submission_wire(
    DelegationSubmissionWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_execute_proposal_result(
    ExecuteProposalResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_extract_and_broadcast_pczt_result(
    ExtractAndBroadcastPcztResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_keystone_account_info(
    KeystoneAccountInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_info(
    List<AccountInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_draft_vote(
    List<ApiDraftVote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_keystone_signature_record(
    List<ApiKeystoneSignatureRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_signed_vote_commitment(
    List<ApiSignedVoteCommitment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_vote_record(
    List<ApiVoteRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_voting_note_ref(
    List<ApiVotingNoteRef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_block_meta_info(
    List<BlockMetaInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_commitment_bundle_recovery_view(
    List<CommitmentBundleRecoveryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_delegation_recovery_view(
    List<DelegationRecoveryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_keystone_account_info(
    List<KeystoneAccountInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_next_step_view(
    List<NextStepView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scan_range_info(
    List<ScanRangeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_share_delegation_record_view(
    List<ShareDelegationRecordView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_share_submission_plan_view(
    List<ShareSubmissionPlanView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_share_workflow_recovery_view(
    List<ShareWorkflowRecoveryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_subtree_root(
    List<SubtreeRoot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_detail_output(
    List<TransactionDetailOutput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transaction_info(
    List<TransactionInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tx_data_request(
    List<TxDataRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vote_recovery_view(
    List<VoteRecoveryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vote_share_wire(
    List<VoteShareWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_wire_encrypted_share_json(
    List<WireEncryptedShareJson> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_next_step_view(NextStepView self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_signed_delegation_payload(
    ApiSignedDelegationPayload? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_signed_vote_commitments(
    ApiSignedVoteCommitments? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_proposal_result(
    ProposalResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_round_plan_view(RoundPlanView self, SseSerializer serializer);

  @protected
  void sse_encode_round_recovery_state_view(
    RoundRecoveryStateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_range_info(ScanRangeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_scan_result(ScanResult self, SseSerializer serializer);

  @protected
  void sse_encode_send_max_estimate_result(
    SendMaxEstimateResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_delegation_record_view(
    ShareDelegationRecordView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_submission_plan_view(
    ShareSubmissionPlanView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_workflow_recovery_view(
    ShareWorkflowRecoveryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shield_transparent_pczt_result(
    ShieldTransparentPcztResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shield_transparent_result(
    ShieldTransparentResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_shield_transparent_status(
    ShieldTransparentStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtree_indices(
    SubtreeIndices self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_subtree_root(SubtreeRoot self, SseSerializer serializer);

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_detail(
    TransactionDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_detail_output(
    TransactionDetailOutput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transaction_info(
    TransactionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tx_data_request(TxDataRequest self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_ur_decode_result(
    UrDecodeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vote_commitment_wire(
    VoteCommitmentWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vote_recovery_view(
    VoteRecoveryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vote_share_wire(VoteShareWire self, SseSerializer serializer);

  @protected
  void sse_encode_voting_round_params(
    VotingRoundParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_balance(WalletBalance self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_creation_result(
    WalletCreationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_import_result(
    WalletImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wire_encrypted_share_json(
    WireEncryptedShareJson self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
