// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'api/sync.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressValidationResult dco_decode_address_validation_result(dynamic raw);

  @protected
  BlockMetaInfo dco_decode_block_meta_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  List<BlockMetaInfo> dco_decode_list_block_meta_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ScanRangeInfo> dco_decode_list_scan_range_info(dynamic raw);

  @protected
  List<SubtreeRoot> dco_decode_list_subtree_root(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ScanRangeInfo dco_decode_scan_range_info(dynamic raw);

  @protected
  ScanResult dco_decode_scan_result(dynamic raw);

  @protected
  SubtreeRoot dco_decode_subtree_root(dynamic raw);

  @protected
  SyncProgress dco_decode_sync_progress(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WalletBalance dco_decode_wallet_balance(dynamic raw);

  @protected
  WalletCreationResult dco_decode_wallet_creation_result(dynamic raw);

  @protected
  WalletImportResult dco_decode_wallet_import_result(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressValidationResult sse_decode_address_validation_result(
    SseDeserializer deserializer,
  );

  @protected
  BlockMetaInfo sse_decode_block_meta_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<BlockMetaInfo> sse_decode_list_block_meta_info(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ScanRangeInfo> sse_decode_list_scan_range_info(
    SseDeserializer deserializer,
  );

  @protected
  List<SubtreeRoot> sse_decode_list_subtree_root(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ScanRangeInfo sse_decode_scan_range_info(SseDeserializer deserializer);

  @protected
  ScanResult sse_decode_scan_result(SseDeserializer deserializer);

  @protected
  SubtreeRoot sse_decode_subtree_root(SseDeserializer deserializer);

  @protected
  SyncProgress sse_decode_sync_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WalletBalance sse_decode_wallet_balance(SseDeserializer deserializer);

  @protected
  WalletCreationResult sse_decode_wallet_creation_result(
    SseDeserializer deserializer,
  );

  @protected
  WalletImportResult sse_decode_wallet_import_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_validation_result(
    AddressValidationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_block_meta_info(BlockMetaInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_list_block_meta_info(
    List<BlockMetaInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scan_range_info(
    List<ScanRangeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_subtree_root(
    List<SubtreeRoot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_scan_range_info(ScanRangeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_scan_result(ScanResult self, SseSerializer serializer);

  @protected
  void sse_encode_subtree_root(SubtreeRoot self, SseSerializer serializer);

  @protected
  void sse_encode_sync_progress(SyncProgress self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_balance(WalletBalance self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_creation_result(
    WalletCreationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_import_result(
    WalletImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
