// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KeystoneAccountInfo {
  final String name;
  final String ufvk;
  final int index;
  final Uint8List seedFingerprint;

  const KeystoneAccountInfo({
    required this.name,
    required this.ufvk,
    required this.index,
    required this.seedFingerprint,
  });

  @override
  int get hashCode =>
      name.hashCode ^ ufvk.hashCode ^ index.hashCode ^ seedFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeystoneAccountInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          ufvk == other.ufvk &&
          index == other.index &&
          seedFingerprint == other.seedFingerprint;
}

class UrDecodeResult {
  final bool complete;
  final int progress;
  final Uint8List? data;
  final String? urType;

  const UrDecodeResult({
    required this.complete,
    required this.progress,
    this.data,
    this.urType,
  });

  @override
  int get hashCode =>
      complete.hashCode ^ progress.hashCode ^ data.hashCode ^ urType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UrDecodeResult &&
          runtimeType == other.runtimeType &&
          complete == other.complete &&
          progress == other.progress &&
          data == other.data &&
          urType == other.urType;
}

class ZcashBatchMessageInput {
  final String id;
  final Uint8List pcztBytes;

  const ZcashBatchMessageInput({required this.id, required this.pcztBytes});

  @override
  int get hashCode => id.hashCode ^ pcztBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZcashBatchMessageInput &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pcztBytes == other.pcztBytes;
}

class ZcashBatchSignResult {
  final int version;
  final String requestId;
  final List<ZcashBatchSignedMessage> results;

  const ZcashBatchSignResult({
    required this.version,
    required this.requestId,
    required this.results,
  });

  @override
  int get hashCode => version.hashCode ^ requestId.hashCode ^ results.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZcashBatchSignResult &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          requestId == other.requestId &&
          results == other.results;
}

class ZcashBatchSignedMessage {
  final String id;
  final int status;
  final int kind;
  final Uint8List signedPcztBytes;
  final String payloadDigestHex;

  const ZcashBatchSignedMessage({
    required this.id,
    required this.status,
    required this.kind,
    required this.signedPcztBytes,
    required this.payloadDigestHex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      status.hashCode ^
      kind.hashCode ^
      signedPcztBytes.hashCode ^
      payloadDigestHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZcashBatchSignedMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          status == other.status &&
          kind == other.kind &&
          signedPcztBytes == other.signedPcztBytes &&
          payloadDigestHex == other.payloadDigestHex;
}
