#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OVERRIDES_PATH="$ROOT_DIR/linux/FlavorOverrides.cmake"
DIST_DIR="$ROOT_DIR/dist/linux"
BUILD_MODE="release"
ARCHIVE="true"
FLAVORS=()

usage() {
  cat <<USAGE
Usage: scripts/build-linux-release.sh [options]

Build Linux flavor artifacts with separate application identities.

Options:
  --flavor <mainnet|testnet>     Build one flavor. Can be repeated.
  --flavors <a,b>                Build comma-separated flavors.
  --build-mode <release|profile|debug>
                                 Flutter build mode. Default: release.
  --no-archive                   Copy bundles to dist/linux without .tar.gz.
  -h, --help                     Show this help.

Environment:
  VIZOR_LINUX_FLAVOR             Single flavor when no --flavor is provided.
  VIZOR_LINUX_FLAVORS            Comma-separated flavors when no --flavor is provided.
  VIZOR_RELEASE_BUILD_NAME       Native build name. Defaults to VIZOR_RELEASE_VERSION.
  VIZOR_RELEASE_BUILD_NUMBER     Native build number and Dart release build number.
  VIZOR_RELEASE_ARCH             Release arch used by update metadata.
  VIZOR_RELEASE_REPOSITORY       owner/name repository for update metadata.
  VIZOR_UPDATE_CHECK_ENABLED     true only for builds that should check updates.
  FVM_BIN                        fvm executable path. Default: fvm.

Default flavors: mainnet,testnet
USAGE
}

split_flavors() {
  local raw="$1"
  local item
  local -a items=()
  IFS=',' read -ra items <<< "$raw"
  for item in "${items[@]}"; do
    item="${item//[[:space:]]/}"
    [[ -n "$item" ]] && FLAVORS+=("$item")
  done
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --flavor)
      FLAVORS+=("$2")
      shift 2
      ;;
    --flavors)
      split_flavors "$2"
      shift 2
      ;;
    --build-mode)
      BUILD_MODE="$2"
      shift 2
      ;;
    --no-archive)
      ARCHIVE="false"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ${#FLAVORS[@]} -eq 0 ]]; then
  if [[ -n "${VIZOR_LINUX_FLAVORS:-}" ]]; then
    split_flavors "$VIZOR_LINUX_FLAVORS"
  elif [[ -n "${VIZOR_LINUX_FLAVOR:-}" ]]; then
    FLAVORS+=("$VIZOR_LINUX_FLAVOR")
  else
    FLAVORS=(mainnet testnet)
  fi
fi

case "$BUILD_MODE" in
  release|profile|debug) ;;
  *)
    echo "Unsupported build mode: $BUILD_MODE" >&2
    exit 2
    ;;
esac

FVM_BIN="${FVM_BIN:-fvm}"
export CMAKE_BUILD_PARALLEL_LEVEL="${CMAKE_BUILD_PARALLEL_LEVEL:-2}"

cleanup() {
  rm -f "$OVERRIDES_PATH"
}
trap cleanup EXIT

normalize_flavor() {
  case "$1" in
    main|mainnet) echo "mainnet" ;;
    test|testnet) echo "testnet" ;;
    *)
      echo "Unsupported Linux flavor: $1" >&2
      exit 2
      ;;
  esac
}

load_flavor_metadata() {
  local flavor="$1"
  case "$flavor" in
    mainnet)
      APP_IDENTIFIER="vizor"
      APP_DISPLAY_NAME="Vizor"
      BINARY_NAME="vizor"
      APPLICATION_ID="app.keplr.vizor"
      ZCASH_DEFAULT_NETWORK="main"
      ARTIFACT_NAME="Vizor-linux"
      ;;
    testnet)
      APP_IDENTIFIER="vizor-testnet"
      APP_DISPLAY_NAME="Vizor Testnet"
      BINARY_NAME="vizor-testnet"
      APPLICATION_ID="app.keplr.vizor.testnet"
      ZCASH_DEFAULT_NETWORK="test"
      ARTIFACT_NAME="Vizor-Testnet-linux"
      ;;
    *)
      echo "Unsupported Linux flavor: $flavor" >&2
      exit 2
      ;;
  esac
}

write_flavor_overrides() {
  cat > "$OVERRIDES_PATH" <<EOF
# Generated by scripts/build-linux-release.sh; do not commit.
set(APP_IDENTIFIER "$APP_IDENTIFIER")
set(APP_DISPLAY_NAME "$APP_DISPLAY_NAME")
set(BINARY_NAME "$BINARY_NAME")
set(APPLICATION_ID "$APPLICATION_ID")
EOF
}

find_bundle_dir() {
  local bundle
  local -a bundles=()
  while IFS= read -r bundle; do
    bundles+=("$bundle")
  done < <(find "$ROOT_DIR/build/linux" -type d -path "*/$BUILD_MODE/bundle" | sort)

  if [[ ${#bundles[@]} -ne 1 ]]; then
    echo "Expected exactly one Linux $BUILD_MODE bundle, found ${#bundles[@]}" >&2
    printf '%s\n' "${bundles[@]}" >&2
    exit 1
  fi

  echo "${bundles[0]}"
}

build_flavor() {
  local flavor="$1"
  load_flavor_metadata "$flavor"
  local artifact_name="$ARTIFACT_NAME"
  if [[ "$BUILD_MODE" != "release" ]]; then
    artifact_name="$artifact_name-$BUILD_MODE"
  fi

  echo "==> Building Linux $flavor ($APP_DISPLAY_NAME, $APPLICATION_ID)"
  write_flavor_overrides
  rm -rf "$ROOT_DIR/build/linux"

  (
    cd "$ROOT_DIR"
    "$FVM_BIN" flutter pub get
    flutter_args=(
      flutter build linux "--$BUILD_MODE"
      --dart-define="ZCASH_DEFAULT_NETWORK=$ZCASH_DEFAULT_NETWORK"
      --dart-define="VIZOR_RELEASE_FLAVOR=${VIZOR_RELEASE_FLAVOR:-$flavor}"
      --dart-define="VIZOR_RELEASE_ARCH=${VIZOR_RELEASE_ARCH:-}"
      --dart-define="VIZOR_RELEASE_REPOSITORY=${VIZOR_RELEASE_REPOSITORY:-}"
      --dart-define="VIZOR_UPDATE_CHECK_ENABLED=${VIZOR_UPDATE_CHECK_ENABLED:-false}"
    )
    if [[ -n "${VIZOR_RELEASE_VERSION:-}" ]]; then
      release_build_name="${VIZOR_RELEASE_BUILD_NAME:-$VIZOR_RELEASE_VERSION}"
      flutter_args+=(
        --dart-define="VIZOR_RELEASE_VERSION=$VIZOR_RELEASE_VERSION"
        --build-name "$release_build_name"
      )
    fi
    if [[ -n "${VIZOR_RELEASE_BUILD_NUMBER:-}" ]]; then
      flutter_args+=(
        --dart-define="VIZOR_RELEASE_BUILD_NUMBER=$VIZOR_RELEASE_BUILD_NUMBER"
        --build-number "$VIZOR_RELEASE_BUILD_NUMBER"
      )
    fi
    "$FVM_BIN" "${flutter_args[@]}"
  )

  local bundle_dir
  bundle_dir="$(find_bundle_dir)"
  local staging_dir="$DIST_DIR/$artifact_name"

  rm -rf "$staging_dir"
  mkdir -p "$DIST_DIR"
  cp -a "$bundle_dir/." "$staging_dir/"

  if [[ ! -x "$staging_dir/$BINARY_NAME" ]]; then
    echo "Expected executable $staging_dir/$BINARY_NAME" >&2
    exit 1
  fi

  if [[ "$ARCHIVE" == "true" ]]; then
    rm -f "$DIST_DIR/$artifact_name.tar.gz"
    tar -C "$DIST_DIR" -czf "$DIST_DIR/$artifact_name.tar.gz" "$artifact_name"
  fi
}

for raw_flavor in "${FLAVORS[@]}"; do
  build_flavor "$(normalize_flavor "$raw_flavor")"
done

cleanup
echo "Linux artifacts written to $DIST_DIR"
