// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../wallet/keystone.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Check if a Keystone device is connected via USB.
Future<bool> isKeystoneConnected() =>
    RustLib.instance.api.crateApiKeystoneIsKeystoneConnected();

/// Sign PCZT bytes via Keystone USB. Returns signed PCZT bytes.
/// The device will display the transaction for user confirmation.
Future<Uint8List> keystoneUsbSignPczt({required List<int> pcztBytes}) => RustLib
    .instance
    .api
    .crateApiKeystoneKeystoneUsbSignPczt(pcztBytes: pcztBytes);

/// Encode PCZT bytes to a UR string for QR code display.
Future<String> encodePcztToUr({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiKeystoneEncodePcztToUr(pcztBytes: pcztBytes);

/// Decode a UR string (from QR scan) to PCZT bytes.
Future<Uint8List> decodeUrToPczt({required String urString}) =>
    RustLib.instance.api.crateApiKeystoneDecodeUrToPczt(urString: urString);

/// Decode a single UR part (from animated QR scan). Stateful — accumulates parts
/// until the full UR is decoded. `expected_ur_type` pins the scan to one UR
/// registry type (e.g. `"zcash-pczt"`); parts of any other type are rejected.
/// The session auto-resets on completion or when the expected type changes.
Future<UrDecodeResult> decodeUrPart({
  required String part_,
  required String expectedUrType,
}) => RustLib.instance.api.crateApiKeystoneDecodeUrPart(
  part_: part_,
  expectedUrType: expectedUrType,
);

/// Encode PCZT bytes into multiple UR parts for animated QR display.
Future<List<String>> encodePcztUrParts({
  required List<int> pcztBytes,
  required BigInt maxFragmentLen,
}) => RustLib.instance.api.crateApiKeystoneEncodePcztUrParts(
  pcztBytes: pcztBytes,
  maxFragmentLen: maxFragmentLen,
);

/// Decode ZcashAccounts from raw CBOR bytes (from animated QR scan result).
Future<List<KeystoneAccountInfo>> decodeAccountsFromCbor({
  required List<int> cbor,
}) => RustLib.instance.api.crateApiKeystoneDecodeAccountsFromCbor(cbor: cbor);

/// Decode raw PCZT bytes from a ZcashPczt CBOR envelope (from animated QR scan result).
Future<Uint8List> decodePcztFromCbor({required List<int> cbor}) =>
    RustLib.instance.api.crateApiKeystoneDecodePcztFromCbor(cbor: cbor);

/// Decode a ZcashAccounts UR string to account info list.
Future<List<KeystoneAccountInfo>> decodeAccountsUr({
  required String urString,
}) => RustLib.instance.api.crateApiKeystoneDecodeAccountsUr(urString: urString);
