// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Check if a Keystone device is connected via USB.
Future<bool> isKeystoneConnected() =>
    RustLib.instance.api.crateApiKeystoneIsKeystoneConnected();

/// Sign PCZT bytes via Keystone USB. Returns signed PCZT bytes.
/// The device will display the transaction for user confirmation.
Future<Uint8List> keystoneUsbSignPczt({required List<int> pcztBytes}) => RustLib
    .instance
    .api
    .crateApiKeystoneKeystoneUsbSignPczt(pcztBytes: pcztBytes);

/// Encode PCZT bytes to a UR string for QR code display.
Future<String> encodePcztToUr({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiKeystoneEncodePcztToUr(pcztBytes: pcztBytes);

/// Decode a UR string (from QR scan) to PCZT bytes.
Future<Uint8List> decodeUrToPczt({required String urString}) =>
    RustLib.instance.api.crateApiKeystoneDecodeUrToPczt(urString: urString);

/// Decode a ZcashAccounts UR string to account info list.
Future<List<KeystoneAccountInfo>> decodeAccountsUr({
  required String urString,
}) => RustLib.instance.api.crateApiKeystoneDecodeAccountsUr(urString: urString);

class KeystoneAccountInfo {
  final String name;
  final String ufvk;
  final int index;
  final Uint8List seedFingerprint;

  const KeystoneAccountInfo({
    required this.name,
    required this.ufvk,
    required this.index,
    required this.seedFingerprint,
  });

  @override
  int get hashCode =>
      name.hashCode ^ ufvk.hashCode ^ index.hashCode ^ seedFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeystoneAccountInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          ufvk == other.ufvk &&
          index == other.index &&
          seedFingerprint == other.seedFingerprint;
}
