// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> updateChainTip({
  required String dbPath,
  required String network,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncUpdateChainTip(
  dbPath: dbPath,
  network: network,
  height: height,
);

Future<void> putSubtreeRoots({
  required String dbPath,
  required String network,
  required List<SubtreeRoot> saplingRoots,
  required List<SubtreeRoot> orchardRoots,
}) => RustLib.instance.api.crateApiSyncPutSubtreeRoots(
  dbPath: dbPath,
  network: network,
  saplingRoots: saplingRoots,
  orchardRoots: orchardRoots,
);

Future<List<ScanRangeInfo>> suggestScanRanges({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncSuggestScanRanges(
  dbPath: dbPath,
  network: network,
);

Future<void> writeBlockMetadata({
  required String cachePath,
  required List<BlockMetaInfo> blocks,
}) => RustLib.instance.api.crateApiSyncWriteBlockMetadata(
  cachePath: cachePath,
  blocks: blocks,
);

Future<ScanResult> scanBlocks({
  required String dbPath,
  required String cachePath,
  required String network,
  required BigInt fromHeight,
  required String treeStateNetwork,
  required BigInt treeStateHeight,
  required String treeStateHash,
  required int treeStateTime,
  required String treeStateSaplingTree,
  required String treeStateOrchardTree,
  required BigInt limit,
}) => RustLib.instance.api.crateApiSyncScanBlocks(
  dbPath: dbPath,
  cachePath: cachePath,
  network: network,
  fromHeight: fromHeight,
  treeStateNetwork: treeStateNetwork,
  treeStateHeight: treeStateHeight,
  treeStateHash: treeStateHash,
  treeStateTime: treeStateTime,
  treeStateSaplingTree: treeStateSaplingTree,
  treeStateOrchardTree: treeStateOrchardTree,
  limit: limit,
);

Future<SyncProgress> getSyncStatus({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetSyncStatus(
  dbPath: dbPath,
  network: network,
);

Future<WalletBalance> getBalance({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetBalance(
  dbPath: dbPath,
  network: network,
);

/// Get the blocks directory path where Dart should write compact block files.
String getBlocksDir({required String cachePath}) =>
    RustLib.instance.api.crateApiSyncGetBlocksDir(cachePath: cachePath);

class BlockMetaInfo {
  final BigInt height;
  final Uint8List hash;
  final int time;
  final int saplingOutputsCount;
  final int orchardActionsCount;

  const BlockMetaInfo({
    required this.height,
    required this.hash,
    required this.time,
    required this.saplingOutputsCount,
    required this.orchardActionsCount,
  });

  @override
  int get hashCode =>
      height.hashCode ^
      hash.hashCode ^
      time.hashCode ^
      saplingOutputsCount.hashCode ^
      orchardActionsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockMetaInfo &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          hash == other.hash &&
          time == other.time &&
          saplingOutputsCount == other.saplingOutputsCount &&
          orchardActionsCount == other.orchardActionsCount;
}

class ScanRangeInfo {
  final BigInt start;
  final BigInt end;
  final int priority;

  const ScanRangeInfo({
    required this.start,
    required this.end,
    required this.priority,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRangeInfo &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          priority == other.priority;
}

class ScanResult {
  final BigInt blocksScanned;

  const ScanResult({required this.blocksScanned});

  @override
  int get hashCode => blocksScanned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          blocksScanned == other.blocksScanned;
}

class SubtreeRoot {
  final BigInt completingBlockHeight;
  final Uint8List rootHash;

  const SubtreeRoot({
    required this.completingBlockHeight,
    required this.rootHash,
  });

  @override
  int get hashCode => completingBlockHeight.hashCode ^ rootHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtreeRoot &&
          runtimeType == other.runtimeType &&
          completingBlockHeight == other.completingBlockHeight &&
          rootHash == other.rootHash;
}

class SyncProgress {
  final BigInt scannedHeight;
  final BigInt chainTipHeight;
  final bool isSyncing;

  const SyncProgress({
    required this.scannedHeight,
    required this.chainTipHeight,
    required this.isSyncing,
  });

  @override
  int get hashCode =>
      scannedHeight.hashCode ^ chainTipHeight.hashCode ^ isSyncing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          scannedHeight == other.scannedHeight &&
          chainTipHeight == other.chainTipHeight &&
          isSyncing == other.isSyncing;
}

class WalletBalance {
  final BigInt transparent;
  final BigInt sapling;
  final BigInt orchard;
  final BigInt total;

  const WalletBalance({
    required this.transparent,
    required this.sapling,
    required this.orchard,
    required this.total,
  });

  @override
  int get hashCode =>
      transparent.hashCode ^
      sapling.hashCode ^
      orchard.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBalance &&
          runtimeType == other.runtimeType &&
          transparent == other.transparent &&
          sapling == other.sapling &&
          orchard == other.orchard &&
          total == other.total;
}
