// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`

/// Set the desired sync mode. 0=none, 1=foreground, 2=background.
/// The running sync loop checks this each batch and exits if mismatched.
void setSyncMode({required int mode}) =>
    RustLib.instance.api.crateApiSyncSetSyncMode(mode: mode);

/// Get the current desired sync mode.
int getSyncMode() => RustLib.instance.api.crateApiSyncGetSyncMode();

/// Start a full sync. Streams progress events to Dart via StreamSink.
/// mode: 1=foreground, 2=background. Sync exits if desired mode changes.
Stream<ApiSyncProgressEvent> startFullSync({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required int mode,
}) => RustLib.instance.api.crateApiSyncStartFullSync(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  mode: mode,
);

/// Cancel a running full sync.
void cancelFullSync() => RustLib.instance.api.crateApiSyncCancelFullSync();

/// Check if a sync is currently running.
bool isSyncRunning() => RustLib.instance.api.crateApiSyncIsSyncRunning();

Future<void> updateChainTip({
  required String dbPath,
  required String network,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncUpdateChainTip(
  dbPath: dbPath,
  network: network,
  height: height,
);

Future<SubtreeIndices> getNextSubtreeIndices({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetNextSubtreeIndices(
  dbPath: dbPath,
  network: network,
);

Future<void> putSubtreeRoots({
  required String dbPath,
  required String network,
  required BigInt saplingStartIndex,
  required List<SubtreeRoot> saplingRoots,
  required BigInt orchardStartIndex,
  required List<SubtreeRoot> orchardRoots,
}) => RustLib.instance.api.crateApiSyncPutSubtreeRoots(
  dbPath: dbPath,
  network: network,
  saplingStartIndex: saplingStartIndex,
  saplingRoots: saplingRoots,
  orchardStartIndex: orchardStartIndex,
  orchardRoots: orchardRoots,
);

Future<List<ScanRangeInfo>> suggestScanRanges({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncSuggestScanRanges(
  dbPath: dbPath,
  network: network,
);

Future<void> writeBlockMetadata({
  required String cachePath,
  required List<BlockMetaInfo> blocks,
}) => RustLib.instance.api.crateApiSyncWriteBlockMetadata(
  cachePath: cachePath,
  blocks: blocks,
);

Future<ScanResult> scanBlocks({
  required String dbPath,
  required String cachePath,
  required String network,
  required BigInt fromHeight,
  required String treeStateNetwork,
  required BigInt treeStateHeight,
  required String treeStateHash,
  required int treeStateTime,
  required String treeStateSaplingTree,
  required String treeStateOrchardTree,
  required BigInt limit,
}) => RustLib.instance.api.crateApiSyncScanBlocks(
  dbPath: dbPath,
  cachePath: cachePath,
  network: network,
  fromHeight: fromHeight,
  treeStateNetwork: treeStateNetwork,
  treeStateHeight: treeStateHeight,
  treeStateHash: treeStateHash,
  treeStateTime: treeStateTime,
  treeStateSaplingTree: treeStateSaplingTree,
  treeStateOrchardTree: treeStateOrchardTree,
  limit: limit,
);

Future<SyncProgress> getSyncStatus({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetSyncStatus(
  dbPath: dbPath,
  network: network,
);

Future<WalletBalance> getBalance({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetBalance(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<BigInt> rewindToHeight({
  required String dbPath,
  required String network,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncRewindToHeight(
  dbPath: dbPath,
  network: network,
  height: height,
);

Future<AddressValidationResult> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiSyncValidateAddress(address: address);

/// Step 1: Propose a transfer. Returns proposal info including whether Sapling params are needed.
Future<ProposalResult> proposeSend({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String toAddress,
  required BigInt amountZatoshi,
  String? memo,
}) => RustLib.instance.api.crateApiSyncProposeSend(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  toAddress: toAddress,
  amountZatoshi: amountZatoshi,
  memo: memo,
);

/// Estimate the fee for a transfer without storing a proposal.
Future<BigInt> estimateFee({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String toAddress,
  required BigInt amountZatoshi,
  String? memo,
}) => RustLib.instance.api.crateApiSyncEstimateFee(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  toAddress: toAddress,
  amountZatoshi: amountZatoshi,
  memo: memo,
);

/// Step 2: Execute a previously proposed transfer and broadcast to the network.
/// spend_params_path and output_params_path are required only if needs_sapling_params was true.
Future<String> executeProposal({
  required String dbPath,
  required String lightwalletdUrl,
  required BigInt proposalId,
  required List<int> seed,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncExecuteProposal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  proposalId: proposalId,
  seed: seed,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

Future<String> getNextAvailableAddress({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetNextAvailableAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<List<TxDataRequest>> getTransactionDataRequests({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetTransactionDataRequests(
  dbPath: dbPath,
  network: network,
);

Future<void> decryptAndStoreTransaction({
  required String dbPath,
  required String network,
  required List<int> txBytes,
  BigInt? minedHeight,
}) => RustLib.instance.api.crateApiSyncDecryptAndStoreTransaction(
  dbPath: dbPath,
  network: network,
  txBytes: txBytes,
  minedHeight: minedHeight,
);

Future<void> setTransactionStatus({
  required String dbPath,
  required String network,
  required String txidHex,
  required PlatformInt64 status,
}) => RustLib.instance.api.crateApiSyncSetTransactionStatus(
  dbPath: dbPath,
  network: network,
  txidHex: txidHex,
  status: status,
);

Future<List<TransactionInfo>> getTransactionHistory({
  required String dbPath,
  required String network,
  int? limit,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetTransactionHistory(
  dbPath: dbPath,
  network: network,
  limit: limit,
  accountUuid: accountUuid,
);

String getBlocksDir({required String cachePath}) =>
    RustLib.instance.api.crateApiSyncGetBlocksDir(cachePath: cachePath);

/// Create a PCZT from a stored proposal for hardware wallet signing.
Future<Uint8List> createPcztFromProposal({
  required String dbPath,
  required String network,
  required BigInt proposalId,
}) => RustLib.instance.api.crateApiSyncCreatePcztFromProposal(
  dbPath: dbPath,
  network: network,
  proposalId: proposalId,
);

/// Add Orchard (and Sapling if needed) proofs to a PCZT locally. The output
/// is the "PCZT with proofs" half that is later combined with the signed PCZT
/// returned by the hardware wallet.
Future<Uint8List> addProofsToPczt({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiSyncAddProofsToPczt(pcztBytes: pcztBytes);

/// Redact information from a PCZT that the hardware signer does not need
/// (witnesses, proprietary metadata). The returned bytes are what is sent
/// to the Keystone device for signing.
Future<Uint8List> redactPcztForSigner({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiSyncRedactPcztForSigner(pcztBytes: pcztBytes);

/// Combine a PCZT-with-proofs and a PCZT-with-signatures, extract the final
/// transaction, store it in the wallet DB, and broadcast it to lightwalletd.
/// Returns the txid.
Future<String> extractAndBroadcastPczt({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required List<int> pcztWithProofsBytes,
  required List<int> pcztWithSignaturesBytes,
}) => RustLib.instance.api.crateApiSyncExtractAndBroadcastPczt(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  pcztWithProofsBytes: pcztWithProofsBytes,
  pcztWithSignaturesBytes: pcztWithSignaturesBytes,
);

class AddressValidationResult {
  final bool isValid;
  final String addressType;

  const AddressValidationResult({
    required this.isValid,
    required this.addressType,
  });

  @override
  int get hashCode => isValid.hashCode ^ addressType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressValidationResult &&
          runtimeType == other.runtimeType &&
          isValid == other.isValid &&
          addressType == other.addressType;
}

/// Progress event streamed to Dart during sync.
class ApiSyncProgressEvent {
  final BigInt scannedHeight;
  final BigInt chainTipHeight;
  final double percentage;
  final bool isSyncing;
  final bool isComplete;
  final bool hasNewTx;

  const ApiSyncProgressEvent({
    required this.scannedHeight,
    required this.chainTipHeight,
    required this.percentage,
    required this.isSyncing,
    required this.isComplete,
    required this.hasNewTx,
  });

  @override
  int get hashCode =>
      scannedHeight.hashCode ^
      chainTipHeight.hashCode ^
      percentage.hashCode ^
      isSyncing.hashCode ^
      isComplete.hashCode ^
      hasNewTx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSyncProgressEvent &&
          runtimeType == other.runtimeType &&
          scannedHeight == other.scannedHeight &&
          chainTipHeight == other.chainTipHeight &&
          percentage == other.percentage &&
          isSyncing == other.isSyncing &&
          isComplete == other.isComplete &&
          hasNewTx == other.hasNewTx;
}

class BlockMetaInfo {
  final BigInt height;
  final Uint8List hash;
  final int time;
  final int saplingOutputsCount;
  final int orchardActionsCount;

  const BlockMetaInfo({
    required this.height,
    required this.hash,
    required this.time,
    required this.saplingOutputsCount,
    required this.orchardActionsCount,
  });

  @override
  int get hashCode =>
      height.hashCode ^
      hash.hashCode ^
      time.hashCode ^
      saplingOutputsCount.hashCode ^
      orchardActionsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockMetaInfo &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          hash == other.hash &&
          time == other.time &&
          saplingOutputsCount == other.saplingOutputsCount &&
          orchardActionsCount == other.orchardActionsCount;
}

class ProposalResult {
  final BigInt proposalId;
  final bool needsSaplingParams;
  final BigInt feeZatoshi;

  const ProposalResult({
    required this.proposalId,
    required this.needsSaplingParams,
    required this.feeZatoshi,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^ needsSaplingParams.hashCode ^ feeZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalResult &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          needsSaplingParams == other.needsSaplingParams &&
          feeZatoshi == other.feeZatoshi;
}

class ScanRangeInfo {
  final BigInt start;
  final BigInt end;
  final int priority;

  const ScanRangeInfo({
    required this.start,
    required this.end,
    required this.priority,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRangeInfo &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          priority == other.priority;
}

class ScanResult {
  final BigInt blocksScanned;

  const ScanResult({required this.blocksScanned});

  @override
  int get hashCode => blocksScanned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          blocksScanned == other.blocksScanned;
}

class SubtreeIndices {
  final BigInt nextSapling;
  final BigInt nextOrchard;

  const SubtreeIndices({required this.nextSapling, required this.nextOrchard});

  @override
  int get hashCode => nextSapling.hashCode ^ nextOrchard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtreeIndices &&
          runtimeType == other.runtimeType &&
          nextSapling == other.nextSapling &&
          nextOrchard == other.nextOrchard;
}

class SubtreeRoot {
  final BigInt completingBlockHeight;
  final Uint8List rootHash;

  const SubtreeRoot({
    required this.completingBlockHeight,
    required this.rootHash,
  });

  @override
  int get hashCode => completingBlockHeight.hashCode ^ rootHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtreeRoot &&
          runtimeType == other.runtimeType &&
          completingBlockHeight == other.completingBlockHeight &&
          rootHash == other.rootHash;
}

class SyncProgress {
  final BigInt scannedHeight;
  final BigInt chainTipHeight;
  final bool isSyncing;

  const SyncProgress({
    required this.scannedHeight,
    required this.chainTipHeight,
    required this.isSyncing,
  });

  @override
  int get hashCode =>
      scannedHeight.hashCode ^ chainTipHeight.hashCode ^ isSyncing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          scannedHeight == other.scannedHeight &&
          chainTipHeight == other.chainTipHeight &&
          isSyncing == other.isSyncing;
}

class TransactionInfo {
  final String txidHex;
  final BigInt minedHeight;
  final bool expiredUnmined;
  final PlatformInt64 accountBalanceDelta;
  final BigInt fee;
  final BigInt blockTime;

  const TransactionInfo({
    required this.txidHex,
    required this.minedHeight,
    required this.expiredUnmined,
    required this.accountBalanceDelta,
    required this.fee,
    required this.blockTime,
  });

  @override
  int get hashCode =>
      txidHex.hashCode ^
      minedHeight.hashCode ^
      expiredUnmined.hashCode ^
      accountBalanceDelta.hashCode ^
      fee.hashCode ^
      blockTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionInfo &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          minedHeight == other.minedHeight &&
          expiredUnmined == other.expiredUnmined &&
          accountBalanceDelta == other.accountBalanceDelta &&
          fee == other.fee &&
          blockTime == other.blockTime;
}

class TxDataRequest {
  final String requestType;
  final String? txid;
  final String? address;
  final BigInt? blockRangeStart;
  final BigInt? blockRangeEnd;

  const TxDataRequest({
    required this.requestType,
    this.txid,
    this.address,
    this.blockRangeStart,
    this.blockRangeEnd,
  });

  @override
  int get hashCode =>
      requestType.hashCode ^
      txid.hashCode ^
      address.hashCode ^
      blockRangeStart.hashCode ^
      blockRangeEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxDataRequest &&
          runtimeType == other.runtimeType &&
          requestType == other.requestType &&
          txid == other.txid &&
          address == other.address &&
          blockRangeStart == other.blockRangeStart &&
          blockRangeEnd == other.blockRangeEnd;
}

class WalletBalance {
  final BigInt transparent;
  final BigInt sapling;
  final BigInt orchard;
  final BigInt transparentPending;
  final BigInt saplingPending;
  final BigInt orchardPending;
  final BigInt total;

  const WalletBalance({
    required this.transparent,
    required this.sapling,
    required this.orchard,
    required this.transparentPending,
    required this.saplingPending,
    required this.orchardPending,
    required this.total,
  });

  @override
  int get hashCode =>
      transparent.hashCode ^
      sapling.hashCode ^
      orchard.hashCode ^
      transparentPending.hashCode ^
      saplingPending.hashCode ^
      orchardPending.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBalance &&
          runtimeType == other.runtimeType &&
          transparent == other.transparent &&
          sapling == other.sapling &&
          orchard == other.orchard &&
          transparentPending == other.transparentPending &&
          saplingPending == other.saplingPending &&
          orchardPending == other.orchardPending &&
          total == other.total;
}
