// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'keystone.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `api_proposal_result`, `catch`, `enhance_pir_enabled`, `fetch_block_time`, `migration_status_from_balance`, `parse_network_and_migrate`, `payment_link_batch_pairs`, `run_full_sync_internal`, `to_wallet_action_sigs`, `to_wallet_migration_schedule`, `to_wallet_signed_messages`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MempoolObserverState`

/// Set the desired sync mode. 0=none, 1=foreground, 2=background.
/// The running sync loop checks this each batch and exits if mismatched.
void setSyncMode({required int mode}) =>
    RustLib.instance.api.crateApiSyncSetSyncMode(mode: mode);

/// Get the current desired sync mode.
int getSyncMode() => RustLib.instance.api.crateApiSyncGetSyncMode();

/// Update the foreground sync account whose pending transparent refreshes
/// should be scheduled first. Requests already in flight are not interrupted.
void setActiveSyncAccount({String? accountUuid}) => RustLib.instance.api
    .crateApiSyncSetActiveSyncAccount(accountUuid: accountUuid);

/// Enable private Ironwood transaction enhancement for future sync work.
void setEnhancePirEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSyncSetEnhancePirEnabled(enabled: enabled);

/// Start a full sync. Streams progress events to Dart via StreamSink.
/// mode: 1=foreground, 2=background. Sync exits if desired mode changes.
Stream<ApiSyncProgressEvent> startFullSync({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required int mode,
}) => RustLib.instance.api.crateApiSyncStartFullSync(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  mode: mode,
);

/// Blocking sync entrypoint that uses the same API-layer network parsing,
/// desired-mode globals, and running guard as `start_full_sync`, but without
/// a StreamSink. Used by Rust integration tests that want to stay on the
/// public API surface.
Future<void> runFullSyncBlocking({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required int mode,
}) => RustLib.instance.api.crateApiSyncRunFullSyncBlocking(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  mode: mode,
);

/// Cancel a running full sync.
void cancelFullSync() => RustLib.instance.api.crateApiSyncCancelFullSync();

/// Check whether a sync cancel has been requested.
bool isSyncCancelRequested() =>
    RustLib.instance.api.crateApiSyncIsSyncCancelRequested();

/// Check if a sync is currently running.
bool isSyncRunning() => RustLib.instance.api.crateApiSyncIsSyncRunning();

/// Runs an isolated scan for one short-lived payment-link claim database.
///
/// Claim syncs do not use the main wallet's process-global running guard or
/// desired mode. Different claim IDs can therefore scan independent databases
/// concurrently with each other and with the main wallet.
Future<void> runPaymentLinkClaimSync({
  required String claimId,
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required bool allowResubmit,
}) => RustLib.instance.api.crateApiSyncRunPaymentLinkClaimSync(
  claimId: claimId,
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  allowResubmit: allowResubmit,
);

/// Cancels only the isolated scan associated with `claim_id`.
void cancelPaymentLinkClaimSync({required String claimId}) => RustLib
    .instance
    .api
    .crateApiSyncCancelPaymentLinkClaimSync(claimId: claimId);

/// Start the background mempool observer.
///
/// Blocks until [`stop_mempool_observer`] is called or the
/// observer returns on an unrecoverable setup error. Only parsed
/// wallet-relevant mempool txs are pushed to `sink` as
/// [`ApiMempoolTxEvent`]s; unrelated txs are filtered inside Rust.
///
/// The FRB layer runs this on the Rust isolate thread pool, so
/// Dart can `await` the call while the observer keeps polling
/// lightwalletd in the background. Dart is expected to fire this
/// alongside `start_full_sync` and call `stop_mempool_observer`
/// alongside `cancel_full_sync` — the two lifecycles are parallel
/// but separately controlled (intentional: the same bug in one
/// path must not silently take down the other).
Stream<ApiMempoolTxEvent> startMempoolObserver({
  required String dbPath,
  required String network,
  required String lightwalletdUrl,
}) => RustLib.instance.api.crateApiSyncStartMempoolObserver(
  dbPath: dbPath,
  network: network,
  lightwalletdUrl: lightwalletdUrl,
);

/// Ask the running mempool observer to exit at the next cancel
/// check (inside the 100ms sleep slices or between stream
/// messages). Safe to call when no observer is running — the
/// stored cancel token is `None` in that case and this becomes a
/// no-op.
void stopMempoolObserver() =>
    RustLib.instance.api.crateApiSyncStopMempoolObserver();

/// Check whether the mempool observer task is currently running.
bool isMempoolObserverRunning() =>
    RustLib.instance.api.crateApiSyncIsMempoolObserverRunning();

Future<void> updateChainTip({
  required String dbPath,
  required String network,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncUpdateChainTip(
  dbPath: dbPath,
  network: network,
  height: height,
);

Future<SubtreeIndices> getNextSubtreeIndices({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetNextSubtreeIndices(
  dbPath: dbPath,
  network: network,
);

Future<void> putSubtreeRoots({
  required String dbPath,
  required String network,
  required BigInt saplingStartIndex,
  required List<SubtreeRoot> saplingRoots,
  required BigInt orchardStartIndex,
  required List<SubtreeRoot> orchardRoots,
  required BigInt ironwoodStartIndex,
  required List<SubtreeRoot> ironwoodRoots,
}) => RustLib.instance.api.crateApiSyncPutSubtreeRoots(
  dbPath: dbPath,
  network: network,
  saplingStartIndex: saplingStartIndex,
  saplingRoots: saplingRoots,
  orchardStartIndex: orchardStartIndex,
  orchardRoots: orchardRoots,
  ironwoodStartIndex: ironwoodStartIndex,
  ironwoodRoots: ironwoodRoots,
);

Future<List<ScanRangeInfo>> suggestScanRanges({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncSuggestScanRanges(
  dbPath: dbPath,
  network: network,
);

Future<void> writeBlockMetadata({
  required String cachePath,
  required List<BlockMetaInfo> blocks,
}) => RustLib.instance.api.crateApiSyncWriteBlockMetadata(
  cachePath: cachePath,
  blocks: blocks,
);

Future<ScanResult> scanBlocks({
  required String dbPath,
  required String cachePath,
  required String network,
  required BigInt fromHeight,
  required String treeStateNetwork,
  required BigInt treeStateHeight,
  required String treeStateHash,
  required int treeStateTime,
  required String treeStateSaplingTree,
  required String treeStateOrchardTree,
  required String treeStateIronwoodTree,
  required BigInt limit,
}) => RustLib.instance.api.crateApiSyncScanBlocks(
  dbPath: dbPath,
  cachePath: cachePath,
  network: network,
  fromHeight: fromHeight,
  treeStateNetwork: treeStateNetwork,
  treeStateHeight: treeStateHeight,
  treeStateHash: treeStateHash,
  treeStateTime: treeStateTime,
  treeStateSaplingTree: treeStateSaplingTree,
  treeStateOrchardTree: treeStateOrchardTree,
  treeStateIronwoodTree: treeStateIronwoodTree,
  limit: limit,
);

Future<SyncProgress> getSyncStatus({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetSyncStatus(
  dbPath: dbPath,
  network: network,
);

Future<WalletBalance> getBalance({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetBalance(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<BigInt> rewindToHeight({
  required String dbPath,
  required String network,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncRewindToHeight(
  dbPath: dbPath,
  network: network,
  height: height,
);

/// Validate a recipient address against the network this build talks to.
///
/// `network` is the usual `"main"` / `"test"` / `"regtest"` name; an unknown
/// name is a programming error and comes back as an `Err`, not as an invalid
/// address.
Future<AddressValidationResult> validateAddress({
  required String address,
  required String network,
}) => RustLib.instance.api.crateApiSyncValidateAddress(
  address: address,
  network: network,
);

/// Quotes the complete batch, including its actual destination addresses.
Future<BigInt> estimatePaymentLinkBatchFee({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<String> addresses,
  required BigInt amountZatoshi,
}) => RustLib.instance.api.crateApiSyncEstimatePaymentLinkBatchFee(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  addresses: addresses,
  amountZatoshi: amountZatoshi,
);

/// Proposes a Gift Card batch only if it fits in one funding transaction.
Future<ProposalResult> proposePaymentLinkBatch({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required List<String> addresses,
  required BigInt amountZatoshi,
}) => RustLib.instance.api.crateApiSyncProposePaymentLinkBatch(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  addresses: addresses,
  amountZatoshi: amountZatoshi,
);

/// Step 1: Propose a transfer. Returns proposal info including whether Sapling params are needed.
Future<ProposalResult> proposeSend({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String toAddress,
  required BigInt amountZatoshi,
  String? memo,
}) => RustLib.instance.api.crateApiSyncProposeSend(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  toAddress: toAddress,
  amountZatoshi: amountZatoshi,
  memo: memo,
);

/// Estimate the fee for a transfer without storing a proposal.
Future<BigInt> estimateFee({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String toAddress,
  required BigInt amountZatoshi,
  String? memo,
}) => RustLib.instance.api.crateApiSyncEstimateFee(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  toAddress: toAddress,
  amountZatoshi: amountZatoshi,
  memo: memo,
);

/// Estimate the maximum recipient amount for the current recipient and memo.
Future<SendMaxEstimateResult> estimateSendMax({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String toAddress,
  String? memo,
}) => RustLib.instance.api.crateApiSyncEstimateSendMax(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  toAddress: toAddress,
  memo: memo,
);

/// Propose a Gift Card claim from its temporary wallet. Uses the claim
/// confirmation policy and discards the outgoing viewing key, so the link's
/// seed cannot recover the recipient address.
Future<ProposalResult> proposePaymentLinkClaim({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String sendFlowId,
  required String toAddress,
  required BigInt amountZatoshi,
}) => RustLib.instance.api.crateApiSyncProposePaymentLinkClaim(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  sendFlowId: sendFlowId,
  toAddress: toAddress,
  amountZatoshi: amountZatoshi,
);

/// Estimate the maximum Gift Card claim under the claim confirmation policy.
Future<SendMaxEstimateResult> estimatePaymentLinkClaimMax({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String toAddress,
}) => RustLib.instance.api.crateApiSyncEstimatePaymentLinkClaimMax(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  toAddress: toAddress,
);

/// Step 2: Execute a previously proposed transfer and broadcast to the network.
/// spend_params_path and output_params_path are required only if needs_sapling_params was true.
Future<ExecuteProposalResult> executeProposal({
  required String dbPath,
  required String lightwalletdUrl,
  required BigInt proposalId,
  required String sendFlowId,
  required List<int> mnemonicBytes,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncExecuteProposal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  proposalId: proposalId,
  sendFlowId: sendFlowId,
  mnemonicBytes: mnemonicBytes,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

/// macOS-only software send path that keeps encrypted mnemonic payloads out of
/// Dart memory. Rust reads and decrypts the stored mnemonic, derives the seed,
/// and zeroizes intermediate material.
Future<ExecuteProposalResult> executeProposalWithMacosStoredMnemonic({
  required String dbPath,
  required String lightwalletdUrl,
  required BigInt proposalId,
  required String sendFlowId,
  required String password,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncExecuteProposalWithMacosStoredMnemonic(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  proposalId: proposalId,
  sendFlowId: sendFlowId,
  password: password,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

Future<IronwoodMigrationResult> migrateOrchardToIronwood({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required List<int> mnemonicBytes,
  required String password,
  required String saltBase64,
  required List<MigrationScheduledTransfer> approvedSchedule,
  required bool spacePreparationBroadcasts,
}) => RustLib.instance.api.crateApiSyncMigrateOrchardToIronwood(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  mnemonicBytes: mnemonicBytes,
  password: password,
  saltBase64: saltBase64,
  approvedSchedule: approvedSchedule,
  spacePreparationBroadcasts: spacePreparationBroadcasts,
);

/// User-attended Immediate migration. This directly spends Orchard notes into
/// Ironwood and intentionally does not create a staged migration run.
Future<IronwoodMigrationResult> migrateOrchardToIronwoodImmediately({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required List<int> mnemonicBytes,
  required BigInt approvedTotalInputZatoshi,
  required BigInt approvedFeeZatoshi,
  required BigInt approvedMigratedZatoshi,
  required int approvedInputNoteCount,
}) => RustLib.instance.api.crateApiSyncMigrateOrchardToIronwoodImmediately(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  mnemonicBytes: mnemonicBytes,
  approvedTotalInputZatoshi: approvedTotalInputZatoshi,
  approvedFeeZatoshi: approvedFeeZatoshi,
  approvedMigratedZatoshi: approvedMigratedZatoshi,
  approvedInputNoteCount: approvedInputNoteCount,
);

Future<KeystoneMigrationSigningRequest> prepareOrchardMigrationImmediatePczt({
  required String dbPath,
  required String network,
  required String accountUuid,
  required BigInt approvedTotalInputZatoshi,
  required BigInt approvedFeeZatoshi,
  required BigInt approvedMigratedZatoshi,
  required int approvedInputNoteCount,
}) => RustLib.instance.api.crateApiSyncPrepareOrchardMigrationImmediatePczt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  approvedTotalInputZatoshi: approvedTotalInputZatoshi,
  approvedFeeZatoshi: approvedFeeZatoshi,
  approvedMigratedZatoshi: approvedMigratedZatoshi,
  approvedInputNoteCount: approvedInputNoteCount,
);

Future<IronwoodMigrationResult> completeOrchardMigrationImmediatePczt({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String requestId,
  required List<KeystoneSignedMigrationMessage> signedMessages,
}) => RustLib.instance.api.crateApiSyncCompleteOrchardMigrationImmediatePczt(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  requestId: requestId,
  signedMessages: signedMessages,
);

Future<OrchardMigrationImmediatePlan?> getOrchardMigrationImmediatePlan({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetOrchardMigrationImmediatePlan(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<void> retireUnbroadcastOrchardMigration({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String expectedRunId,
}) => RustLib.instance.api.crateApiSyncRetireUnbroadcastOrchardMigration(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  expectedRunId: expectedRunId,
);

Future<void> abandonOrchardMigration({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String expectedRunId,
  required List<String> nativeAttemptedTxids,
}) => RustLib.instance.api.crateApiSyncAbandonOrchardMigration(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  expectedRunId: expectedRunId,
  nativeAttemptedTxids: nativeAttemptedTxids,
);

Future<MigrationStatus> getOrchardMigrationStatus({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetOrchardMigrationStatus(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Migration statuses for several accounts from a single wallet summary.
///
/// `get_orchard_migration_status` needs four per-account pool balances,
/// but obtaining them through `get_wallet_balance` computes a summary
/// across *every* account. Calling it once per account — which the
/// migration coordinator does on every poll — is therefore quadratic in
/// account count, and profiling showed it accounted for ~81% of all
/// balance computations in the process.
///
/// This computes the summary once and derives each account's status
/// from it. Statuses in one batch also share a single point-in-time
/// snapshot, instead of being read seconds apart as the per-account
/// loop did.
///
/// A per-account failure is reported in that entry's `error` rather
/// than failing the batch, so one bad account cannot blank the sweep.
Future<List<MigrationStatusEntry>> getOrchardMigrationStatuses({
  required String dbPath,
  required String network,
  required List<String> accountUuids,
}) => RustLib.instance.api.crateApiSyncGetOrchardMigrationStatuses(
  dbPath: dbPath,
  network: network,
  accountUuids: accountUuids,
);

Future<OrchardMigrationPrivatePlan?> getOrchardMigrationPrivatePlan({
  required String dbPath,
  required String network,
  required String accountUuid,
  required bool spacePreparationBroadcasts,
}) => RustLib.instance.api.crateApiSyncGetOrchardMigrationPrivatePlan(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  spacePreparationBroadcasts: spacePreparationBroadcasts,
);

/// Foreground-only migration preparation for the Swift-owned outbox.
/// Denomination stages may advance, and every currently provable signed child
/// is materialized, but scheduled child transactions are never broadcast here.
Future<IronwoodMigrationResult> prepareOrchardMigrationOutbox({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSyncPrepareOrchardMigrationOutbox(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  password: password,
  saltBase64: saltBase64,
);

Future<MigrationOutboxBatch?> exportOrchardMigrationOutbox({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSyncExportOrchardMigrationOutbox(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  password: password,
  saltBase64: saltBase64,
);

Future<void> reconcileOrchardMigrationOutboxReceipt({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String runId,
  required String txidHex,
  required String outcome,
  required int remoteHeight,
  String? responseMessage,
  required List<MigrationOutboxScheduleUpdate> scheduleUpdates,
  Uint8List? acceptedRawTransaction,
}) => RustLib.instance.api.crateApiSyncReconcileOrchardMigrationOutboxReceipt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  runId: runId,
  txidHex: txidHex,
  outcome: outcome,
  remoteHeight: remoteHeight,
  responseMessage: responseMessage,
  scheduleUpdates: scheduleUpdates,
  acceptedRawTransaction: acceptedRawTransaction,
);

Future<IronwoodMigrationResult> broadcastDueOrchardMigrationTransactions({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSyncBroadcastDueOrchardMigrationTransactions(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  password: password,
  saltBase64: saltBase64,
);

/// `wallet_open_tip_height` is the authoritative chain tip observed when the
/// desktop wallet-open epoch began. It floors the post-accept wallet-overdue
/// redraw so on-open overdue parts scheduled between the locally synced tip
/// and the network tip are redrawn by the single fallback acceptance instead
/// of staying wedged behind the consumed on-open allowance. Pass `None` when
/// no authoritative open tip is known.
Future<IronwoodMigrationResult> broadcastOneDueOrchardMigrationTransaction({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String password,
  required String saltBase64,
  int? walletOpenTipHeight,
}) =>
    RustLib.instance.api.crateApiSyncBroadcastOneDueOrchardMigrationTransaction(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      network: network,
      accountUuid: accountUuid,
      password: password,
      saltBase64: saltBase64,
      walletOpenTipHeight: walletOpenTipHeight,
    );

/// Prepares denomination PCZTs for the approved schedule, with expiry heights
/// derived from their planned broadcast heights.
Future<KeystoneMigrationSigningRequest>
prepareOrchardMigrationDenominationsPczt({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<MigrationScheduledTransfer> approvedSchedule,
  required bool spacePreparationBroadcasts,
}) => RustLib.instance.api.crateApiSyncPrepareOrchardMigrationDenominationsPczt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  approvedSchedule: approvedSchedule,
  spacePreparationBroadcasts: spacePreparationBroadcasts,
);

Future<String> createOrResumePrivateMigrationDraft({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<MigrationScheduledTransfer> approvedSchedule,
  required bool spacePreparationBroadcasts,
}) => RustLib.instance.api.crateApiSyncCreateOrResumePrivateMigrationDraft(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  approvedSchedule: approvedSchedule,
  spacePreparationBroadcasts: spacePreparationBroadcasts,
);

Future<IronwoodMigrationResult> completeOrchardMigrationDenominationsPczt({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String requestId,
  required List<KeystoneSignedMigrationMessage> signedMessages,
  required String password,
  required String saltBase64,
  required List<MigrationScheduledTransfer> approvedSchedule,
}) =>
    RustLib.instance.api.crateApiSyncCompleteOrchardMigrationDenominationsPczt(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      network: network,
      accountUuid: accountUuid,
      requestId: requestId,
      signedMessages: signedMessages,
      password: password,
      saltBase64: saltBase64,
      approvedSchedule: approvedSchedule,
    );

/// Prepares the split and migration PCZTs for one Keystone signing session.
///
/// The approved schedule must still match the denomination plan when the
/// signing request is created.
Future<KeystoneMigrationSigningRequest> prepareOrchardMigrationSingleQrPczt({
  required String dbPath,
  required String network,
  required String accountUuid,
  required List<MigrationScheduledTransfer> approvedSchedule,
  required bool spacePreparationBroadcasts,
}) => RustLib.instance.api.crateApiSyncPrepareOrchardMigrationSingleQrPczt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  approvedSchedule: approvedSchedule,
  spacePreparationBroadcasts: spacePreparationBroadcasts,
);

Future<IronwoodMigrationResult> completeOrchardMigrationSingleQrPczt({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String requestId,
  required List<KeystoneSignedMigrationMessage> signedMessages,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSyncCompleteOrchardMigrationSingleQrPczt(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  requestId: requestId,
  signedMessages: signedMessages,
  password: password,
  saltBase64: saltBase64,
);

Future<KeystoneMigrationSigningRequest> prepareOrchardMigrationBatchPczt({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncPrepareOrchardMigrationBatchPczt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<KeystoneMigrationProofStatus> keystoneMigrationProofStatus({
  required String requestId,
}) => RustLib.instance.api.crateApiSyncKeystoneMigrationProofStatus(
  requestId: requestId,
);

Future<void> discardKeystoneMigrationRequest({required String requestId}) =>
    RustLib.instance.api.crateApiSyncDiscardKeystoneMigrationRequest(
      requestId: requestId,
    );

Future<void> discardAllKeystoneMigrationRequests() =>
    RustLib.instance.api.crateApiSyncDiscardAllKeystoneMigrationRequests();

Future<IronwoodMigrationResult> completeOrchardMigrationBatchPczt({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String requestId,
  required List<KeystoneSignedMigrationMessage> signedMessages,
  required String password,
  required String saltBase64,
}) => RustLib.instance.api.crateApiSyncCompleteOrchardMigrationBatchPczt(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  requestId: requestId,
  signedMessages: signedMessages,
  password: password,
  saltBase64: saltBase64,
);

Future<IronwoodMigrationResult>
migrateOrchardToIronwoodWithMacosStoredMnemonic({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String password,
  required String saltBase64,
  required List<MigrationScheduledTransfer> approvedSchedule,
  required bool spacePreparationBroadcasts,
}) => RustLib.instance.api
    .crateApiSyncMigrateOrchardToIronwoodWithMacosStoredMnemonic(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      network: network,
      accountUuid: accountUuid,
      password: password,
      saltBase64: saltBase64,
      approvedSchedule: approvedSchedule,
      spacePreparationBroadcasts: spacePreparationBroadcasts,
    );

/// Dry-run transparent shielding without creating or broadcasting a transaction.
Future<ShieldTransparentStatus> getShieldTransparentStatus({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetShieldTransparentStatus(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<LedgerShieldingProgress> getLedgerShieldingProgress({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetLedgerShieldingProgress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

/// Create a height-appropriate transparent-shielding PCZT for hardware accounts.
Future<ShieldTransparentPcztResult> createShieldTransparentPczt({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncCreateShieldTransparentPczt(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
);

/// Shield spendable transparent funds into the account's shielded balance.
/// Software-account only.
Future<ShieldTransparentResult> shieldTransparentBalance({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required List<int> mnemonicBytes,
}) => RustLib.instance.api.crateApiSyncShieldTransparentBalance(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  mnemonicBytes: mnemonicBytes,
);

/// macOS-only software transparent shielding path that keeps encrypted mnemonic
/// payloads out of Dart memory. Rust reads and decrypts the stored mnemonic,
/// derives the seed, and zeroizes intermediate material.
Future<ShieldTransparentResult>
shieldTransparentBalanceWithMacosStoredMnemonic({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required String password,
}) => RustLib.instance.api
    .crateApiSyncShieldTransparentBalanceWithMacosStoredMnemonic(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      network: network,
      accountUuid: accountUuid,
      password: password,
    );

Future<String> getNextAvailableAddress({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String addressRequest,
}) => RustLib.instance.api.crateApiSyncGetNextAvailableAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  addressRequest: addressRequest,
);

Future<List<TxDataRequest>> getTransactionDataRequests({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetTransactionDataRequests(
  dbPath: dbPath,
  network: network,
);

Future<void> decryptAndStoreTransaction({
  required String dbPath,
  required String network,
  required List<int> txBytes,
  BigInt? minedHeight,
}) => RustLib.instance.api.crateApiSyncDecryptAndStoreTransaction(
  dbPath: dbPath,
  network: network,
  txBytes: txBytes,
  minedHeight: minedHeight,
);

Future<void> setTransactionStatus({
  required String dbPath,
  required String network,
  required String txidHex,
  required PlatformInt64 status,
}) => RustLib.instance.api.crateApiSyncSetTransactionStatus(
  dbPath: dbPath,
  network: network,
  txidHex: txidHex,
  status: status,
);

Future<List<TransactionInfo>> getTransactionHistory({
  required String dbPath,
  required String network,
  int? limit,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetTransactionHistory(
  dbPath: dbPath,
  network: network,
  limit: limit,
  accountUuid: accountUuid,
);

Future<int> getPreviousTransactionCountForAddress({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String address,
}) => RustLib.instance.api.crateApiSyncGetPreviousTransactionCountForAddress(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  address: address,
);

Future<BigInt> getExportBirthdayHeight({
  required String dbPath,
  required String network,
  required String accountUuid,
}) => RustLib.instance.api.crateApiSyncGetExportBirthdayHeight(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
);

Future<BigInt> getBlockTime({
  required String lightwalletdUrl,
  required BigInt height,
}) => RustLib.instance.api.crateApiSyncGetBlockTime(
  lightwalletdUrl: lightwalletdUrl,
  height: height,
);

Future<TransactionDetail> getTransactionDetail({
  required String dbPath,
  required String network,
  required String accountUuid,
  required String txidHex,
  required String txKind,
}) => RustLib.instance.api.crateApiSyncGetTransactionDetail(
  dbPath: dbPath,
  network: network,
  accountUuid: accountUuid,
  txidHex: txidHex,
  txKind: txKind,
);

String getBlocksDir({required String cachePath}) =>
    RustLib.instance.api.crateApiSyncGetBlocksDir(cachePath: cachePath);

/// Create a PCZT from a stored proposal for hardware wallet signing.
Future<Uint8List> createPcztFromProposal({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required BigInt proposalId,
  required String sendFlowId,
}) => RustLib.instance.api.crateApiSyncCreatePcztFromProposal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  proposalId: proposalId,
  sendFlowId: sendFlowId,
);

/// Create the two ordered PCZTs for a ZIP-320 Keystone send.
Future<TexPcztPairResult> createTexPcztsFromProposal({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required BigInt proposalId,
  required String sendFlowId,
}) => RustLib.instance.api.crateApiSyncCreateTexPcztsFromProposal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  proposalId: proposalId,
  sendFlowId: sendFlowId,
);

/// Release a stored proposal without executing it. Called by the Dart send
/// flow when the user cancels before `create_pczt_from_proposal` so the
/// proposal ID cannot be replayed. Idempotent.
Future<void> discardProposal({
  required BigInt proposalId,
  required String sendFlowId,
}) => RustLib.instance.api.crateApiSyncDiscardProposal(
  proposalId: proposalId,
  sendFlowId: sendFlowId,
);

/// Remove the replayable proposal capability but keep its owner-scoped wallet
/// input lock until the original expiry height. Use this when broadcast
/// acceptance is uncertain or the accepted transaction could not be persisted
/// locally, so a conflicting send cannot be created immediately.
Future<void> retainProposalLockUntilExpiry({
  required BigInt proposalId,
  required String sendFlowId,
}) => RustLib.instance.api.crateApiSyncRetainProposalLockUntilExpiry(
  proposalId: proposalId,
  sendFlowId: sendFlowId,
);

/// Kick off process-lifetime Orchard proving-key warm-up for sends.
///
/// Safe to call repeatedly. The first call starts a background worker and
/// returns immediately; proving blocks on the same shared cache if it catches
/// up before warm-up completes.
void warmOrchardProvingKeyCache() =>
    RustLib.instance.api.crateApiSyncWarmOrchardProvingKeyCache();

/// Add Orchard (and Sapling if needed) proofs to a PCZT locally. The output
/// is the wallet-owned proof PCZT that later receives compact signatures from
/// the hardware wallet. Legacy transparent-input paths combine it with a full
/// signed PCZT instead.
///
/// `spend_params_path` and `output_params_path` are only consulted when the
/// PCZT has a non-empty Sapling bundle (e.g. sending to a Sapling-only
/// recipient). Orchard-only sends can pass `None` for both. The caller is
/// responsible for ensuring the referenced files exist — the `proposal
/// .needsSaplingParams` flag on the propose result already tells the Dart
/// layer when it needs to download them.
Future<Uint8List> addProofsToPczt({
  required List<int> pcztBytes,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncAddProofsToPczt(
  pcztBytes: pcztBytes,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

/// Legacy full-PCZT signer redaction for transparent-input transactions that
/// Keystone's signatures-only batch response cannot represent.
Future<Uint8List> redactPcztForSigner({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiSyncRedactPcztForSigner(pcztBytes: pcztBytes);

/// Prepare one PCZT for Keystone's `zcash-sign-batch` request. This rejects
/// input types that the signatures-only response cannot represent and signing
/// sets above the device's 96-signature per-transaction limit.
Future<KeystoneBatchPczt> preparePcztForKeystoneBatch({
  required List<int> pcztBytes,
}) => RustLib.instance.api.crateApiSyncPreparePcztForKeystoneBatch(
  pcztBytes: pcztBytes,
);

/// Legacy full-PCZT completion for transparent-input transactions. Validate
/// and finalize every signed PCZT, broadcast parent before child, then
/// atomically persist only the accepted-or-ambiguous transaction prefix.
Future<StoreAndBroadcastPcztsResult> storeAndBroadcastSignedPcztsForProposal({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required BigInt proposalId,
  required String sendFlowId,
  required List<Uint8List> pcztWithProofs,
  required List<Uint8List> pcztWithSignatures,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncStoreAndBroadcastSignedPcztsForProposal(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  proposalId: proposalId,
  sendFlowId: sendFlowId,
  pcztWithProofs: pcztWithProofs,
  pcztWithSignatures: pcztWithSignatures,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

/// Apply a compact Keystone batch response to wallet-owned proof PCZTs,
/// validate every signature and transaction before network I/O, then broadcast
/// and persist with the same proposal-lock guarantees as the full-PCZT path.
Future<StoreAndBroadcastPcztsResult>
storeAndBroadcastPcztsWithKeystoneSignaturesForProposal({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required BigInt proposalId,
  required String sendFlowId,
  required List<Uint8List> pcztWithProofs,
  required List<Uint8List> signatureBlobs,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api
    .crateApiSyncStoreAndBroadcastPcztsWithKeystoneSignaturesForProposal(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      network: network,
      proposalId: proposalId,
      sendFlowId: sendFlowId,
      pcztWithProofs: pcztWithProofs,
      signatureBlobs: signatureBlobs,
      spendParamsPath: spendParamsPath,
      outputParamsPath: outputParamsPath,
    );

/// Computes the stable transaction ID before a finalized PCZT crosses the
/// irreversible broadcast boundary.
String getPcztTxid({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiSyncGetPcztTxid(pcztBytes: pcztBytes);

/// Returns the expiry height committed to by an IO-finalized PCZT.
int getPcztExpiryHeight({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiSyncGetPcztExpiryHeight(pcztBytes: pcztBytes);

/// Combine a PCZT-with-proofs and a PCZT-with-signatures, extract the final
/// transaction, store it in the wallet DB, and broadcast it to lightwalletd.
/// Returns the txid.
///
/// `spend_params_path` / `output_params_path` are required whenever the
/// combined PCZT has a non-empty Sapling bundle (e.g. the original proposal
/// had `needsSaplingParams == true`). They are used both to verify the
/// extracted transaction in-memory before broadcast and by
/// `extract_and_store_transaction_from_pczt` after broadcast. Orchard-only
/// sends can pass `None` for both. Mirrors the `add_proofs_to_pczt`
/// contract: if you needed to supply params there, you need them here too.
Future<ExtractAndBroadcastPcztResult> extractAndBroadcastPczt({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required List<int> pcztWithProofsBytes,
  required List<int> pcztWithSignaturesBytes,
  String? spendParamsPath,
  String? outputParamsPath,
}) => RustLib.instance.api.crateApiSyncExtractAndBroadcastPczt(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  pcztWithProofsBytes: pcztWithProofsBytes,
  pcztWithSignaturesBytes: pcztWithSignaturesBytes,
  spendParamsPath: spendParamsPath,
  outputParamsPath: outputParamsPath,
);

Future<PaymentLinkSpendEvidence> getPaymentLinkSpendEvidence({
  required String dbPath,
  required String accountUuid,
  required String claimTxids,
}) => RustLib.instance.api.crateApiSyncGetPaymentLinkSpendEvidence(
  dbPath: dbPath,
  accountUuid: accountUuid,
  claimTxids: claimTxids,
);

/// End the foreground signing session during normal application shutdown.
/// Durable signed or submitted transactions are retained for recovery.
Future<void> shutdownSigningReservations() =>
    RustLib.instance.api.crateApiSyncShutdownSigningReservations();

Future<EnhanceRecoveryStatus> getEnhanceRecoveryStatus({
  required String dbPath,
  required String network,
}) => RustLib.instance.api.crateApiSyncGetEnhanceRecoveryStatus(
  dbPath: dbPath,
  network: network,
);

/// Flat address-validation result for the Dart side.
///
/// `wrong_network` marks the one case where `is_valid` is false but the input
/// is still a real Zcash address: it decoded fine, and `address_type` carries
/// the kind it decoded to, but its encoding belongs to a network other than
/// the one this build talks to. For input that is not an address we can send
/// to at all, `address_type` is `"invalid"` and `wrong_network` is false.
class AddressValidationResult {
  final bool isValid;
  final String addressType;
  final bool wrongNetwork;

  const AddressValidationResult({
    required this.isValid,
    required this.addressType,
    required this.wrongNetwork,
  });

  @override
  int get hashCode =>
      isValid.hashCode ^ addressType.hashCode ^ wrongNetwork.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressValidationResult &&
          runtimeType == other.runtimeType &&
          isValid == other.isValid &&
          addressType == other.addressType &&
          wrongNetwork == other.wrongNetwork;
}

/// Event emitted by the mempool observer when a wallet-relevant
/// transaction appears on lightwalletd's mempool stream. Mirrored
/// one-to-one from `sync_engine::mempool::MempoolTxEvent` for FRB
/// codegen.
class ApiMempoolTxEvent {
  /// Lower-case hex of the tx id.
  final String txidHex;

  /// Account UUIDs that this event is known to affect. Empty means the
  /// tx is wallet-relevant but not account-scoped enough for Rust to
  /// name the account, so Dart keeps the legacy behavior of refreshing
  /// the active account.
  final List<String> accountUuids;

  /// `true` when the tx is wallet-relevant: either the wallet DB
  /// already has this txid as unmined, or the observer decrypted
  /// and stored a new inbound transaction from the mempool. Dart
  /// uses this flag to decide whether to refresh balance + history
  /// immediately.
  final bool matched;

  const ApiMempoolTxEvent({
    required this.txidHex,
    required this.accountUuids,
    required this.matched,
  });

  @override
  int get hashCode =>
      txidHex.hashCode ^ accountUuids.hashCode ^ matched.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiMempoolTxEvent &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          accountUuids == other.accountUuids &&
          matched == other.matched;
}

/// Progress event streamed to Dart during sync.
class ApiSyncProgressEvent {
  final BigInt scannedHeight;
  final BigInt chainTipHeight;
  final double percentage;

  /// UI-only smoothed progress target. Dart chooses the display tick and
  /// advances at most `display_target_blocks` virtual blocks to this target.
  final double displayTargetPercentage;
  final BigInt displayTargetBlocks;
  final bool isSyncing;
  final bool isComplete;
  final bool hasNewTx;

  /// Completed and total work units for measurable preparation phases.
  final BigInt phaseCompletedUnits;
  final BigInt phaseTotalUnits;

  /// Current sync phase. Preparation adds `"active_utxo"` and
  /// `"chain_prepare"` before the existing download/scan phases.
  final String phase;

  const ApiSyncProgressEvent({
    required this.scannedHeight,
    required this.chainTipHeight,
    required this.percentage,
    required this.displayTargetPercentage,
    required this.displayTargetBlocks,
    required this.isSyncing,
    required this.isComplete,
    required this.hasNewTx,
    required this.phaseCompletedUnits,
    required this.phaseTotalUnits,
    required this.phase,
  });

  @override
  int get hashCode =>
      scannedHeight.hashCode ^
      chainTipHeight.hashCode ^
      percentage.hashCode ^
      displayTargetPercentage.hashCode ^
      displayTargetBlocks.hashCode ^
      isSyncing.hashCode ^
      isComplete.hashCode ^
      hasNewTx.hashCode ^
      phaseCompletedUnits.hashCode ^
      phaseTotalUnits.hashCode ^
      phase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSyncProgressEvent &&
          runtimeType == other.runtimeType &&
          scannedHeight == other.scannedHeight &&
          chainTipHeight == other.chainTipHeight &&
          percentage == other.percentage &&
          displayTargetPercentage == other.displayTargetPercentage &&
          displayTargetBlocks == other.displayTargetBlocks &&
          isSyncing == other.isSyncing &&
          isComplete == other.isComplete &&
          hasNewTx == other.hasNewTx &&
          phaseCompletedUnits == other.phaseCompletedUnits &&
          phaseTotalUnits == other.phaseTotalUnits &&
          phase == other.phase;
}

class BlockMetaInfo {
  final BigInt height;
  final Uint8List hash;
  final int time;
  final int saplingOutputsCount;
  final int orchardActionsCount;

  const BlockMetaInfo({
    required this.height,
    required this.hash,
    required this.time,
    required this.saplingOutputsCount,
    required this.orchardActionsCount,
  });

  @override
  int get hashCode =>
      height.hashCode ^
      hash.hashCode ^
      time.hashCode ^
      saplingOutputsCount.hashCode ^
      orchardActionsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockMetaInfo &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          hash == other.hash &&
          time == other.time &&
          saplingOutputsCount == other.saplingOutputsCount &&
          orchardActionsCount == other.orchardActionsCount;
}

/// Durable pending work, including obligations that cannot currently be retried.
class EnhanceRecoveryStatus {
  final int queries;
  final int rediscovery;
  final int suspended;

  /// Private transaction-status obligations still awaiting Status PIR. A
  /// deferred private status failure leaves these durable without payload
  /// work, so they count toward a recovery-only sync restart.
  final int status;
  final String serviceState;

  const EnhanceRecoveryStatus({
    required this.queries,
    required this.rediscovery,
    required this.suspended,
    required this.status,
    required this.serviceState,
  });

  @override
  int get hashCode =>
      queries.hashCode ^
      rediscovery.hashCode ^
      suspended.hashCode ^
      status.hashCode ^
      serviceState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnhanceRecoveryStatus &&
          runtimeType == other.runtimeType &&
          queries == other.queries &&
          rediscovery == other.rediscovery &&
          suspended == other.suspended &&
          status == other.status &&
          serviceState == other.serviceState;
}

class ExecuteProposalResult {
  final String txids;
  final String status;
  final int broadcastedCount;
  final int totalCount;
  final String? message;

  /// Server rejection is distinct from a missing response, but is not finality.
  final String? broadcastFailureKind;

  const ExecuteProposalResult({
    required this.txids,
    required this.status,
    required this.broadcastedCount,
    required this.totalCount,
    this.message,
    this.broadcastFailureKind,
  });

  @override
  int get hashCode =>
      txids.hashCode ^
      status.hashCode ^
      broadcastedCount.hashCode ^
      totalCount.hashCode ^
      message.hashCode ^
      broadcastFailureKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecuteProposalResult &&
          runtimeType == other.runtimeType &&
          txids == other.txids &&
          status == other.status &&
          broadcastedCount == other.broadcastedCount &&
          totalCount == other.totalCount &&
          message == other.message &&
          broadcastFailureKind == other.broadcastFailureKind;
}

class ExtractAndBroadcastPcztResult {
  final String txid;
  final String status;
  final String? message;

  const ExtractAndBroadcastPcztResult({
    required this.txid,
    required this.status,
    this.message,
  });

  @override
  int get hashCode => txid.hashCode ^ status.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractAndBroadcastPcztResult &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          status == other.status &&
          message == other.message;
}

class IronwoodMigrationResult {
  final String txids;
  final String status;
  final int broadcastedCount;
  final int totalCount;
  final String? message;
  final BigInt feeZatoshi;
  final BigInt migratedZatoshi;

  const IronwoodMigrationResult({
    required this.txids,
    required this.status,
    required this.broadcastedCount,
    required this.totalCount,
    this.message,
    required this.feeZatoshi,
    required this.migratedZatoshi,
  });

  @override
  int get hashCode =>
      txids.hashCode ^
      status.hashCode ^
      broadcastedCount.hashCode ^
      totalCount.hashCode ^
      message.hashCode ^
      feeZatoshi.hashCode ^
      migratedZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IronwoodMigrationResult &&
          runtimeType == other.runtimeType &&
          txids == other.txids &&
          status == other.status &&
          broadcastedCount == other.broadcastedCount &&
          totalCount == other.totalCount &&
          message == other.message &&
          feeZatoshi == other.feeZatoshi &&
          migratedZatoshi == other.migratedZatoshi;
}

/// One signer-redacted PCZT prepared for Keystone's signatures-only batch
/// protocol, plus the number of Orchard/Ironwood signatures expected back.
class KeystoneBatchPczt {
  final Uint8List redactedPczt;
  final int expectedSignatureCount;

  const KeystoneBatchPczt({
    required this.redactedPczt,
    required this.expectedSignatureCount,
  });

  @override
  int get hashCode => redactedPczt.hashCode ^ expectedSignatureCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeystoneBatchPczt &&
          runtimeType == other.runtimeType &&
          redactedPczt == other.redactedPczt &&
          expectedSignatureCount == other.expectedSignatureCount;
}

class KeystoneMigrationMessage {
  final String id;
  final Uint8List redactedPczt;

  /// Number of spend authorization signatures expected from Keystone.
  final int expectedSignatureCount;

  const KeystoneMigrationMessage({
    required this.id,
    required this.redactedPczt,
    required this.expectedSignatureCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ redactedPczt.hashCode ^ expectedSignatureCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeystoneMigrationMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          redactedPczt == other.redactedPczt &&
          expectedSignatureCount == other.expectedSignatureCount;
}

class KeystoneMigrationProofStatus {
  final int readyCount;
  final int totalCount;
  final bool isReady;
  final bool isFailed;
  final String? message;

  const KeystoneMigrationProofStatus({
    required this.readyCount,
    required this.totalCount,
    required this.isReady,
    required this.isFailed,
    this.message,
  });

  @override
  int get hashCode =>
      readyCount.hashCode ^
      totalCount.hashCode ^
      isReady.hashCode ^
      isFailed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeystoneMigrationProofStatus &&
          runtimeType == other.runtimeType &&
          readyCount == other.readyCount &&
          totalCount == other.totalCount &&
          isReady == other.isReady &&
          isFailed == other.isFailed &&
          message == other.message;
}

class KeystoneMigrationSigningRequest {
  final String requestId;
  final List<KeystoneMigrationMessage> messages;
  final int signingBatchLimit;

  const KeystoneMigrationSigningRequest({
    required this.requestId,
    required this.messages,
    required this.signingBatchLimit,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^ messages.hashCode ^ signingBatchLimit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeystoneMigrationSigningRequest &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          messages == other.messages &&
          signingBatchLimit == other.signingBatchLimit;
}

/// One signed message in the compact "signatures-only" Keystone response: the
/// produced spend-authorization signatures for request message `id`. Replaces
/// the prior full-signed-PCZT payload. Dart builds this from the decoded
/// `KeystoneSigResult` and feeds it into the migration completion calls.
class KeystoneSignedMigrationMessage {
  final String id;
  final List<KeystoneActionSig> sigs;

  const KeystoneSignedMigrationMessage({required this.id, required this.sigs});

  @override
  int get hashCode => id.hashCode ^ sigs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeystoneSignedMigrationMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sigs == other.sigs;
}

/// Local DB progress only; no address discovery or network requests.
class LedgerShieldingProgress {
  final int inputCount;
  final int inputLimit;
  final bool belowThreshold;

  const LedgerShieldingProgress({
    required this.inputCount,
    required this.inputLimit,
    required this.belowThreshold,
  });

  @override
  int get hashCode =>
      inputCount.hashCode ^ inputLimit.hashCode ^ belowThreshold.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LedgerShieldingProgress &&
          runtimeType == other.runtimeType &&
          inputCount == other.inputCount &&
          inputLimit == other.inputLimit &&
          belowThreshold == other.belowThreshold;
}

class MigrationOutboxBatch {
  final String runId;
  final int timingMeanBlocks;
  final int timingMaxBlocks;
  final int? nextProofHeight;
  final List<MigrationOutboxItem> items;

  const MigrationOutboxBatch({
    required this.runId,
    required this.timingMeanBlocks,
    required this.timingMaxBlocks,
    this.nextProofHeight,
    required this.items,
  });

  @override
  int get hashCode =>
      runId.hashCode ^
      timingMeanBlocks.hashCode ^
      timingMaxBlocks.hashCode ^
      nextProofHeight.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationOutboxBatch &&
          runtimeType == other.runtimeType &&
          runId == other.runId &&
          timingMeanBlocks == other.timingMeanBlocks &&
          timingMaxBlocks == other.timingMaxBlocks &&
          nextProofHeight == other.nextProofHeight &&
          items == other.items;
}

class MigrationOutboxItem {
  /// Stable Swift outbox item identifier. This is the finalized txid.
  final String itemId;
  final int partIndex;
  final String txidHex;
  final Uint8List rawTransaction;
  final int anchorBoundaryHeight;
  final int scheduledHeight;
  final int scheduleStartHeight;
  final int expiryHeight;

  const MigrationOutboxItem({
    required this.itemId,
    required this.partIndex,
    required this.txidHex,
    required this.rawTransaction,
    required this.anchorBoundaryHeight,
    required this.scheduledHeight,
    required this.scheduleStartHeight,
    required this.expiryHeight,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      partIndex.hashCode ^
      txidHex.hashCode ^
      rawTransaction.hashCode ^
      anchorBoundaryHeight.hashCode ^
      scheduledHeight.hashCode ^
      scheduleStartHeight.hashCode ^
      expiryHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationOutboxItem &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          partIndex == other.partIndex &&
          txidHex == other.txidHex &&
          rawTransaction == other.rawTransaction &&
          anchorBoundaryHeight == other.anchorBoundaryHeight &&
          scheduledHeight == other.scheduledHeight &&
          scheduleStartHeight == other.scheduleStartHeight &&
          expiryHeight == other.expiryHeight;
}

class MigrationOutboxScheduleUpdate {
  final String itemId;
  final int scheduledHeight;
  final int scheduleStartHeight;

  const MigrationOutboxScheduleUpdate({
    required this.itemId,
    required this.scheduledHeight,
    required this.scheduleStartHeight,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^ scheduledHeight.hashCode ^ scheduleStartHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationOutboxScheduleUpdate &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          scheduledHeight == other.scheduledHeight &&
          scheduleStartHeight == other.scheduleStartHeight;
}

enum MigrationPartState {
  preparing,
  scheduled,
  migrating,
  confirming,
  completed,
  needsInput,
}

class MigrationPartStatus {
  final int partIndex;
  final int? scheduleOrder;
  final BigInt valueZatoshi;
  final MigrationPartState state;
  final String? txidHex;
  final int? scheduleStartHeight;

  /// Backward-compatible alias for `effective_scheduled_height`.
  final int? scheduledHeight;

  /// First absolute block height assigned to this logical migration part.
  final int? originalScheduledHeight;

  /// Current absolute block height after any catch-up rescheduling.
  final int? effectiveScheduledHeight;

  /// Actual block containing the transaction, once observed in the local chain.
  final int? minedHeight;
  final int confirmationCount;
  final int confirmationTarget;

  const MigrationPartStatus({
    required this.partIndex,
    this.scheduleOrder,
    required this.valueZatoshi,
    required this.state,
    this.txidHex,
    this.scheduleStartHeight,
    this.scheduledHeight,
    this.originalScheduledHeight,
    this.effectiveScheduledHeight,
    this.minedHeight,
    required this.confirmationCount,
    required this.confirmationTarget,
  });

  @override
  int get hashCode =>
      partIndex.hashCode ^
      scheduleOrder.hashCode ^
      valueZatoshi.hashCode ^
      state.hashCode ^
      txidHex.hashCode ^
      scheduleStartHeight.hashCode ^
      scheduledHeight.hashCode ^
      originalScheduledHeight.hashCode ^
      effectiveScheduledHeight.hashCode ^
      minedHeight.hashCode ^
      confirmationCount.hashCode ^
      confirmationTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationPartStatus &&
          runtimeType == other.runtimeType &&
          partIndex == other.partIndex &&
          scheduleOrder == other.scheduleOrder &&
          valueZatoshi == other.valueZatoshi &&
          state == other.state &&
          txidHex == other.txidHex &&
          scheduleStartHeight == other.scheduleStartHeight &&
          scheduledHeight == other.scheduledHeight &&
          originalScheduledHeight == other.originalScheduledHeight &&
          effectiveScheduledHeight == other.effectiveScheduledHeight &&
          minedHeight == other.minedHeight &&
          confirmationCount == other.confirmationCount &&
          confirmationTarget == other.confirmationTarget;
}

enum MigrationPreparationOutputKind { migration, change, continuation }

class MigrationPreparationOutputStatus {
  /// Actual Orchard note value, including any fee reserved for its migration.
  final BigInt valueZatoshi;

  /// Canonical ZIP 318 value that will reach Ironwood for migration outputs.
  final BigInt? targetValueZatoshi;
  final MigrationPreparationOutputKind kind;
  final int? nextRound;

  const MigrationPreparationOutputStatus({
    required this.valueZatoshi,
    this.targetValueZatoshi,
    required this.kind,
    this.nextRound,
  });

  @override
  int get hashCode =>
      valueZatoshi.hashCode ^
      targetValueZatoshi.hashCode ^
      kind.hashCode ^
      nextRound.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationPreparationOutputStatus &&
          runtimeType == other.runtimeType &&
          valueZatoshi == other.valueZatoshi &&
          targetValueZatoshi == other.targetValueZatoshi &&
          kind == other.kind &&
          nextRound == other.nextRound;
}

enum MigrationPreparationTransactionState {
  awaitingInputs,
  scheduled,
  broadcasted,
  confirming,
  completed,
}

class MigrationPreparationTransactionStatus {
  final int stageIndex;
  final BigInt approximateValueZatoshi;
  final int round;
  final BigInt feeZatoshi;
  final int plannedHeight;
  final int projectedHeight;
  final int projectedCompletionHeight;
  final List<MigrationPreparationOutputStatus> outputs;
  final MigrationPreparationTransactionState state;
  final int? scheduledHeight;
  final int? minedHeight;
  final int confirmationCount;
  final int confirmationTarget;

  const MigrationPreparationTransactionStatus({
    required this.stageIndex,
    required this.approximateValueZatoshi,
    required this.round,
    required this.feeZatoshi,
    required this.plannedHeight,
    required this.projectedHeight,
    required this.projectedCompletionHeight,
    required this.outputs,
    required this.state,
    this.scheduledHeight,
    this.minedHeight,
    required this.confirmationCount,
    required this.confirmationTarget,
  });

  @override
  int get hashCode =>
      stageIndex.hashCode ^
      approximateValueZatoshi.hashCode ^
      round.hashCode ^
      feeZatoshi.hashCode ^
      plannedHeight.hashCode ^
      projectedHeight.hashCode ^
      projectedCompletionHeight.hashCode ^
      outputs.hashCode ^
      state.hashCode ^
      scheduledHeight.hashCode ^
      minedHeight.hashCode ^
      confirmationCount.hashCode ^
      confirmationTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationPreparationTransactionStatus &&
          runtimeType == other.runtimeType &&
          stageIndex == other.stageIndex &&
          approximateValueZatoshi == other.approximateValueZatoshi &&
          round == other.round &&
          feeZatoshi == other.feeZatoshi &&
          plannedHeight == other.plannedHeight &&
          projectedHeight == other.projectedHeight &&
          projectedCompletionHeight == other.projectedCompletionHeight &&
          outputs == other.outputs &&
          state == other.state &&
          scheduledHeight == other.scheduledHeight &&
          minedHeight == other.minedHeight &&
          confirmationCount == other.confirmationCount &&
          confirmationTarget == other.confirmationTarget;
}

class MigrationScheduledBroadcast {
  final String txidHex;
  final BigInt valueZatoshi;
  final PlatformInt64 scheduledAtMs;
  final int? scheduleStartHeight;
  final int scheduledHeight;
  final String status;

  const MigrationScheduledBroadcast({
    required this.txidHex,
    required this.valueZatoshi,
    required this.scheduledAtMs,
    this.scheduleStartHeight,
    required this.scheduledHeight,
    required this.status,
  });

  @override
  int get hashCode =>
      txidHex.hashCode ^
      valueZatoshi.hashCode ^
      scheduledAtMs.hashCode ^
      scheduleStartHeight.hashCode ^
      scheduledHeight.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationScheduledBroadcast &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          valueZatoshi == other.valueZatoshi &&
          scheduledAtMs == other.scheduledAtMs &&
          scheduleStartHeight == other.scheduleStartHeight &&
          scheduledHeight == other.scheduledHeight &&
          status == other.status;
}

class MigrationScheduledTransfer {
  final int partIndex;
  final BigInt valueZatoshi;
  final int blockOffset;

  const MigrationScheduledTransfer({
    required this.partIndex,
    required this.valueZatoshi,
    required this.blockOffset,
  });

  @override
  int get hashCode =>
      partIndex.hashCode ^ valueZatoshi.hashCode ^ blockOffset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationScheduledTransfer &&
          runtimeType == other.runtimeType &&
          partIndex == other.partIndex &&
          valueZatoshi == other.valueZatoshi &&
          blockOffset == other.blockOffset;
}

class MigrationStatus {
  final String phase;
  final String? activeRunId;
  final Uint64List targetValuesZatoshi;
  final int preparedNoteCount;

  /// Minimum confirmation depth across the active denomination split
  /// frontier, including parallel split roots.
  final int denominationConfirmationCount;
  final int denominationConfirmationTarget;

  /// Denomination split transactions that have reached the wallet's trusted
  /// confirmation depth, rather than transactions that are merely mined.
  final int denominationSplitCompletedCount;

  /// Total denomination split transactions planned for this migration run.
  final int denominationSplitTotalCount;
  final int pendingTxCount;
  final int broadcastedTxCount;
  final int confirmedTxCount;
  final int totalCount;
  final int signedChildPcztCount;
  final int pendingSplitStageCount;
  final String? message;
  final bool canAbandon;
  final int signingBatchLimit;
  final int scheduleMeanDelayBlocks;
  final int scheduleMaxDelayBlocks;
  final int? preparationMeanDelayBlocks;
  final int? nextActionHeight;

  /// Earliest chain height at which the next ZIP 318 proof window should be
  /// retried. Kept separate from `next_action_height`, which may instead
  /// describe an earlier scheduled broadcast.
  final int? nextProofWindowHeight;

  /// Migration parts expected to use that proof window.
  final Uint32List? nextProofWindowPartIndices;

  /// Exact foreground proof preflight. `None` means no signed proof action
  /// is currently applicable; `Some(false)` keeps a height-due action gated
  /// until its anchor checkpoint and witness are actually available.
  final bool? proofReady;
  final int? estimatedCompletionHeight;
  final int? nextActionPartIndex;
  final Uint32List? currentSigningPartIndices;
  final List<MigrationScheduledBroadcast> scheduledBroadcasts;
  final List<MigrationPreparationTransactionStatus>? preparationTransactions;
  final List<MigrationPartStatus> parts;

  const MigrationStatus({
    required this.phase,
    this.activeRunId,
    required this.targetValuesZatoshi,
    required this.preparedNoteCount,
    required this.denominationConfirmationCount,
    required this.denominationConfirmationTarget,
    required this.denominationSplitCompletedCount,
    required this.denominationSplitTotalCount,
    required this.pendingTxCount,
    required this.broadcastedTxCount,
    required this.confirmedTxCount,
    required this.totalCount,
    required this.signedChildPcztCount,
    required this.pendingSplitStageCount,
    this.message,
    required this.canAbandon,
    required this.signingBatchLimit,
    required this.scheduleMeanDelayBlocks,
    required this.scheduleMaxDelayBlocks,
    this.preparationMeanDelayBlocks,
    this.nextActionHeight,
    this.nextProofWindowHeight,
    this.nextProofWindowPartIndices,
    this.proofReady,
    this.estimatedCompletionHeight,
    this.nextActionPartIndex,
    this.currentSigningPartIndices,
    required this.scheduledBroadcasts,
    this.preparationTransactions,
    required this.parts,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      activeRunId.hashCode ^
      targetValuesZatoshi.hashCode ^
      preparedNoteCount.hashCode ^
      denominationConfirmationCount.hashCode ^
      denominationConfirmationTarget.hashCode ^
      denominationSplitCompletedCount.hashCode ^
      denominationSplitTotalCount.hashCode ^
      pendingTxCount.hashCode ^
      broadcastedTxCount.hashCode ^
      confirmedTxCount.hashCode ^
      totalCount.hashCode ^
      signedChildPcztCount.hashCode ^
      pendingSplitStageCount.hashCode ^
      message.hashCode ^
      canAbandon.hashCode ^
      signingBatchLimit.hashCode ^
      scheduleMeanDelayBlocks.hashCode ^
      scheduleMaxDelayBlocks.hashCode ^
      preparationMeanDelayBlocks.hashCode ^
      nextActionHeight.hashCode ^
      nextProofWindowHeight.hashCode ^
      nextProofWindowPartIndices.hashCode ^
      proofReady.hashCode ^
      estimatedCompletionHeight.hashCode ^
      nextActionPartIndex.hashCode ^
      currentSigningPartIndices.hashCode ^
      scheduledBroadcasts.hashCode ^
      preparationTransactions.hashCode ^
      parts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationStatus &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          activeRunId == other.activeRunId &&
          targetValuesZatoshi == other.targetValuesZatoshi &&
          preparedNoteCount == other.preparedNoteCount &&
          denominationConfirmationCount ==
              other.denominationConfirmationCount &&
          denominationConfirmationTarget ==
              other.denominationConfirmationTarget &&
          denominationSplitCompletedCount ==
              other.denominationSplitCompletedCount &&
          denominationSplitTotalCount == other.denominationSplitTotalCount &&
          pendingTxCount == other.pendingTxCount &&
          broadcastedTxCount == other.broadcastedTxCount &&
          confirmedTxCount == other.confirmedTxCount &&
          totalCount == other.totalCount &&
          signedChildPcztCount == other.signedChildPcztCount &&
          pendingSplitStageCount == other.pendingSplitStageCount &&
          message == other.message &&
          canAbandon == other.canAbandon &&
          signingBatchLimit == other.signingBatchLimit &&
          scheduleMeanDelayBlocks == other.scheduleMeanDelayBlocks &&
          scheduleMaxDelayBlocks == other.scheduleMaxDelayBlocks &&
          preparationMeanDelayBlocks == other.preparationMeanDelayBlocks &&
          nextActionHeight == other.nextActionHeight &&
          nextProofWindowHeight == other.nextProofWindowHeight &&
          nextProofWindowPartIndices == other.nextProofWindowPartIndices &&
          proofReady == other.proofReady &&
          estimatedCompletionHeight == other.estimatedCompletionHeight &&
          nextActionPartIndex == other.nextActionPartIndex &&
          currentSigningPartIndices == other.currentSigningPartIndices &&
          scheduledBroadcasts == other.scheduledBroadcasts &&
          preparationTransactions == other.preparationTransactions &&
          parts == other.parts;
}

/// One account's slot in a batched migration-status read.
///
/// `status` and `error` are mutually exclusive: a per-account failure is
/// reported here so it cannot fail the whole batch, matching the
/// per-account error handling the caller already does.
class MigrationStatusEntry {
  final String accountUuid;
  final MigrationStatus? status;
  final String? error;

  const MigrationStatusEntry({
    required this.accountUuid,
    this.status,
    this.error,
  });

  @override
  int get hashCode => accountUuid.hashCode ^ status.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationStatusEntry &&
          runtimeType == other.runtimeType &&
          accountUuid == other.accountUuid &&
          status == other.status &&
          error == other.error;
}

class OrchardMigrationImmediatePlan {
  final BigInt totalInputZatoshi;
  final BigInt feeZatoshi;
  final BigInt migratedZatoshi;
  final int inputNoteCount;

  const OrchardMigrationImmediatePlan({
    required this.totalInputZatoshi,
    required this.feeZatoshi,
    required this.migratedZatoshi,
    required this.inputNoteCount,
  });

  @override
  int get hashCode =>
      totalInputZatoshi.hashCode ^
      feeZatoshi.hashCode ^
      migratedZatoshi.hashCode ^
      inputNoteCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrchardMigrationImmediatePlan &&
          runtimeType == other.runtimeType &&
          totalInputZatoshi == other.totalInputZatoshi &&
          feeZatoshi == other.feeZatoshi &&
          migratedZatoshi == other.migratedZatoshi &&
          inputNoteCount == other.inputNoteCount;
}

class OrchardMigrationPrivatePlan {
  final Uint64List targetValuesZatoshi;
  final BigInt totalInputZatoshi;
  final BigInt totalMigratableZatoshi;
  final BigInt? orchardChangeZatoshi;
  final BigInt denominationSplitFeeZatoshi;
  final BigInt migrationFeeZatoshi;
  final BigInt estimatedTotalFeeZatoshi;
  final int plannedBatchCount;
  final int denominationSplitStageCount;
  final int denominationSplitLayerCount;
  final int signingBatchLimit;
  final int scheduleMeanDelayBlocks;
  final int scheduleMaxDelayBlocks;

  /// Estimated preparation spacing plus the remaining blocks until every
  /// funding note can use a valid migration anchor.
  final int proofReadinessDelayBlocks;

  /// Estimated absolute height at which the projected final prepared note
  /// can first use a valid migration anchor.
  final int? estimatedProofReadyHeight;
  final List<MigrationScheduledTransfer> scheduledTransfers;

  const OrchardMigrationPrivatePlan({
    required this.targetValuesZatoshi,
    required this.totalInputZatoshi,
    required this.totalMigratableZatoshi,
    this.orchardChangeZatoshi,
    required this.denominationSplitFeeZatoshi,
    required this.migrationFeeZatoshi,
    required this.estimatedTotalFeeZatoshi,
    required this.plannedBatchCount,
    required this.denominationSplitStageCount,
    required this.denominationSplitLayerCount,
    required this.signingBatchLimit,
    required this.scheduleMeanDelayBlocks,
    required this.scheduleMaxDelayBlocks,
    required this.proofReadinessDelayBlocks,
    this.estimatedProofReadyHeight,
    required this.scheduledTransfers,
  });

  @override
  int get hashCode =>
      targetValuesZatoshi.hashCode ^
      totalInputZatoshi.hashCode ^
      totalMigratableZatoshi.hashCode ^
      orchardChangeZatoshi.hashCode ^
      denominationSplitFeeZatoshi.hashCode ^
      migrationFeeZatoshi.hashCode ^
      estimatedTotalFeeZatoshi.hashCode ^
      plannedBatchCount.hashCode ^
      denominationSplitStageCount.hashCode ^
      denominationSplitLayerCount.hashCode ^
      signingBatchLimit.hashCode ^
      scheduleMeanDelayBlocks.hashCode ^
      scheduleMaxDelayBlocks.hashCode ^
      proofReadinessDelayBlocks.hashCode ^
      estimatedProofReadyHeight.hashCode ^
      scheduledTransfers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrchardMigrationPrivatePlan &&
          runtimeType == other.runtimeType &&
          targetValuesZatoshi == other.targetValuesZatoshi &&
          totalInputZatoshi == other.totalInputZatoshi &&
          totalMigratableZatoshi == other.totalMigratableZatoshi &&
          orchardChangeZatoshi == other.orchardChangeZatoshi &&
          denominationSplitFeeZatoshi == other.denominationSplitFeeZatoshi &&
          migrationFeeZatoshi == other.migrationFeeZatoshi &&
          estimatedTotalFeeZatoshi == other.estimatedTotalFeeZatoshi &&
          plannedBatchCount == other.plannedBatchCount &&
          denominationSplitStageCount == other.denominationSplitStageCount &&
          denominationSplitLayerCount == other.denominationSplitLayerCount &&
          signingBatchLimit == other.signingBatchLimit &&
          scheduleMeanDelayBlocks == other.scheduleMeanDelayBlocks &&
          scheduleMaxDelayBlocks == other.scheduleMaxDelayBlocks &&
          proofReadinessDelayBlocks == other.proofReadinessDelayBlocks &&
          estimatedProofReadyHeight == other.estimatedProofReadyHeight &&
          scheduledTransfers == other.scheduledTransfers;
}

/// Positive, scanned evidence for a Gift Card's shielded inputs. This reads
/// only the claim database; it never submits or retransmits a transaction.
class PaymentLinkSpendEvidence {
  final bool allFundsSpentElsewhere;
  final List<String> conflictedTxids;
  final List<String> localClaimTxids;
  final BigInt verifiedHeight;

  const PaymentLinkSpendEvidence({
    required this.allFundsSpentElsewhere,
    required this.conflictedTxids,
    required this.localClaimTxids,
    required this.verifiedHeight,
  });

  @override
  int get hashCode =>
      allFundsSpentElsewhere.hashCode ^
      conflictedTxids.hashCode ^
      localClaimTxids.hashCode ^
      verifiedHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PaymentLinkSpendEvidence &&
          runtimeType == other.runtimeType &&
          allFundsSpentElsewhere == other.allFundsSpentElsewhere &&
          conflictedTxids == other.conflictedTxids &&
          localClaimTxids == other.localClaimTxids &&
          verifiedHeight == other.verifiedHeight;
}

class ProposalResult {
  final BigInt proposalId;
  final bool needsSaplingParams;
  final BigInt feeZatoshi;

  const ProposalResult({
    required this.proposalId,
    required this.needsSaplingParams,
    required this.feeZatoshi,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^ needsSaplingParams.hashCode ^ feeZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalResult &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          needsSaplingParams == other.needsSaplingParams &&
          feeZatoshi == other.feeZatoshi;
}

class ScanRangeInfo {
  final BigInt start;
  final BigInt end;
  final int priority;

  const ScanRangeInfo({
    required this.start,
    required this.end,
    required this.priority,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanRangeInfo &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          priority == other.priority;
}

class ScanResult {
  final BigInt blocksScanned;

  const ScanResult({required this.blocksScanned});

  @override
  int get hashCode => blocksScanned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          blocksScanned == other.blocksScanned;
}

class SendMaxEstimateResult {
  final BigInt amountZatoshi;
  final BigInt feeZatoshi;
  final bool needsSaplingParams;

  const SendMaxEstimateResult({
    required this.amountZatoshi,
    required this.feeZatoshi,
    required this.needsSaplingParams,
  });

  @override
  int get hashCode =>
      amountZatoshi.hashCode ^
      feeZatoshi.hashCode ^
      needsSaplingParams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendMaxEstimateResult &&
          runtimeType == other.runtimeType &&
          amountZatoshi == other.amountZatoshi &&
          feeZatoshi == other.feeZatoshi &&
          needsSaplingParams == other.needsSaplingParams;
}

class ShieldTransparentPcztResult {
  final Uint8List pcztBytes;
  final BigInt feeZatoshi;
  final BigInt shieldedZatoshi;
  final bool needsSaplingParams;

  const ShieldTransparentPcztResult({
    required this.pcztBytes,
    required this.feeZatoshi,
    required this.shieldedZatoshi,
    required this.needsSaplingParams,
  });

  @override
  int get hashCode =>
      pcztBytes.hashCode ^
      feeZatoshi.hashCode ^
      shieldedZatoshi.hashCode ^
      needsSaplingParams.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShieldTransparentPcztResult &&
          runtimeType == other.runtimeType &&
          pcztBytes == other.pcztBytes &&
          feeZatoshi == other.feeZatoshi &&
          shieldedZatoshi == other.shieldedZatoshi &&
          needsSaplingParams == other.needsSaplingParams;
}

class ShieldTransparentResult {
  final String txids;
  final String status;
  final int broadcastedCount;
  final int totalCount;
  final String? message;
  final BigInt feeZatoshi;
  final BigInt shieldedZatoshi;

  const ShieldTransparentResult({
    required this.txids,
    required this.status,
    required this.broadcastedCount,
    required this.totalCount,
    this.message,
    required this.feeZatoshi,
    required this.shieldedZatoshi,
  });

  @override
  int get hashCode =>
      txids.hashCode ^
      status.hashCode ^
      broadcastedCount.hashCode ^
      totalCount.hashCode ^
      message.hashCode ^
      feeZatoshi.hashCode ^
      shieldedZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShieldTransparentResult &&
          runtimeType == other.runtimeType &&
          txids == other.txids &&
          status == other.status &&
          broadcastedCount == other.broadcastedCount &&
          totalCount == other.totalCount &&
          message == other.message &&
          feeZatoshi == other.feeZatoshi &&
          shieldedZatoshi == other.shieldedZatoshi;
}

class ShieldTransparentStatus {
  final bool canShield;
  final BigInt feeZatoshi;
  final BigInt shieldedZatoshi;
  final String reason;

  const ShieldTransparentStatus({
    required this.canShield,
    required this.feeZatoshi,
    required this.shieldedZatoshi,
    required this.reason,
  });

  @override
  int get hashCode =>
      canShield.hashCode ^
      feeZatoshi.hashCode ^
      shieldedZatoshi.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShieldTransparentStatus &&
          runtimeType == other.runtimeType &&
          canShield == other.canShield &&
          feeZatoshi == other.feeZatoshi &&
          shieldedZatoshi == other.shieldedZatoshi &&
          reason == other.reason;
}

class StoreAndBroadcastPcztsResult {
  final String txids;
  final String status;
  final int broadcastedCount;
  final int totalCount;
  final String? message;

  const StoreAndBroadcastPcztsResult({
    required this.txids,
    required this.status,
    required this.broadcastedCount,
    required this.totalCount,
    this.message,
  });

  @override
  int get hashCode =>
      txids.hashCode ^
      status.hashCode ^
      broadcastedCount.hashCode ^
      totalCount.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoreAndBroadcastPcztsResult &&
          runtimeType == other.runtimeType &&
          txids == other.txids &&
          status == other.status &&
          broadcastedCount == other.broadcastedCount &&
          totalCount == other.totalCount &&
          message == other.message;
}

class SubtreeIndices {
  final BigInt nextSapling;
  final BigInt nextOrchard;
  final BigInt nextIronwood;

  const SubtreeIndices({
    required this.nextSapling,
    required this.nextOrchard,
    required this.nextIronwood,
  });

  @override
  int get hashCode =>
      nextSapling.hashCode ^ nextOrchard.hashCode ^ nextIronwood.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtreeIndices &&
          runtimeType == other.runtimeType &&
          nextSapling == other.nextSapling &&
          nextOrchard == other.nextOrchard &&
          nextIronwood == other.nextIronwood;
}

class SubtreeRoot {
  final BigInt completingBlockHeight;
  final Uint8List rootHash;

  const SubtreeRoot({
    required this.completingBlockHeight,
    required this.rootHash,
  });

  @override
  int get hashCode => completingBlockHeight.hashCode ^ rootHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtreeRoot &&
          runtimeType == other.runtimeType &&
          completingBlockHeight == other.completingBlockHeight &&
          rootHash == other.rootHash;
}

class SyncProgress {
  final BigInt scannedHeight;
  final BigInt chainTipHeight;
  final bool isSyncing;
  final bool isComplete;

  const SyncProgress({
    required this.scannedHeight,
    required this.chainTipHeight,
    required this.isSyncing,
    required this.isComplete,
  });

  @override
  int get hashCode =>
      scannedHeight.hashCode ^
      chainTipHeight.hashCode ^
      isSyncing.hashCode ^
      isComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncProgress &&
          runtimeType == other.runtimeType &&
          scannedHeight == other.scannedHeight &&
          chainTipHeight == other.chainTipHeight &&
          isSyncing == other.isSyncing &&
          isComplete == other.isComplete;
}

class TexPcztPairResult {
  final List<Uint8List> pczts;
  final List<Uint8List> signerPczts;

  const TexPcztPairResult({required this.pczts, required this.signerPczts});

  @override
  int get hashCode => pczts.hashCode ^ signerPczts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TexPcztPairResult &&
          runtimeType == other.runtimeType &&
          pczts == other.pczts &&
          signerPczts == other.signerPczts;
}

class TransactionDetail {
  final String txidHex;
  final String txKind;
  final String? primaryAddress;
  final String? sourceAddress;
  final String? sourcePool;
  final String? memo;
  final List<TransactionDetailOutput> outputs;

  /// Whether `outputs` holds every recipient and memo.
  final bool detailsComplete;

  /// See [`TransactionInfo::provisional`].
  final bool provisional;

  const TransactionDetail({
    required this.txidHex,
    required this.txKind,
    this.primaryAddress,
    this.sourceAddress,
    this.sourcePool,
    this.memo,
    required this.outputs,
    required this.detailsComplete,
    required this.provisional,
  });

  @override
  int get hashCode =>
      txidHex.hashCode ^
      txKind.hashCode ^
      primaryAddress.hashCode ^
      sourceAddress.hashCode ^
      sourcePool.hashCode ^
      memo.hashCode ^
      outputs.hashCode ^
      detailsComplete.hashCode ^
      provisional.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionDetail &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          txKind == other.txKind &&
          primaryAddress == other.primaryAddress &&
          sourceAddress == other.sourceAddress &&
          sourcePool == other.sourcePool &&
          memo == other.memo &&
          outputs == other.outputs &&
          detailsComplete == other.detailsComplete &&
          provisional == other.provisional;
}

class TransactionDetailOutput {
  final String? address;
  final BigInt amountZatoshi;
  final String pool;
  final bool usesOrchardReceiver;

  const TransactionDetailOutput({
    this.address,
    required this.amountZatoshi,
    required this.pool,
    required this.usesOrchardReceiver,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      amountZatoshi.hashCode ^
      pool.hashCode ^
      usesOrchardReceiver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionDetailOutput &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amountZatoshi == other.amountZatoshi &&
          pool == other.pool &&
          usesOrchardReceiver == other.usesOrchardReceiver;
}

/// The fee of a transaction as it concerns the account.
enum TransactionFeeState {
  /// The account paid the recorded `fee`.
  known,

  /// The account spent funds, or may have, but the fee is not recorded.
  /// Show it as unknown, never as zero.
  unknown,

  /// The account spent nothing, so it paid no fee.
  notApplicable,
}

class TransactionInfo {
  final String txidHex;
  final BigInt minedHeight;
  final bool expiredUnmined;
  final PlatformInt64 accountBalanceDelta;

  /// The recorded fee. Zero unless `fee_state` is `Known`.
  final BigInt fee;
  final TransactionFeeState feeState;
  final BigInt blockTime;
  final bool isTransparent;
  final String txKind;
  final BigInt displayAmount;
  final String displayPool;
  final BigInt createdTime;

  /// Whether the recipients, payment amounts, and memos are known.
  final bool detailsComplete;

  /// Whether later discovery or enhancement can still change this entry.
  /// A provisional debit is a net amount, not a payment amount.
  final bool provisional;

  const TransactionInfo({
    required this.txidHex,
    required this.minedHeight,
    required this.expiredUnmined,
    required this.accountBalanceDelta,
    required this.fee,
    required this.feeState,
    required this.blockTime,
    required this.isTransparent,
    required this.txKind,
    required this.displayAmount,
    required this.displayPool,
    required this.createdTime,
    required this.detailsComplete,
    required this.provisional,
  });

  @override
  int get hashCode =>
      txidHex.hashCode ^
      minedHeight.hashCode ^
      expiredUnmined.hashCode ^
      accountBalanceDelta.hashCode ^
      fee.hashCode ^
      feeState.hashCode ^
      blockTime.hashCode ^
      isTransparent.hashCode ^
      txKind.hashCode ^
      displayAmount.hashCode ^
      displayPool.hashCode ^
      createdTime.hashCode ^
      detailsComplete.hashCode ^
      provisional.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionInfo &&
          runtimeType == other.runtimeType &&
          txidHex == other.txidHex &&
          minedHeight == other.minedHeight &&
          expiredUnmined == other.expiredUnmined &&
          accountBalanceDelta == other.accountBalanceDelta &&
          fee == other.fee &&
          feeState == other.feeState &&
          blockTime == other.blockTime &&
          isTransparent == other.isTransparent &&
          txKind == other.txKind &&
          displayAmount == other.displayAmount &&
          displayPool == other.displayPool &&
          createdTime == other.createdTime &&
          detailsComplete == other.detailsComplete &&
          provisional == other.provisional;
}

/// What the transparent fields of a [`WalletBalance`] represent.
enum TransparentBalanceAuthority {
  /// Current authorized amounts.
  current,

  /// No current authority: the transparent fields are zero because nothing
  /// is spendable, and `transparent_last_known` holds the prior amount.
  lastKnown,

  /// No current authority and no prior amount. Show as unavailable, never 0.
  unavailable,
}

class TxDataRequest {
  final String requestType;
  final String? txid;
  final String? address;
  final BigInt? blockRangeStart;
  final BigInt? blockRangeEnd;

  const TxDataRequest({
    required this.requestType,
    this.txid,
    this.address,
    this.blockRangeStart,
    this.blockRangeEnd,
  });

  @override
  int get hashCode =>
      requestType.hashCode ^
      txid.hashCode ^
      address.hashCode ^
      blockRangeStart.hashCode ^
      blockRangeEnd.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxDataRequest &&
          runtimeType == other.runtimeType &&
          requestType == other.requestType &&
          txid == other.txid &&
          address == other.address &&
          blockRangeStart == other.blockRangeStart &&
          blockRangeEnd == other.blockRangeEnd;
}

class WalletBalance {
  final WalletBalanceAvailability availability;
  final TransparentBalanceAuthority transparentAuthority;

  /// Informational prior transparent total, present only with
  /// `TransparentBalanceAuthority::LastKnown`. It never authorizes a spend.
  final BigInt? transparentLastKnown;
  final BigInt transparent;
  final BigInt sapling;
  final BigInt orchard;
  final BigInt ironwood;
  final BigInt transparentLocked;
  final BigInt saplingLocked;
  final BigInt orchardLocked;
  final BigInt ironwoodLocked;
  final BigInt transparentPending;
  final BigInt saplingPending;
  final BigInt orchardPending;
  final BigInt ironwoodPending;

  /// Wallet-created change that has not reached the trusted confirmation depth.
  final BigInt changePendingConfirmation;

  /// Other received value awaiting confirmations or additional witness scanning.
  final BigInt valuePendingSpendability;

  /// Notes at or below the ZIP-317 marginal fee, excluded from normal spendability.
  final BigInt uneconomicValue;

  /// Sum of spendable shielded balances. Use this for "available to send".
  final BigInt spendable;

  /// Sum of owner-locked balances across all pools.
  final BigInt locked;

  /// Sum of spendable + locked + pending balances across all pools.
  final BigInt total;

  const WalletBalance({
    required this.availability,
    required this.transparentAuthority,
    this.transparentLastKnown,
    required this.transparent,
    required this.sapling,
    required this.orchard,
    required this.ironwood,
    required this.transparentLocked,
    required this.saplingLocked,
    required this.orchardLocked,
    required this.ironwoodLocked,
    required this.transparentPending,
    required this.saplingPending,
    required this.orchardPending,
    required this.ironwoodPending,
    required this.changePendingConfirmation,
    required this.valuePendingSpendability,
    required this.uneconomicValue,
    required this.spendable,
    required this.locked,
    required this.total,
  });

  @override
  int get hashCode =>
      availability.hashCode ^
      transparentAuthority.hashCode ^
      transparentLastKnown.hashCode ^
      transparent.hashCode ^
      sapling.hashCode ^
      orchard.hashCode ^
      ironwood.hashCode ^
      transparentLocked.hashCode ^
      saplingLocked.hashCode ^
      orchardLocked.hashCode ^
      ironwoodLocked.hashCode ^
      transparentPending.hashCode ^
      saplingPending.hashCode ^
      orchardPending.hashCode ^
      ironwoodPending.hashCode ^
      changePendingConfirmation.hashCode ^
      valuePendingSpendability.hashCode ^
      uneconomicValue.hashCode ^
      spendable.hashCode ^
      locked.hashCode ^
      total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBalance &&
          runtimeType == other.runtimeType &&
          availability == other.availability &&
          transparentAuthority == other.transparentAuthority &&
          transparentLastKnown == other.transparentLastKnown &&
          transparent == other.transparent &&
          sapling == other.sapling &&
          orchard == other.orchard &&
          ironwood == other.ironwood &&
          transparentLocked == other.transparentLocked &&
          saplingLocked == other.saplingLocked &&
          orchardLocked == other.orchardLocked &&
          ironwoodLocked == other.ironwoodLocked &&
          transparentPending == other.transparentPending &&
          saplingPending == other.saplingPending &&
          orchardPending == other.orchardPending &&
          ironwoodPending == other.ironwoodPending &&
          changePendingConfirmation == other.changePendingConfirmation &&
          valuePendingSpendability == other.valuePendingSpendability &&
          uneconomicValue == other.uneconomicValue &&
          spendable == other.spendable &&
          locked == other.locked &&
          total == other.total;
}

enum WalletBalanceAvailability {
  available,
  summaryUnavailable,
  accountUnavailable,
}
