// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/config.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

/// Authenticate the static voting config bytes and surface the dynamic URL.
///
/// The wallet fetches the static trust anchor with its own transport and passes
/// the bytes here. Rust verifies the hash pin and decodes the static config,
/// returning the `dynamic_config_url` the wallet must fetch next before calling
/// [`resolve_voting_config`]. Config errors are returned as a flat string.
Future<String> resolveStaticVotingConfig({
  required String source,
  required List<int> staticBytes,
}) => RustLib.instance.api.crateApiVotingResolveStaticVotingConfig(
  source: source,
  staticBytes: staticBytes,
);

/// Resolve and authenticate voting config from wallet-fetched bytes.
///
/// The wallet owns transport: it fetches the static bytes, calls
/// [`resolve_static_voting_config`] to learn the dynamic URL, fetches the
/// dynamic bytes, then passes both blobs here. Rust authenticates them and
/// computes the config-switch classification against `previous`. Config errors
/// are returned as a flat string; transport failures never reach this layer.
Future<VotingConfigResolution> resolveVotingConfig({
  required String source,
  required List<int> staticBytes,
  required List<int> dynamicBytes,
  ResolvedVotingConfig? previous,
}) async {
  final resolution = await RustLib.instance.api
      .crateApiVotingResolveVotingConfig(
        source: source,
        staticBytes: staticBytes,
        dynamicBytes: dynamicBytes,
        previous: previous,
      );
  return VotingConfigResolution(
    config: resolution.config,
    switchKind: resolution.switchKind,
  );
}

class VotingConfigResolution {
  final ResolvedVotingConfig config;
  final ConfigSwitchKind switchKind;

  const VotingConfigResolution({
    required this.config,
    required this.switchKind,
  });

  @override
  int get hashCode => config.hashCode ^ switchKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VotingConfigResolution &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          switchKind == other.switchKind;
}
