// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/delegate.dart';
import '../third_party/zcash_voting/round.dart';
import '../third_party/zcash_voting/share_policy.dart';
import '../third_party/zcash_voting/types.dart';
import '../third_party/zcash_voting/vote.dart';
import '../third_party/zcash_voting/wire.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bundle_policy`, `catch`, `require_len`, `seed_from_mnemonic`, `share_tracking_record`, `voting_network`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Returns the vote-chain delegation submission body as validated wire JSON.
///
/// Binary fields are base64-encoded here so Dart does not duplicate protocol
/// field names or byte encoding rules.
Future<String> delegationSubmissionWireJson({
  required SignedDelegationPayloadView submission,
}) => RustLib.instance.api.crateApiVotingDelegationSubmissionWireJson(
  submission: submission,
);

/// Returns the vote-chain cast-vote submission body as validated wire JSON.
Future<String> voteCommitmentWireJson({
  required VoteCommitmentWire commitment,
}) => RustLib.instance.api.crateApiVotingVoteCommitmentWireJson(
  commitment: commitment,
);

/// Returns the helper-server encrypted-share submission body as wire JSON.
Future<String> voteShareWireJson({
  required VoteShareWire share,
  BigInt? vcTreePosition,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingVoteShareWireJson(
  share: share,
  vcTreePosition: vcTreePosition,
  submitAt: submitAt,
);

/// Plan independent helper-share timing and randomized helper targets.
///
/// This mirrors the zcash-swift-wallet-sdk wrapper around
/// `zcash_voting::share_policy::plan_share_submissions`, with Rust drawing the
/// policy-sized entropy from the OS CSPRNG before returning FRB-safe plans.
Future<List<ShareSubmissionPlan>> planShareSubmissions({
  required int shareCount,
  required List<String> serverUrls,
  required BigInt nowSeconds,
  required BigInt voteEndTimeSeconds,
  BigInt? lastMomentBufferSeconds,
  required bool singleShare,
}) => RustLib.instance.api.crateApiVotingPlanShareSubmissions(
  shareCount: shareCount,
  serverUrls: serverUrls,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
  lastMomentBufferSeconds: lastMomentBufferSeconds,
  singleShare: singleShare,
);

/// Return share-tracking action flags using `zcash_voting::share_policy`.
///
/// Bit 0 means the share is ready for status polling. Bit 1 means it is overdue
/// and should be retried against helpers that missed the initial submission.
Future<int> shareTrackingFlags({
  required ShareDelegationRecordView share,
  required BigInt nowSeconds,
  BigInt? voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingShareTrackingFlags(
  share: share,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Return the next share-tracking delay in seconds using crate policy.
Future<BigInt?> nextShareTrackingDelaySeconds({
  required List<ShareDelegationRecordView> shares,
  required BigInt nowSeconds,
}) => RustLib.instance.api.crateApiVotingNextShareTrackingDelaySeconds(
  shares: shares,
  nowSeconds: nowSeconds,
);

/// Extract and validate one helper-share payload from stored recovery JSON.
///
/// The stored recovery blob is hex-encoded and also contains local-only
/// recovery material. This helper emits only the public base64 wire shape that
/// helper servers accept.
Future<String> recoveredVoteShareWireJson({
  required String commitmentBundleJson,
  required int proposalId,
  required int shareIndex,
  required BigInt vcTreePosition,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingRecoveredVoteShareWireJson(
  commitmentBundleJson: commitmentBundleJson,
  proposalId: proposalId,
  shareIndex: shareIndex,
  vcTreePosition: vcTreePosition,
  submitAt: submitAt,
);

/// Derive the opaque per-account, per-round voting hotkey bytes.
///
/// Rust derives the wallet seed from the account mnemonic, then derives scoped
/// hotkey seed material locally and returns bytes for secure storage.
/// The returned `Vec<u8>` is an unavoidable FRB copy boundary
Future<Uint8List> deriveVotingHotkey({
  required String mnemonic,
  required String roundId,
  required String accountUuid,
  required String network,
}) => RustLib.instance.api.crateApiVotingDeriveVotingHotkey(
  mnemonic: mnemonic,
  roundId: roundId,
  accountUuid: accountUuid,
  network: network,
);

/// Generate opaque voting hotkey bytes for a hardware account.
///
/// Hardware accounts cannot expose their wallet seed to derive the deterministic
/// software hotkey, so the app persists this random per-round hotkey in secure
/// storage and reuses it for vote commitment signing.
Future<Uint8List> generateVotingHotkey({required String network}) =>
    RustLib.instance.api.crateApiVotingGenerateVotingHotkey(network: network);

/// Select notes and persist bundle rows for the delegation pipeline.
///
/// Reuses existing bundle rows for the same round/wallet, so callers can safely
/// retry setup before proving a specific bundle.
Future<BundleLayout> setupDelegationBundles({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required VotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  int? maxRealNotesPerBundle,
}) => RustLib.instance.api.crateApiVotingSetupDelegationBundles(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
  maxRealNotesPerBundle: maxRealNotesPerBundle,
);

/// Build delegation PCZT material and prefetch/cache PIR-backed IMT proofs.
///
/// This is a background warm-up path. The normal proof path still fetches any
/// missing PIR proofs if this was not run or did not complete in time.
Future<DelegationPirPrecomputeResultView> precomputeDelegationPir({
  required String dbPath,
  required String lightwalletdUrl,
  required String pirServerUrl,
  required String network,
  required VotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required String mnemonic,
  required int bundleIndex,
  int? maxRealNotesPerBundle,
}) => RustLib.instance.api.crateApiVotingPrecomputeDelegationPir(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  pirServerUrl: pirServerUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
  mnemonic: mnemonic,
  bundleIndex: bundleIndex,
  maxRealNotesPerBundle: maxRealNotesPerBundle,
);

/// Streaming variant of `build_prove_and_sign_delegation_payload`.
///
/// Emits local preparation phase events while work progresses, then emits a
/// final `"result"` event containing `SignedDelegationPayloadView`. The function
/// returns `Ok(())` after the terminal event is queued.
Stream<ApiDelegationProofEvent> buildProveAndSignDelegationPayloadWithProgress({
  required String dbPath,
  required String lightwalletdUrl,
  required String pirServerUrl,
  required String network,
  required VotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required String mnemonic,
  required int bundleIndex,
  int? maxRealNotesPerBundle,
}) => RustLib.instance.api
    .crateApiVotingBuildProveAndSignDelegationPayloadWithProgress(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      pirServerUrl: pirServerUrl,
      network: network,
      roundParams: roundParams,
      roundName: roundName,
      sessionJson: sessionJson,
      accountUuid: accountUuid,
      mnemonic: mnemonic,
      bundleIndex: bundleIndex,
      maxRealNotesPerBundle: maxRealNotesPerBundle,
    );

/// Build and redact a voting PCZT that Keystone must sign for one bundle.
Future<KeystoneSigningRequest> buildKeystoneDelegationRequest({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required VotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required List<int> hotkeySeed,
  required int bundleIndex,
  int? maxRealNotesPerBundle,
}) => RustLib.instance.api.crateApiVotingBuildKeystoneDelegationRequest(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
  hotkeySeed: hotkeySeed,
  bundleIndex: bundleIndex,
  maxRealNotesPerBundle: maxRealNotesPerBundle,
);

/// Extract the ZIP-244 sighash from PCZT bytes.
Future<Uint8List> extractPcztSighash({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiVotingExtractPcztSighash(pcztBytes: pcztBytes);

/// Extract a Keystone SpendAuth signature from signed PCZT bytes.
Future<Uint8List> extractSpendAuthSignatureFromSignedPczt({
  required List<int> signedPcztBytes,
  required int actionIndex,
}) =>
    RustLib.instance.api.crateApiVotingExtractSpendAuthSignatureFromSignedPczt(
      signedPcztBytes: signedPcztBytes,
      actionIndex: actionIndex,
    );

/// Persist a Keystone signature for one delegation bundle.
Future<void> storeKeystoneSignature({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required List<int> sig,
  required List<int> sighash,
  required List<int> rk,
}) => RustLib.instance.api.crateApiVotingStoreKeystoneSignature(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  sig: sig,
  sighash: sighash,
  rk: rk,
);

/// Load persisted Keystone signatures for one voting round.
Future<List<KeystoneSignatureRecord>> getKeystoneSignatures({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetKeystoneSignatures(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Streaming Keystone variant of `build_prove_and_sign_delegation_payload`.
Stream<ApiDelegationProofEvent>
buildProveDelegationPayloadWithKeystoneSignatureWithProgress({
  required String dbPath,
  required String lightwalletdUrl,
  required String pirServerUrl,
  required String network,
  required VotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required List<int> hotkeySeed,
  required int bundleIndex,
  required List<int> keystoneSig,
  required List<int> keystoneSighash,
  int? maxRealNotesPerBundle,
}) => RustLib.instance.api
    .crateApiVotingBuildProveDelegationPayloadWithKeystoneSignatureWithProgress(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      pirServerUrl: pirServerUrl,
      network: network,
      roundParams: roundParams,
      roundName: roundName,
      sessionJson: sessionJson,
      accountUuid: accountUuid,
      hotkeySeed: hotkeySeed,
      bundleIndex: bundleIndex,
      keystoneSig: keystoneSig,
      keystoneSighash: keystoneSighash,
      maxRealNotesPerBundle: maxRealNotesPerBundle,
    );

Future<void> markDelegationSubmitted({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkDelegationSubmitted(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
);

/// Parse tx events and record a confirmed delegation submission.
Future<DelegationConfirmation> confirmDelegationSubmission({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required String txHash,
  required List<ApiTxEvent> events,
}) => RustLib.instance.api.crateApiVotingConfirmDelegationSubmission(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
  events: events,
);

/// Delete bundle rows at or above `keep_count` for partial-bundle recovery.
///
/// Returns the number of deleted rows.
Future<int> deleteSkippedBundles({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int keepCount,
}) => RustLib.instance.api.crateApiVotingDeleteSkippedBundles(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  keepCount: keepCount,
);

/// Sync vote commitment tree state for a voting round.
///
/// Returns the latest synced tree height. The underlying tree client is cached
/// per `(db_path, wallet_id)` so later VAN witness calls can reuse the synced
/// in-memory tree state.
Future<int> syncVoteTree({
  required String dbPath,
  required String walletId,
  required String roundId,
  required String nodeUrl,
}) => RustLib.instance.api.crateApiVotingSyncVoteTree(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  nodeUrl: nodeUrl,
);

/// Generate a Vote Authority Note Merkle witness for a delegation bundle.
///
/// `anchor_height` is the vote-tree height where the witness should be anchored;
/// callers must sync the same round before requesting the witness.
Future<VanWitness> generateVanWitness({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int anchorHeight,
}) => RustLib.instance.api.crateApiVotingGenerateVanWitness(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  anchorHeight: anchorHeight,
);

/// Clear process-local voting state for a wallet or round.
///
/// Passing a non-empty round ID clears round-scoped caches only. Passing `None`
/// or an empty round ID also drops the cached vote-tree client for the wallet.
/// This does not abort in-flight proof or vote work already running on worker
/// threads.
Future<void> resetVotingSessionState({
  required String dbPath,
  required String walletId,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVotingSessionState(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Recover a committed but unsubmitted vote from persisted local recovery data.
Future<SignedVoteCommitmentsView> recoverVoteCommitment({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
}) => RustLib.instance.api.crateApiVotingRecoverVoteCommitment(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
);

/// Streaming variant of `build_vote_commitments`.
///
/// Emits per-proposal progress events, then a terminal `"result"` event carrying
/// `SignedVoteCommitmentsView`.
Stream<ApiVoteCommitEvent> buildVoteCommitmentsWithProgress({
  required String dbPath,
  required String walletId,
  required String network,
  required String roundId,
  required int bundleIndex,
  required List<int> hotkeySeed,
  required VanWitness vanWitness,
  required List<DraftVote> draftVotes,
}) => RustLib.instance.api.crateApiVotingBuildVoteCommitmentsWithProgress(
  dbPath: dbPath,
  walletId: walletId,
  network: network,
  roundId: roundId,
  bundleIndex: bundleIndex,
  hotkeySeed: hotkeySeed,
  vanWitness: vanWitness,
  draftVotes: draftVotes,
);

/// Load the full recovery/share-tracking summary for one voting round.
Future<RoundRecoveryStateView> getRoundRecoveryState({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetRoundRecoveryState(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

Future<void> markVoteSubmitted({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkVoteSubmitted(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
);

/// Parse tx events and record a confirmed vote submission.
Future<VoteConfirmation> confirmVoteSubmission({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
  required List<ApiTxEvent> events,
}) => RustLib.instance.api.crateApiVotingConfirmVoteSubmission(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
  events: events,
);

/// Record helper-server submission state for one encrypted vote share.
Future<void> recordShareDelegation({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> sentToUrls,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingRecordShareDelegation(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  sentToUrls: sentToUrls,
  submitAt: submitAt,
);

/// Mark one delegated share as confirmed on-chain.
Future<void> markShareConfirmed({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
}) => RustLib.instance.api.crateApiVotingMarkShareConfirmed(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
);

/// Merge additional helper-server URLs into one share delegation record.
Future<void> addSentServers({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> newUrls,
}) => RustLib.instance.api.crateApiVotingAddSentServers(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  newUrls: newUrls,
);

/// Clear vote/delegation recovery columns and share-tracking rows for a round.
///
/// This is an explicit reset for finalized or abandoned rounds, not a normal
/// retry step.
Future<void> clearRecoveryState({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingClearRecoveryState(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Compute the resumable voting-session plan for a round. The plan reports the
/// ordered remaining work (`next_steps`) and which proposals are still open.
Future<RoundPlanView> getRoundPlan({
  required String dbPath,
  required String walletId,
  required String roundId,
  required List<int> proposalIds,
}) => RustLib.instance.api.crateApiVotingGetRoundPlan(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  proposalIds: proposalIds,
);

/// Persist (insert or replace) the voter's ballot intent for one proposal.
/// Pass `skipped: true` for `Decision::Skipped`; otherwise `choice` must be set.
/// `num_options` is the proposal's declared option count.
Future<void> setBallotIntent({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int proposalId,
  required int numOptions,
  required bool skipped,
  int? choice,
}) => RustLib.instance.api.crateApiVotingSetBallotIntent(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  proposalId: proposalId,
  numOptions: numOptions,
  skipped: skipped,
  choice: choice,
);

/// Progress event emitted while building, proving, and signing a delegation payload.
///
/// A terminal `"result"` event carries `signed_delegation_payload`; earlier
/// phase events only describe local preparation progress.
class ApiDelegationProofEvent {
  final String phase;
  final double? proofProgress;
  final SignedDelegationPayloadView? signedDelegationPayload;

  const ApiDelegationProofEvent({
    required this.phase,
    this.proofProgress,
    this.signedDelegationPayload,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proofProgress.hashCode ^
      signedDelegationPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationProofEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proofProgress == other.proofProgress &&
          signedDelegationPayload == other.signedDelegationPayload;
}

/// One vote-chain event from a confirmed transaction.
class ApiTxEvent {
  final String eventType;
  final List<ApiTxEventAttribute> attributes;

  const ApiTxEvent({required this.eventType, required this.attributes});

  @override
  int get hashCode => eventType.hashCode ^ attributes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTxEvent &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          attributes == other.attributes;
}

/// One vote-chain event attribute from a confirmed transaction.
class ApiTxEventAttribute {
  final String key;
  final String value;

  const ApiTxEventAttribute({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTxEventAttribute &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// Progress event emitted while building ZKP2 vote commitments.
///
/// A terminal `"result"` event carries the completed commitment set; earlier
/// phase events include the active `(proposal_id, bundle_index)` pair.
class ApiVoteCommitEvent {
  final String phase;
  final int? proposalId;
  final int? bundleIndex;
  final double? proofProgress;
  final SignedVoteCommitmentsView? commitments;

  const ApiVoteCommitEvent({
    required this.phase,
    this.proposalId,
    this.bundleIndex,
    this.proofProgress,
    this.commitments,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proposalId.hashCode ^
      bundleIndex.hashCode ^
      proofProgress.hashCode ^
      commitments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteCommitEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proposalId == other.proposalId &&
          bundleIndex == other.bundleIndex &&
          proofProgress == other.proofProgress &&
          commitments == other.commitments;
}
