// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`, `selection_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Derive the opaque per-account, per-round voting hotkey bytes.
///
/// The seed stays platform-owned; Rust only applies the same zcash_voting
/// hotkey derivation used by delegation and returns bytes for secure storage.
Future<Uint8List> deriveVotingHotkey({
  required List<int> seedBytes,
  required String roundId,
  required String accountUuid,
}) => RustLib.instance.api.crateApiVotingDeriveVotingHotkey(
  seedBytes: seedBytes,
  roundId: roundId,
  accountUuid: accountUuid,
);

/// Initialize or load a voting round in the local voting database.
///
/// `session_json` is stored with the round when provided and can contain
/// coordinator metadata such as the human-readable round name.
Future<void> prepareVotingRound({
  required String dbPath,
  required String walletId,
  required ApiVotingRoundParams roundParams,
  String? sessionJson,
}) => RustLib.instance.api.crateApiVotingPrepareVotingRound(
  dbPath: dbPath,
  walletId: walletId,
  roundParams: roundParams,
  sessionJson: sessionJson,
);

/// Return the number of stored bundles for a voting round.
Future<int> getBundleCount({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetBundleCount(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Select voting-eligible notes at `snapshot_height` using lightwalletd data.
///
/// The returned notes are already quantized to `BALLOT_DIVISOR` voting weight
/// and include the cached tree anchor used by later delegation setup.
Future<ApiVotingNoteSelectionResult> selectVotingNotes({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required String accountUuid,
  required BigInt snapshotHeight,
}) => RustLib.instance.api.crateApiVotingSelectVotingNotes(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  accountUuid: accountUuid,
  snapshotHeight: snapshotHeight,
);

/// Select notes and persist bundle rows for the delegation pipeline.
///
/// Reuses existing bundle rows for the same round/wallet, so callers can safely
/// retry setup before proving a specific bundle.
Future<ApiVotingBundleSetupResult> setupDelegationBundles({
  required String dbPath,
  required String lightwalletdUrl,
  required String network,
  required ApiVotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
}) => RustLib.instance.api.crateApiVotingSetupDelegationBundles(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
);

/// Build delegation PCZT material and prefetch/cache PIR-backed IMT proofs.
///
/// This is a background warm-up path. The normal proof path still fetches any
/// missing PIR proofs if this was not run or did not complete in time.
Future<ApiDelegationPirPrecomputeResult> precomputeDelegationPir({
  required String dbPath,
  required String lightwalletdUrl,
  required String pirServerUrl,
  required String network,
  required ApiVotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required List<int> seedBytes,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingPrecomputeDelegationPir(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  pirServerUrl: pirServerUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
  seedBytes: seedBytes,
  bundleIndex: bundleIndex,
);

/// Build, prove, and sign one delegation payload.
///
/// This non-streaming variant drops intermediate proof progress and returns the
/// final signed payload directly. Submission and tx-hash storage happen in Dart.
Future<ApiSignedDelegationPayload> buildProveAndSignDelegationPayload({
  required String dbPath,
  required String lightwalletdUrl,
  required String pirServerUrl,
  required String network,
  required ApiVotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required List<int> seedBytes,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingBuildProveAndSignDelegationPayload(
  dbPath: dbPath,
  lightwalletdUrl: lightwalletdUrl,
  pirServerUrl: pirServerUrl,
  network: network,
  roundParams: roundParams,
  roundName: roundName,
  sessionJson: sessionJson,
  accountUuid: accountUuid,
  seedBytes: seedBytes,
  bundleIndex: bundleIndex,
);

/// Streaming variant of `build_prove_and_sign_delegation_payload`.
///
/// Emits local preparation phase events while work progresses, then emits a
/// final `"result"` event containing `ApiSignedDelegationPayload`. The function
/// returns `Ok(())` after the terminal event is queued.
Stream<ApiDelegationProofEvent> buildProveAndSignDelegationPayloadWithProgress({
  required String dbPath,
  required String lightwalletdUrl,
  required String pirServerUrl,
  required String network,
  required ApiVotingRoundParams roundParams,
  required String roundName,
  String? sessionJson,
  required String accountUuid,
  required List<int> seedBytes,
  required int bundleIndex,
}) => RustLib.instance.api
    .crateApiVotingBuildProveAndSignDelegationPayloadWithProgress(
      dbPath: dbPath,
      lightwalletdUrl: lightwalletdUrl,
      pirServerUrl: pirServerUrl,
      network: network,
      roundParams: roundParams,
      roundName: roundName,
      sessionJson: sessionJson,
      accountUuid: accountUuid,
      seedBytes: seedBytes,
      bundleIndex: bundleIndex,
    );

/// Store the broadcast transaction hash for one delegation bundle.
///
/// Hashes are keyed by `(round_id, wallet_id, bundle_index)` to support partial
/// bundle recovery.
Future<void> storeDelegationTxHash({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingStoreDelegationTxHash(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
);

Future<void> markDelegationSubmitted({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkDelegationSubmitted(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
);

Future<void> markDelegationConfirmed({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required String txHash,
  required int vanLeafPosition,
}) => RustLib.instance.api.crateApiVotingMarkDelegationConfirmed(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
  vanLeafPosition: vanLeafPosition,
);

/// Store the vote-authority-note leaf position emitted by the delegation TX.
Future<void> storeVanPosition({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int position,
}) => RustLib.instance.api.crateApiVotingStoreVanPosition(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  position: position,
);

/// Load the broadcast transaction hash for one delegation bundle, if present.
Future<String?> getDelegationTxHash({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingGetDelegationTxHash(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
);

/// Delete bundle rows at or above `keep_count` for partial-bundle recovery.
///
/// Returns the number of deleted rows.
Future<int> deleteSkippedBundles({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int keepCount,
}) => RustLib.instance.api.crateApiVotingDeleteSkippedBundles(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  keepCount: keepCount,
);

/// Sync vote commitment tree state for a voting round.
///
/// Returns the latest synced tree height. The underlying tree client is cached
/// per `(db_path, wallet_id)` so later VAN witness calls can reuse the synced
/// in-memory tree state.
Future<int> syncVoteTree({
  required String dbPath,
  required String walletId,
  required String roundId,
  required String nodeUrl,
}) => RustLib.instance.api.crateApiVotingSyncVoteTree(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  nodeUrl: nodeUrl,
);

/// Generate a Vote Authority Note Merkle witness for a delegation bundle.
///
/// `anchor_height` is the vote-tree height where the witness should be anchored;
/// callers must sync the same round before requesting the witness.
Future<ApiVanWitness> generateVanWitness({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int anchorHeight,
}) => RustLib.instance.api.crateApiVotingGenerateVanWitness(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  anchorHeight: anchorHeight,
);

/// Reset cached vote-tree client state for one round or all rounds.
///
/// `None` and `Some("")` both clear every round for the `(db_path, wallet_id)`
/// session; a non-empty round ID clears only that round.
Future<void> resetTreeClient({
  required String dbPath,
  required String walletId,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetTreeClient(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Clear process-local voting state for a wallet or round.
///
/// Passing a non-empty round ID clears prepared delegation PCZTs only for that
/// round. Passing `None` or an empty round ID performs account-wide cleanup:
/// prepared PCZTs for the wallet are cleared and the cached vote-tree client is
/// dropped.
Future<void> resetVotingSessionState({
  required String dbPath,
  required String walletId,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVotingSessionState(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Build signed ZKP2 vote commitments for one bundle.
///
/// Callers must pass a VAN witness generated for the same round and anchor
/// height. Returned encrypted shares are wire-safe and exclude plaintext values
/// and randomness.
Future<ApiSignedVoteCommitments> buildVoteCommitments({
  required String dbPath,
  required String walletId,
  required String network,
  required String roundId,
  required int bundleIndex,
  required List<int> hotkeySeed,
  required ApiVanWitness vanWitness,
  required List<ApiDraftVote> draftVotes,
}) => RustLib.instance.api.crateApiVotingBuildVoteCommitments(
  dbPath: dbPath,
  walletId: walletId,
  network: network,
  roundId: roundId,
  bundleIndex: bundleIndex,
  hotkeySeed: hotkeySeed,
  vanWitness: vanWitness,
  draftVotes: draftVotes,
);

/// Streaming variant of `build_vote_commitments`.
///
/// Emits per-proposal progress events, then a terminal `"result"` event carrying
/// `ApiSignedVoteCommitments`.
Stream<ApiVoteCommitEvent> buildVoteCommitmentsWithProgress({
  required String dbPath,
  required String walletId,
  required String network,
  required String roundId,
  required int bundleIndex,
  required List<int> hotkeySeed,
  required ApiVanWitness vanWitness,
  required List<ApiDraftVote> draftVotes,
}) => RustLib.instance.api.crateApiVotingBuildVoteCommitmentsWithProgress(
  dbPath: dbPath,
  walletId: walletId,
  network: network,
  roundId: roundId,
  bundleIndex: bundleIndex,
  hotkeySeed: hotkeySeed,
  vanWitness: vanWitness,
  draftVotes: draftVotes,
);

/// Load stored votes for a round across all bundles for this wallet.
Future<List<ApiVoteRecord>> getVotes({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetVotes(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Compute the deterministic share nullifier as lowercase 64-character hex.
///
/// The helper validates the commitment and blind lengths through `zcash_voting`.
Future<String> computeShareNullifierHex({
  required List<int> voteCommitment,
  required int shareIndex,
  required List<int> primaryBlind,
}) => RustLib.instance.api.crateApiVotingComputeShareNullifierHex(
  voteCommitment: voteCommitment,
  shareIndex: shareIndex,
  primaryBlind: primaryBlind,
);

/// Load the full recovery/share-tracking summary for one voting round.
Future<ApiRoundRecoveryState> getRoundRecoveryState({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetRoundRecoveryState(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Store the broadcast transaction hash for one vote.
///
/// Keyed by `(round_id, wallet_id, bundle_index, proposal_id)` so multi-bundle
/// and multi-proposal rounds can resume without ambiguous "current vote" state.
Future<void> storeVoteTxHash({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingStoreVoteTxHash(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
);

Future<void> markVoteSubmitted({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkVoteSubmitted(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
);

Future<void> markVoteConfirmed({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
  required int vanPosition,
  required BigInt vcTreePosition,
  required String commitmentBundleJson,
}) => RustLib.instance.api.crateApiVotingMarkVoteConfirmed(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
  vanPosition: vanPosition,
  vcTreePosition: vcTreePosition,
  commitmentBundleJson: commitmentBundleJson,
);

/// Load the broadcast transaction hash for one vote, if present.
Future<String?> getVoteTxHash({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
}) => RustLib.instance.api.crateApiVotingGetVoteTxHash(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
);

/// Store commitment bundle recovery JSON and confirmed vote-tree position for one vote.
Future<void> storeCommitmentBundle({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String commitmentBundleJson,
  required BigInt vcTreePosition,
}) => RustLib.instance.api.crateApiVotingStoreCommitmentBundle(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  commitmentBundleJson: commitmentBundleJson,
  vcTreePosition: vcTreePosition,
);

/// Load commitment bundle recovery JSON and vote-tree position for one vote.
Future<ApiCommitmentBundleRecovery?> getCommitmentBundle({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
}) => RustLib.instance.api.crateApiVotingGetCommitmentBundle(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
);

/// Record helper-server submission state for one encrypted vote share.
Future<void> recordShareDelegation({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> sentToUrls,
  required List<int> nullifier,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingRecordShareDelegation(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  sentToUrls: sentToUrls,
  nullifier: nullifier,
  submitAt: submitAt,
);

/// Load all helper-server share delegation records for a round.
Future<List<ApiShareDelegationRecord>> getShareDelegations({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetShareDelegations(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Load only unconfirmed helper-server share delegation records for retry.
Future<List<ApiShareDelegationRecord>> getUnconfirmedShareDelegations({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetUnconfirmedShareDelegations(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Mark one delegated share as confirmed on-chain.
Future<void> markShareConfirmed({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
}) => RustLib.instance.api.crateApiVotingMarkShareConfirmed(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
);

/// Merge additional helper-server URLs into one share delegation record.
Future<void> addSentServers({
  required String dbPath,
  required String walletId,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> newUrls,
}) => RustLib.instance.api.crateApiVotingAddSentServers(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  newUrls: newUrls,
);

/// Clear vote/delegation recovery columns and share-tracking rows for a round.
///
/// This is an explicit reset for finalized or abandoned rounds, not a normal
/// retry step.
Future<void> clearRecoveryState({
  required String dbPath,
  required String walletId,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingClearRecoveryState(
  dbPath: dbPath,
  walletId: walletId,
  roundId: roundId,
);

/// Stored commitment bundle recovery data for one `(bundle_index, proposal_id)`.
class ApiCommitmentBundleRecovery {
  final int bundleIndex;
  final int proposalId;
  final String commitmentBundleJson;
  final BigInt vcTreePosition;

  const ApiCommitmentBundleRecovery({
    required this.bundleIndex,
    required this.proposalId,
    required this.commitmentBundleJson,
    required this.vcTreePosition,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^
      proposalId.hashCode ^
      commitmentBundleJson.hashCode ^
      vcTreePosition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiCommitmentBundleRecovery &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          proposalId == other.proposalId &&
          commitmentBundleJson == other.commitmentBundleJson &&
          vcTreePosition == other.vcTreePosition;
}

/// Summary of delegation PIR proof precomputation for one bundle.
class ApiDelegationPirPrecomputeResult {
  final int cachedCount;
  final int fetchedCount;
  final int bundleCount;
  final int bundleIndex;

  const ApiDelegationPirPrecomputeResult({
    required this.cachedCount,
    required this.fetchedCount,
    required this.bundleCount,
    required this.bundleIndex,
  });

  @override
  int get hashCode =>
      cachedCount.hashCode ^
      fetchedCount.hashCode ^
      bundleCount.hashCode ^
      bundleIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationPirPrecomputeResult &&
          runtimeType == other.runtimeType &&
          cachedCount == other.cachedCount &&
          fetchedCount == other.fetchedCount &&
          bundleCount == other.bundleCount &&
          bundleIndex == other.bundleIndex;
}

/// Progress event emitted while building, proving, and signing a delegation payload.
///
/// A terminal `"result"` event carries `signed_delegation_payload`; earlier
/// phase events only describe local preparation progress.
class ApiDelegationProofEvent {
  final String phase;
  final double? proofProgress;
  final ApiSignedDelegationPayload? signedDelegationPayload;

  const ApiDelegationProofEvent({
    required this.phase,
    this.proofProgress,
    this.signedDelegationPayload,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proofProgress.hashCode ^
      signedDelegationPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationProofEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proofProgress == other.proofProgress &&
          signedDelegationPayload == other.signedDelegationPayload;
}

/// Stored delegation transaction hash for one bundle.
class ApiDelegationTxRecovery {
  final int bundleIndex;
  final String txHash;

  const ApiDelegationTxRecovery({
    required this.bundleIndex,
    required this.txHash,
  });

  @override
  int get hashCode => bundleIndex.hashCode ^ txHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationTxRecovery &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          txHash == other.txHash;
}

class ApiDelegationWorkflowRecovery {
  final int bundleIndex;
  final String phase;
  final String? txHash;
  final int? vanLeafPosition;

  const ApiDelegationWorkflowRecovery({
    required this.bundleIndex,
    required this.phase,
    this.txHash,
    this.vanLeafPosition,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^
      phase.hashCode ^
      txHash.hashCode ^
      vanLeafPosition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationWorkflowRecovery &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          phase == other.phase &&
          txHash == other.txHash &&
          vanLeafPosition == other.vanLeafPosition;
}

/// One requested vote for a proposal in a bundle.
///
/// `choice` is zero-indexed and must be less than `num_options`. `single_share`
/// enables the last-moment vote mode where only share 0 is submitted.
class ApiDraftVote {
  final int proposalId;
  final int choice;
  final int numOptions;
  final BigInt vcTreePosition;
  final bool singleShare;

  const ApiDraftVote({
    required this.proposalId,
    required this.choice,
    required this.numOptions,
    required this.vcTreePosition,
    required this.singleShare,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^
      choice.hashCode ^
      numOptions.hashCode ^
      vcTreePosition.hashCode ^
      singleShare.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDraftVote &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          choice == other.choice &&
          numOptions == other.numOptions &&
          vcTreePosition == other.vcTreePosition &&
          singleShare == other.singleShare;
}

/// Recovery summary for resuming one voting round after app restart.
class ApiRoundRecoveryState {
  final String roundId;
  final int bundleCount;
  final List<ApiDelegationWorkflowRecovery> delegationWorkflows;
  final List<ApiDelegationTxRecovery> delegationTxHashes;
  final List<ApiVoteRecord> votes;
  final List<ApiVoteWorkflowRecovery> voteWorkflows;
  final List<ApiVoteTxRecovery> voteTxHashes;
  final List<ApiCommitmentBundleRecovery> commitmentBundles;
  final List<ApiShareWorkflowRecovery> shareWorkflows;
  final List<ApiShareDelegationRecord> shareDelegations;
  final List<ApiShareDelegationRecord> unconfirmedShareDelegations;

  const ApiRoundRecoveryState({
    required this.roundId,
    required this.bundleCount,
    required this.delegationWorkflows,
    required this.delegationTxHashes,
    required this.votes,
    required this.voteWorkflows,
    required this.voteTxHashes,
    required this.commitmentBundles,
    required this.shareWorkflows,
    required this.shareDelegations,
    required this.unconfirmedShareDelegations,
  });

  @override
  int get hashCode =>
      roundId.hashCode ^
      bundleCount.hashCode ^
      delegationWorkflows.hashCode ^
      delegationTxHashes.hashCode ^
      votes.hashCode ^
      voteWorkflows.hashCode ^
      voteTxHashes.hashCode ^
      commitmentBundles.hashCode ^
      shareWorkflows.hashCode ^
      shareDelegations.hashCode ^
      unconfirmedShareDelegations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRoundRecoveryState &&
          runtimeType == other.runtimeType &&
          roundId == other.roundId &&
          bundleCount == other.bundleCount &&
          delegationWorkflows == other.delegationWorkflows &&
          delegationTxHashes == other.delegationTxHashes &&
          votes == other.votes &&
          voteWorkflows == other.voteWorkflows &&
          voteTxHashes == other.voteTxHashes &&
          commitmentBundles == other.commitmentBundles &&
          shareWorkflows == other.shareWorkflows &&
          shareDelegations == other.shareDelegations &&
          unconfirmedShareDelegations == other.unconfirmedShareDelegations;
}

/// Helper-server share delegation state used for retry/resume.
class ApiShareDelegationRecord {
  final String roundId;
  final int bundleIndex;
  final int proposalId;
  final int shareIndex;
  final List<String> sentToUrls;
  final Uint8List nullifier;
  final String phase;
  final bool confirmed;
  final BigInt submitAt;
  final BigInt createdAt;

  const ApiShareDelegationRecord({
    required this.roundId,
    required this.bundleIndex,
    required this.proposalId,
    required this.shareIndex,
    required this.sentToUrls,
    required this.nullifier,
    required this.phase,
    required this.confirmed,
    required this.submitAt,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      roundId.hashCode ^
      bundleIndex.hashCode ^
      proposalId.hashCode ^
      shareIndex.hashCode ^
      sentToUrls.hashCode ^
      nullifier.hashCode ^
      phase.hashCode ^
      confirmed.hashCode ^
      submitAt.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareDelegationRecord &&
          runtimeType == other.runtimeType &&
          roundId == other.roundId &&
          bundleIndex == other.bundleIndex &&
          proposalId == other.proposalId &&
          shareIndex == other.shareIndex &&
          sentToUrls == other.sentToUrls &&
          nullifier == other.nullifier &&
          phase == other.phase &&
          confirmed == other.confirmed &&
          submitAt == other.submitAt &&
          createdAt == other.createdAt;
}

class ApiShareWorkflowRecovery {
  final int bundleIndex;
  final int proposalId;
  final int shareIndex;
  final String phase;

  const ApiShareWorkflowRecovery({
    required this.bundleIndex,
    required this.proposalId,
    required this.shareIndex,
    required this.phase,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^
      proposalId.hashCode ^
      shareIndex.hashCode ^
      phase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiShareWorkflowRecovery &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          proposalId == other.proposalId &&
          shareIndex == other.shareIndex &&
          phase == other.phase;
}

/// Signed delegation payload ready for Dart-side submission.
class ApiSignedDelegationPayload {
  final Uint8List pcztBytes;
  final String status;
  final String? message;
  final Uint8List proof;
  final Uint8List rk;
  final Uint8List spendAuthSig;
  final Uint8List sighash;
  final Uint8List nfSigned;
  final Uint8List cmxNew;
  final Uint8List govComm;
  final List<Uint8List> govNullifiers;
  final String voteRoundId;
  final BigInt eligibleWeightZatoshi;
  final BigInt delegatedWeightZatoshi;
  final int bundleCount;
  final int bundleIndex;

  const ApiSignedDelegationPayload({
    required this.pcztBytes,
    required this.status,
    this.message,
    required this.proof,
    required this.rk,
    required this.spendAuthSig,
    required this.sighash,
    required this.nfSigned,
    required this.cmxNew,
    required this.govComm,
    required this.govNullifiers,
    required this.voteRoundId,
    required this.eligibleWeightZatoshi,
    required this.delegatedWeightZatoshi,
    required this.bundleCount,
    required this.bundleIndex,
  });

  @override
  int get hashCode =>
      pcztBytes.hashCode ^
      status.hashCode ^
      message.hashCode ^
      proof.hashCode ^
      rk.hashCode ^
      spendAuthSig.hashCode ^
      sighash.hashCode ^
      nfSigned.hashCode ^
      cmxNew.hashCode ^
      govComm.hashCode ^
      govNullifiers.hashCode ^
      voteRoundId.hashCode ^
      eligibleWeightZatoshi.hashCode ^
      delegatedWeightZatoshi.hashCode ^
      bundleCount.hashCode ^
      bundleIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSignedDelegationPayload &&
          runtimeType == other.runtimeType &&
          pcztBytes == other.pcztBytes &&
          status == other.status &&
          message == other.message &&
          proof == other.proof &&
          rk == other.rk &&
          spendAuthSig == other.spendAuthSig &&
          sighash == other.sighash &&
          nfSigned == other.nfSigned &&
          cmxNew == other.cmxNew &&
          govComm == other.govComm &&
          govNullifiers == other.govNullifiers &&
          voteRoundId == other.voteRoundId &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi &&
          delegatedWeightZatoshi == other.delegatedWeightZatoshi &&
          bundleCount == other.bundleCount &&
          bundleIndex == other.bundleIndex;
}

/// Signed ZKP2 vote commitment and wire-safe share data for one proposal.
class ApiSignedVoteCommitment {
  final int proposalId;
  final int choice;
  final String voteRoundId;
  final Uint8List vanNullifier;
  final Uint8List voteAuthorityNoteNew;
  final Uint8List voteCommitment;
  final Uint8List proof;
  final List<ApiWireEncryptedShare> encryptedShares;
  final List<ApiVoteSharePayload> sharePayloads;
  final int anchorHeight;
  final Uint8List sharesHash;
  final List<Uint8List> shareComms;
  final Uint8List rVpkBytes;
  final Uint8List voteAuthSig;
  final String commitmentBundleJson;

  const ApiSignedVoteCommitment({
    required this.proposalId,
    required this.choice,
    required this.voteRoundId,
    required this.vanNullifier,
    required this.voteAuthorityNoteNew,
    required this.voteCommitment,
    required this.proof,
    required this.encryptedShares,
    required this.sharePayloads,
    required this.anchorHeight,
    required this.sharesHash,
    required this.shareComms,
    required this.rVpkBytes,
    required this.voteAuthSig,
    required this.commitmentBundleJson,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^
      choice.hashCode ^
      voteRoundId.hashCode ^
      vanNullifier.hashCode ^
      voteAuthorityNoteNew.hashCode ^
      voteCommitment.hashCode ^
      proof.hashCode ^
      encryptedShares.hashCode ^
      sharePayloads.hashCode ^
      anchorHeight.hashCode ^
      sharesHash.hashCode ^
      shareComms.hashCode ^
      rVpkBytes.hashCode ^
      voteAuthSig.hashCode ^
      commitmentBundleJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSignedVoteCommitment &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          choice == other.choice &&
          voteRoundId == other.voteRoundId &&
          vanNullifier == other.vanNullifier &&
          voteAuthorityNoteNew == other.voteAuthorityNoteNew &&
          voteCommitment == other.voteCommitment &&
          proof == other.proof &&
          encryptedShares == other.encryptedShares &&
          sharePayloads == other.sharePayloads &&
          anchorHeight == other.anchorHeight &&
          sharesHash == other.sharesHash &&
          shareComms == other.shareComms &&
          rVpkBytes == other.rVpkBytes &&
          voteAuthSig == other.voteAuthSig &&
          commitmentBundleJson == other.commitmentBundleJson;
}

/// Set of signed vote commitments produced for one bundle index.
class ApiSignedVoteCommitments {
  final int bundleIndex;
  final List<ApiSignedVoteCommitment> commitments;

  const ApiSignedVoteCommitments({
    required this.bundleIndex,
    required this.commitments,
  });

  @override
  int get hashCode => bundleIndex.hashCode ^ commitments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSignedVoteCommitments &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          commitments == other.commitments;
}

class ApiVanWitness {
  /// 24 sibling hashes from the VAN leaf to the vote-tree root.
  final List<Uint8List> authPath;

  /// VAN leaf position in the vote commitment tree.
  final int position;

  /// Vote-tree height at which this witness is valid.
  final int anchorHeight;

  const ApiVanWitness({
    required this.authPath,
    required this.position,
    required this.anchorHeight,
  });

  @override
  int get hashCode =>
      authPath.hashCode ^ position.hashCode ^ anchorHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVanWitness &&
          runtimeType == other.runtimeType &&
          authPath == other.authPath &&
          position == other.position &&
          anchorHeight == other.anchorHeight;
}

/// Progress event emitted while building ZKP2 vote commitments.
///
/// A terminal `"result"` event carries the completed commitment set; earlier
/// phase events include the active `(proposal_id, bundle_index)` pair.
class ApiVoteCommitEvent {
  final String phase;
  final int? proposalId;
  final int? bundleIndex;
  final double? proofProgress;
  final ApiSignedVoteCommitments? commitments;

  const ApiVoteCommitEvent({
    required this.phase,
    this.proposalId,
    this.bundleIndex,
    this.proofProgress,
    this.commitments,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proposalId.hashCode ^
      bundleIndex.hashCode ^
      proofProgress.hashCode ^
      commitments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteCommitEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proposalId == other.proposalId &&
          bundleIndex == other.bundleIndex &&
          proofProgress == other.proofProgress &&
          commitments == other.commitments;
}

/// Stored vote row keyed by `(round_id, wallet_id, bundle_index, proposal_id)`.
class ApiVoteRecord {
  final int proposalId;
  final int bundleIndex;
  final int choice;
  final bool submitted;

  const ApiVoteRecord({
    required this.proposalId,
    required this.bundleIndex,
    required this.choice,
    required this.submitted,
  });

  @override
  int get hashCode =>
      proposalId.hashCode ^
      bundleIndex.hashCode ^
      choice.hashCode ^
      submitted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteRecord &&
          runtimeType == other.runtimeType &&
          proposalId == other.proposalId &&
          bundleIndex == other.bundleIndex &&
          choice == other.choice &&
          submitted == other.submitted;
}

/// Helper-server payload for one encrypted vote share.
///
/// Contains only public inputs and the selected public encrypted share. The
/// `primary_blind` is included for share tracking/nullifier recovery.
class ApiVoteSharePayload {
  final Uint8List sharesHash;
  final int proposalId;
  final int voteDecision;
  final ApiWireEncryptedShare encryptedShare;
  final BigInt treePosition;
  final List<ApiWireEncryptedShare> allEncryptedShares;
  final List<Uint8List> shareComms;
  final Uint8List primaryBlind;

  const ApiVoteSharePayload({
    required this.sharesHash,
    required this.proposalId,
    required this.voteDecision,
    required this.encryptedShare,
    required this.treePosition,
    required this.allEncryptedShares,
    required this.shareComms,
    required this.primaryBlind,
  });

  @override
  int get hashCode =>
      sharesHash.hashCode ^
      proposalId.hashCode ^
      voteDecision.hashCode ^
      encryptedShare.hashCode ^
      treePosition.hashCode ^
      allEncryptedShares.hashCode ^
      shareComms.hashCode ^
      primaryBlind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteSharePayload &&
          runtimeType == other.runtimeType &&
          sharesHash == other.sharesHash &&
          proposalId == other.proposalId &&
          voteDecision == other.voteDecision &&
          encryptedShare == other.encryptedShare &&
          treePosition == other.treePosition &&
          allEncryptedShares == other.allEncryptedShares &&
          shareComms == other.shareComms &&
          primaryBlind == other.primaryBlind;
}

/// Stored vote transaction hash for one `(bundle_index, proposal_id)`.
class ApiVoteTxRecovery {
  final int bundleIndex;
  final int proposalId;
  final String txHash;

  const ApiVoteTxRecovery({
    required this.bundleIndex,
    required this.proposalId,
    required this.txHash,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^ proposalId.hashCode ^ txHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteTxRecovery &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          proposalId == other.proposalId &&
          txHash == other.txHash;
}

class ApiVoteWorkflowRecovery {
  final int bundleIndex;
  final int proposalId;
  final String phase;
  final String? txHash;
  final BigInt? vcTreePosition;
  final bool hasCommitmentBundle;

  const ApiVoteWorkflowRecovery({
    required this.bundleIndex,
    required this.proposalId,
    required this.phase,
    this.txHash,
    this.vcTreePosition,
    required this.hasCommitmentBundle,
  });

  @override
  int get hashCode =>
      bundleIndex.hashCode ^
      proposalId.hashCode ^
      phase.hashCode ^
      txHash.hashCode ^
      vcTreePosition.hashCode ^
      hasCommitmentBundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteWorkflowRecovery &&
          runtimeType == other.runtimeType &&
          bundleIndex == other.bundleIndex &&
          proposalId == other.proposalId &&
          phase == other.phase &&
          txHash == other.txHash &&
          vcTreePosition == other.vcTreePosition &&
          hasCommitmentBundle == other.hasCommitmentBundle;
}

/// Summary of bundle setup keyed by `(round_id, wallet_id)`.
class ApiVotingBundleSetupResult {
  final int bundleCount;
  final BigInt eligibleWeightZatoshi;

  const ApiVotingBundleSetupResult({
    required this.bundleCount,
    required this.eligibleWeightZatoshi,
  });

  @override
  int get hashCode => bundleCount.hashCode ^ eligibleWeightZatoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingBundleSetupResult &&
          runtimeType == other.runtimeType &&
          bundleCount == other.bundleCount &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi;
}

/// FRB-safe reference to one note eligible for voting at the snapshot height.
class ApiVotingNoteRef {
  final String pool;
  final String txidHex;
  final int outputIndex;
  final BigInt valueZatoshi;
  final BigInt votingWeightZatoshi;
  final BigInt commitmentTreePosition;
  final BigInt minedHeight;
  final BigInt anchorHeight;

  const ApiVotingNoteRef({
    required this.pool,
    required this.txidHex,
    required this.outputIndex,
    required this.valueZatoshi,
    required this.votingWeightZatoshi,
    required this.commitmentTreePosition,
    required this.minedHeight,
    required this.anchorHeight,
  });

  @override
  int get hashCode =>
      pool.hashCode ^
      txidHex.hashCode ^
      outputIndex.hashCode ^
      valueZatoshi.hashCode ^
      votingWeightZatoshi.hashCode ^
      commitmentTreePosition.hashCode ^
      minedHeight.hashCode ^
      anchorHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingNoteRef &&
          runtimeType == other.runtimeType &&
          pool == other.pool &&
          txidHex == other.txidHex &&
          outputIndex == other.outputIndex &&
          valueZatoshi == other.valueZatoshi &&
          votingWeightZatoshi == other.votingWeightZatoshi &&
          commitmentTreePosition == other.commitmentTreePosition &&
          minedHeight == other.minedHeight &&
          anchorHeight == other.anchorHeight;
}

/// Result of selecting voting notes for a snapshot height.
class ApiVotingNoteSelectionResult {
  final int noteCount;
  final BigInt eligibleWeightZatoshi;
  final BigInt snapshotHeight;
  final BigInt anchorHeight;
  final List<ApiVotingNoteRef> notes;

  const ApiVotingNoteSelectionResult({
    required this.noteCount,
    required this.eligibleWeightZatoshi,
    required this.snapshotHeight,
    required this.anchorHeight,
    required this.notes,
  });

  @override
  int get hashCode =>
      noteCount.hashCode ^
      eligibleWeightZatoshi.hashCode ^
      snapshotHeight.hashCode ^
      anchorHeight.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingNoteSelectionResult &&
          runtimeType == other.runtimeType &&
          noteCount == other.noteCount &&
          eligibleWeightZatoshi == other.eligibleWeightZatoshi &&
          snapshotHeight == other.snapshotHeight &&
          anchorHeight == other.anchorHeight &&
          notes == other.notes;
}

/// FRB-safe voting round parameters loaded from the coordinator/session.
class ApiVotingRoundParams {
  final String voteRoundId;
  final BigInt snapshotHeight;
  final Uint8List eaPk;
  final Uint8List ncRoot;
  final Uint8List nullifierImtRoot;

  const ApiVotingRoundParams({
    required this.voteRoundId,
    required this.snapshotHeight,
    required this.eaPk,
    required this.ncRoot,
    required this.nullifierImtRoot,
  });

  @override
  int get hashCode =>
      voteRoundId.hashCode ^
      snapshotHeight.hashCode ^
      eaPk.hashCode ^
      ncRoot.hashCode ^
      nullifierImtRoot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingRoundParams &&
          runtimeType == other.runtimeType &&
          voteRoundId == other.voteRoundId &&
          snapshotHeight == other.snapshotHeight &&
          eaPk == other.eaPk &&
          ncRoot == other.ncRoot &&
          nullifierImtRoot == other.nullifierImtRoot;
}

/// Public encrypted share fields safe to pass through Dart/REST.
///
/// Plaintext values and encryption randomness intentionally never cross this API.
class ApiWireEncryptedShare {
  final Uint8List ciphertext1;
  final Uint8List ciphertext2;
  final int shareIndex;

  const ApiWireEncryptedShare({
    required this.ciphertext1,
    required this.ciphertext2,
    required this.shareIndex,
  });

  @override
  int get hashCode =>
      ciphertext1.hashCode ^ ciphertext2.hashCode ^ shareIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiWireEncryptedShare &&
          runtimeType == other.runtimeType &&
          ciphertext1 == other.ciphertext1 &&
          ciphertext2 == other.ciphertext2 &&
          shareIndex == other.shareIndex;
}
