// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/zcash_voting/delegate.dart';
import '../third_party/zcash_voting/round.dart';
import '../third_party/zcash_voting/share_policy.dart';
import '../third_party/zcash_voting/types.dart';
import '../third_party/zcash_voting/vote.dart';
import '../third_party/zcash_voting/wire.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_vote_commitments_result`, `bundle_policy`, `catch`, `emit_signed_delegation_result`, `emit_signed_vote_result`, `log_sink_closed`, `prepare_delegation_bundle_params`, `require_len`, `resolve_delegation_prep_inputs`, `seed_from_mnemonic`, `voting_network`, `wallet_network`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// Returns the vote-chain delegation submission body as validated wire JSON.
///
/// Binary fields are base64-encoded here so Dart does not duplicate protocol
/// field names or byte encoding rules.
Future<String> delegationSubmissionWireJson({
  required SignedDelegationPayloadView submission,
}) => RustLib.instance.api.crateApiVotingDelegationSubmissionWireJson(
  submission: submission,
);

/// Returns the vote-chain cast-vote submission body as validated wire JSON.
Future<String> voteCommitmentWireJson({
  required VoteCommitmentWire commitment,
}) => RustLib.instance.api.crateApiVotingVoteCommitmentWireJson(
  commitment: commitment,
);

/// Returns the helper-server encrypted-share submission body as wire JSON.
Future<String> voteShareWireJson({
  required VoteShareWire share,
  BigInt? vcTreePosition,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingVoteShareWireJson(
  share: share,
  vcTreePosition: vcTreePosition,
  submitAt: submitAt,
);

/// Plan independent helper-share timing and randomized helper targets.
///
/// This mirrors the zcash-swift-wallet-sdk wrapper around
/// `zcash_voting::share_policy::plan_share_submissions`, with Rust drawing the
/// policy-sized entropy from the OS CSPRNG before returning FRB-safe plans.
///
/// # Errors
///
/// Returns an error if `share_count` does not fit `usize`, entropy generation
/// fails, or crate policy rejects the supplied timing/server inputs.
Future<List<ShareSubmissionPlan>> planShareSubmissions({
  required int shareCount,
  required List<String> serverUrls,
  required BigInt nowSeconds,
  required BigInt voteEndTimeSeconds,
  BigInt? lastMomentBufferSeconds,
  required bool singleShare,
}) => RustLib.instance.api.crateApiVotingPlanShareSubmissions(
  shareCount: shareCount,
  serverUrls: serverUrls,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
  lastMomentBufferSeconds: lastMomentBufferSeconds,
  singleShare: singleShare,
);

/// Return share-tracking action flags using `zcash_voting::share_policy`.
///
/// [`SHARE_TRACKING_FLAG_READY`] means the share is ready for status polling.
/// [`SHARE_TRACKING_FLAG_OVERDUE`] means it is overdue and should be retried
/// against helpers that missed the initial submission.
Future<int> shareTrackingFlags({
  required ShareDelegationRecordView share,
  required BigInt nowSeconds,
  BigInt? voteEndTimeSeconds,
}) => RustLib.instance.api.crateApiVotingShareTrackingFlags(
  share: share,
  nowSeconds: nowSeconds,
  voteEndTimeSeconds: voteEndTimeSeconds,
);

/// Return the next share-tracking delay in seconds using crate policy.
Future<BigInt?> nextShareTrackingDelaySeconds({
  required List<ShareDelegationRecordView> shares,
  required BigInt nowSeconds,
}) => RustLib.instance.api.crateApiVotingNextShareTrackingDelaySeconds(
  shares: shares,
  nowSeconds: nowSeconds,
);

/// Extract and validate one helper-share payload from stored recovery JSON.
///
/// The stored recovery blob is hex-encoded and also contains local-only
/// recovery material. This helper emits only the public base64 wire shape that
/// helper servers accept.
Future<String> recoveredVoteShareWireJson({
  required String commitmentBundleJson,
  required int proposalId,
  required int shareIndex,
  required BigInt vcTreePosition,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingRecoveredVoteShareWireJson(
  commitmentBundleJson: commitmentBundleJson,
  proposalId: proposalId,
  shareIndex: shareIndex,
  vcTreePosition: vcTreePosition,
  submitAt: submitAt,
);

/// Derive the opaque per-account, per-round voting hotkey bytes.
///
/// Rust derives the wallet seed from the account mnemonic, then derives scoped
/// hotkey seed material locally and returns bytes for secure storage.
/// The returned `Vec<u8>` is an unavoidable FRB copy boundary
///
/// # Errors
///
/// Returns an error if network parsing fails, mnemonic decoding fails, or
/// contextual hotkey derivation fails.
Future<Uint8List> deriveVotingHotkey({
  required String mnemonic,
  required String roundId,
  required String accountUuid,
  required String network,
}) => RustLib.instance.api.crateApiVotingDeriveVotingHotkey(
  mnemonic: mnemonic,
  roundId: roundId,
  accountUuid: accountUuid,
  network: network,
);

/// Generate opaque voting hotkey bytes for a hardware account.
///
/// Hardware accounts cannot expose their wallet seed to derive the deterministic
/// software hotkey, so the app persists this random per-round hotkey in secure
/// storage and reuses it for vote commitment signing.
///
/// # Errors
///
/// Returns an error if network parsing fails or random hotkey generation fails.
Future<Uint8List> generateVotingHotkey({required String network}) =>
    RustLib.instance.api.crateApiVotingGenerateVotingHotkey(network: network);

/// Select notes and persist bundle rows for the delegation pipeline.
///
/// Reuses existing bundle rows for the same round/wallet, so callers can safely
/// retry setup before proving a specific bundle.
///
/// # Errors
///
/// Returns an error if bundle policy parsing, opening the sidecar DB, round
/// initialization, note selection, or bundle layout persistence fails.
Future<BundleLayout> setupDelegationBundles({
  required ApiVotingRoundContext ctx,
}) => RustLib.instance.api.crateApiVotingSetupDelegationBundles(ctx: ctx);

/// Build delegation PCZT material and prefetch/cache PIR-backed IMT proofs.
///
/// This is a background warm-up path. The normal proof path still fetches any
/// missing PIR proofs if this was not run or did not complete in time.
///
/// # Errors
///
/// Returns an error if round input resolution, mnemonic-to-seed derivation,
/// hotkey derivation, bundle preparation, or PIR precompute fails.
Future<DelegationPirPrecomputeResultView> precomputeDelegationPir({
  required ApiVotingRoundContext ctx,
  required String pirServerUrl,
  required String mnemonic,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingPrecomputeDelegationPir(
  ctx: ctx,
  pirServerUrl: pirServerUrl,
  mnemonic: mnemonic,
  bundleIndex: bundleIndex,
);

/// Streaming variant of `build_prove_and_sign_delegation_payload`.
///
/// Emits local preparation phase events while work progresses, then emits a
/// final `"result"` event containing `SignedDelegationPayloadView`. The function
/// returns `Ok(())` after the terminal event is queued.
///
/// # Errors
///
/// Returns an error if round input resolution fails before the stream work
/// starts. Runtime delegation/proving errors are forwarded into the sink as
/// stream errors.
Stream<ApiDelegationProofEvent> buildProveAndSignDelegationPayloadWithProgress({
  required ApiVotingRoundContext ctx,
  required String pirServerUrl,
  required String mnemonic,
  required int bundleIndex,
}) => RustLib.instance.api
    .crateApiVotingBuildProveAndSignDelegationPayloadWithProgress(
      ctx: ctx,
      pirServerUrl: pirServerUrl,
      mnemonic: mnemonic,
      bundleIndex: bundleIndex,
    );

/// Build and redact a voting PCZT that Keystone must sign for one bundle.
///
/// # Errors
///
/// Returns an error if round input resolution fails or if PCZT construction and
/// redaction for the requested bundle fails.
Future<KeystoneSigningRequest> buildKeystoneDelegationRequest({
  required ApiVotingRoundContext ctx,
  required List<int> hotkeySeed,
  required int bundleIndex,
}) => RustLib.instance.api.crateApiVotingBuildKeystoneDelegationRequest(
  ctx: ctx,
  hotkeySeed: hotkeySeed,
  bundleIndex: bundleIndex,
);

/// Extract the ZIP-244 sighash from PCZT bytes.
///
/// # Errors
///
/// Returns an error if `pczt_bytes` cannot be decoded or does not contain a
/// spend authorization sighash.
Future<Uint8List> extractPcztSighash({required List<int> pcztBytes}) =>
    RustLib.instance.api.crateApiVotingExtractPcztSighash(pcztBytes: pcztBytes);

/// Extract a Keystone SpendAuth signature from signed PCZT bytes.
Future<Uint8List> extractSpendAuthSignatureFromSignedPczt({
  required List<int> signedPcztBytes,
  required int actionIndex,
}) =>
    RustLib.instance.api.crateApiVotingExtractSpendAuthSignatureFromSignedPczt(
      signedPcztBytes: signedPcztBytes,
      actionIndex: actionIndex,
    );

/// Persist a Keystone signature for one delegation bundle.
///
/// # Errors
///
/// Returns an error if signature lengths are invalid, opening the voting DB
/// fails, or persisting the signature record fails.
Future<void> storeKeystoneSignature({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required List<int> sig,
  required List<int> sighash,
  required List<int> rk,
}) => RustLib.instance.api.crateApiVotingStoreKeystoneSignature(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  sig: sig,
  sighash: sighash,
  rk: rk,
);

/// Load persisted Keystone signatures for one voting round.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or signature rows cannot be
/// loaded.
Future<List<KeystoneSignatureRecord>> getKeystoneSignatures({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetKeystoneSignatures(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Streaming Keystone variant of `build_prove_and_sign_delegation_payload`.
///
/// # Errors
///
/// Returns an error if round input resolution fails before stream work starts.
/// Runtime proving/signature errors are emitted through the sink.
Stream<ApiDelegationProofEvent>
buildProveDelegationPayloadWithKeystoneSignatureWithProgress({
  required ApiVotingRoundContext ctx,
  required String pirServerUrl,
  required List<int> hotkeySeed,
  required int bundleIndex,
  required List<int> keystoneSig,
  required List<int> keystoneSighash,
}) => RustLib.instance.api
    .crateApiVotingBuildProveDelegationPayloadWithKeystoneSignatureWithProgress(
      ctx: ctx,
      pirServerUrl: pirServerUrl,
      hotkeySeed: hotkeySeed,
      bundleIndex: bundleIndex,
      keystoneSig: keystoneSig,
      keystoneSighash: keystoneSighash,
    );

/// Record a submitted delegation transaction hash for one bundle.
///
/// Repeated calls are idempotent only for the same transaction hash.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the bundle key is missing,
/// or the stored hash conflicts with `tx_hash`.
Future<void> markDelegationSubmitted({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkDelegationSubmitted(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
);

/// Parse tx events and record a confirmed delegation submission.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the event payload does not
/// match the expected round/type shape, or confirmation state cannot be stored.
Future<DelegationConfirmation> confirmDelegationSubmission({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required String txHash,
  required List<TxEvent> events,
}) => RustLib.instance.api.crateApiVotingConfirmDelegationSubmission(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  txHash: txHash,
  events: events,
);

/// Delete bundle rows at or above `keep_count` for partial-bundle recovery.
///
/// Returns the number of deleted rows.
Future<int> deleteSkippedBundles({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int keepCount,
}) => RustLib.instance.api.crateApiVotingDeleteSkippedBundles(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  keepCount: keepCount,
);

/// Sync vote commitment tree state for a voting round.
///
/// Returns the latest synced tree height. The underlying tree client is cached
/// per `(db_path, account_uuid)` so later VAN witness calls can reuse the synced
/// in-memory tree state.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or tree sync against
/// `node_url` fails for `round_id`.
Future<int> syncVoteTree({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required String nodeUrl,
}) => RustLib.instance.api.crateApiVotingSyncVoteTree(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  nodeUrl: nodeUrl,
);

/// Generate a Vote Authority Note Merkle witness for a delegation bundle.
///
/// `anchor_height` is the vote-tree height where the witness should be anchored;
/// callers must sync the same round before requesting the witness.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, `bundle_index` is out of
/// range for the round, or witness generation fails.
Future<VanWitness> generateVanWitness({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int anchorHeight,
}) => RustLib.instance.api.crateApiVotingGenerateVanWitness(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  anchorHeight: anchorHeight,
);

/// Clear process-local voting state for a wallet or round.
///
/// Passing a non-empty round ID clears round-scoped caches only. Passing `None`
/// or an empty round ID also drops the cached vote-tree client for the wallet.
/// This does not abort in-flight proof or vote work already running on worker
/// threads.
Future<void> resetVotingSessionState({
  required String dbPath,
  required String accountUuid,
  String? roundId,
}) => RustLib.instance.api.crateApiVotingResetVotingSessionState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Recover a committed but unsubmitted vote from persisted local recovery data.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, no matching commitment is
/// recoverable, or wire conversion fails.
Future<SignedVoteCommitmentsView> recoverVoteCommitment({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
}) => RustLib.instance.api.crateApiVotingRecoverVoteCommitment(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
);

/// Streaming variant of `build_vote_commitments`.
///
/// Emits per-proposal progress events, then a terminal `"result"` event carrying
/// `SignedVoteCommitmentsView`.
Stream<ApiVoteCommitEvent> buildVoteCommitmentsWithProgress({
  required String dbPath,
  required String accountUuid,
  required String network,
  required String roundId,
  required int bundleIndex,
  required List<int> hotkeySeed,
  required VanWitness vanWitness,
  required List<DraftVote> draftVotes,
}) => RustLib.instance.api.crateApiVotingBuildVoteCommitmentsWithProgress(
  dbPath: dbPath,
  accountUuid: accountUuid,
  network: network,
  roundId: roundId,
  bundleIndex: bundleIndex,
  hotkeySeed: hotkeySeed,
  vanWitness: vanWitness,
  draftVotes: draftVotes,
);

/// Load the full recovery/share-tracking summary for one voting round.
Future<RoundRecoveryStateView> getRoundRecoveryState({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingGetRoundRecoveryState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Record a submitted cast-vote transaction hash for one bundle/proposal key.
///
/// Repeated calls are idempotent only for the same transaction hash.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the vote key is missing, or
/// the stored hash conflicts with `tx_hash`.
Future<void> markVoteSubmitted({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
}) => RustLib.instance.api.crateApiVotingMarkVoteSubmitted(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
);

/// Parse tx events and record a confirmed vote submission.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the event payload does not
/// match the expected round/type shape, or confirmation state cannot be stored.
Future<VoteConfirmation> confirmVoteSubmission({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required String txHash,
  required List<TxEvent> events,
}) => RustLib.instance.api.crateApiVotingConfirmVoteSubmission(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  txHash: txHash,
  events: events,
);

/// Record helper-server submission state for one encrypted vote share.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the vote cannot be
/// recovered, or the share record cannot be persisted.
Future<void> recordShareDelegation({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> sentToUrls,
  required BigInt submitAt,
}) => RustLib.instance.api.crateApiVotingRecordShareDelegation(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  sentToUrls: sentToUrls,
  submitAt: submitAt,
);

/// Mark one delegated share as confirmed on-chain.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails, the vote cannot be
/// recovered, or share confirmation cannot be persisted.
Future<void> markShareConfirmed({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
}) => RustLib.instance.api.crateApiVotingMarkShareConfirmed(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
);

/// Merge additional helper-server URLs into one share delegation record.
///
/// # Errors
///
/// Returns an error if opening the voting DB fails or the share record cannot
/// be updated.
Future<void> addSentServers({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int bundleIndex,
  required int proposalId,
  required int shareIndex,
  required List<String> newUrls,
}) => RustLib.instance.api.crateApiVotingAddSentServers(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  bundleIndex: bundleIndex,
  proposalId: proposalId,
  shareIndex: shareIndex,
  newUrls: newUrls,
);

/// Clear vote/delegation recovery columns and share-tracking rows for a round.
///
/// This is an explicit reset for finalized or abandoned rounds, not a normal
/// retry step.
Future<void> clearRecoveryState({
  required String dbPath,
  required String accountUuid,
  required String roundId,
}) => RustLib.instance.api.crateApiVotingClearRecoveryState(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
);

/// Compute the resumable voting-session plan for a round. The plan reports the
/// ordered remaining work (`next_steps`) and which proposals are still open.
Future<RoundPlanView> getRoundPlan({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required List<int> proposalIds,
}) => RustLib.instance.api.crateApiVotingGetRoundPlan(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  proposalIds: proposalIds,
);

/// Persist (insert or replace) the voter's ballot intent for one proposal.
/// Pass `skipped: true` for `Decision::Skipped`; otherwise `choice` must be set.
/// `num_options` is the proposal's declared option count.
Future<void> setBallotIntent({
  required String dbPath,
  required String accountUuid,
  required String roundId,
  required int proposalId,
  required int numOptions,
  required bool skipped,
  int? choice,
}) => RustLib.instance.api.crateApiVotingSetBallotIntent(
  dbPath: dbPath,
  accountUuid: accountUuid,
  roundId: roundId,
  proposalId: proposalId,
  numOptions: numOptions,
  skipped: skipped,
  choice: choice,
);

/// Progress event emitted while building, proving, and signing a delegation payload.
///
/// A terminal `"result"` event carries `signed_delegation_payload`; earlier
/// phase events only describe local preparation progress.
class ApiDelegationProofEvent {
  final String phase;
  final double? proofProgress;
  final SignedDelegationPayloadView? signedDelegationPayload;

  const ApiDelegationProofEvent({
    required this.phase,
    this.proofProgress,
    this.signedDelegationPayload,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proofProgress.hashCode ^
      signedDelegationPayload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiDelegationProofEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proofProgress == other.proofProgress &&
          signedDelegationPayload == other.signedDelegationPayload;
}

/// Progress event emitted while building ZKP2 vote commitments.
///
/// A terminal `"result"` event carries the completed commitment set; earlier
/// phase events include the active `(proposal_id, bundle_index)` pair.
class ApiVoteCommitEvent {
  final String phase;
  final int? proposalId;
  final int? bundleIndex;
  final double? proofProgress;
  final SignedVoteCommitmentsView? commitments;

  const ApiVoteCommitEvent({
    required this.phase,
    this.proposalId,
    this.bundleIndex,
    this.proofProgress,
    this.commitments,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      proposalId.hashCode ^
      bundleIndex.hashCode ^
      proofProgress.hashCode ^
      commitments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVoteCommitEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          proposalId == other.proposalId &&
          bundleIndex == other.bundleIndex &&
          proofProgress == other.proofProgress &&
          commitments == other.commitments;
}

/// Shared delegation/voting round context passed across the FRB boundary.
///
/// This bundles the reusable round and wallet scope required by delegation setup,
/// proving, and keystone request flows.
class ApiVotingRoundContext {
  final String dbPath;
  final String lightwalletdUrl;
  final String network;
  final VotingRoundParams roundParams;
  final String roundName;
  final String? sessionJson;
  final String accountUuid;
  final int? maxRealNotesPerBundle;

  const ApiVotingRoundContext({
    required this.dbPath,
    required this.lightwalletdUrl,
    required this.network,
    required this.roundParams,
    required this.roundName,
    this.sessionJson,
    required this.accountUuid,
    this.maxRealNotesPerBundle,
  });

  @override
  int get hashCode =>
      dbPath.hashCode ^
      lightwalletdUrl.hashCode ^
      network.hashCode ^
      roundParams.hashCode ^
      roundName.hashCode ^
      sessionJson.hashCode ^
      accountUuid.hashCode ^
      maxRealNotesPerBundle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiVotingRoundContext &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          lightwalletdUrl == other.lightwalletdUrl &&
          network == other.network &&
          roundParams == other.roundParams &&
          roundName == other.roundName &&
          sessionJson == other.sessionJson &&
          accountUuid == other.accountUuid &&
          maxRealNotesPerBundle == other.maxRealNotesPerBundle;
}
