import 'package:zcash_wallet/src/features/swap/models/swap_models.dart';

final swapActivityFixtureIntents = <SwapIntent>[
  SwapIntent(
    id: 'swap-8f29',
    pair: 'ZEC -> USDC',
    sellAmount: '2.4000 ZEC',
    receiveEstimate: '168.42 USDC',
    provider: 'NEAR Intents',
    status: SwapIntentStatus.processing,
    nextAction: 'Swap is processing',
  ),
  SwapIntent(
    id: 'swap-6c44',
    pair: 'USDC -> ZEC',
    sellAmount: '210.52 USDC',
    receiveEstimate: '3.0000 ZEC',
    provider: 'NEAR Intents',
    status: SwapIntentStatus.awaitingExternalDeposit,
    nextAction: 'Send USDC to the one-time deposit address',
  ),
  SwapIntent(
    id: 'swap-underpaid',
    pair: 'USDC -> ZEC',
    sellAmount: '100.00 USDC',
    receiveEstimate: '1.4250 ZEC',
    provider: 'NEAR Intents',
    status: SwapIntentStatus.incompleteDeposit,
    nextAction: 'Deposit is below the quoted amount',
    direction: SwapDirection.externalToZec,
    externalAsset: SwapAsset.usdc,
    depositAddress: '0xunderpaid-usdc-deposit',
    depositMemo: 'memo-underpaid',
    oneClickRefundTo: '0xusdc-refund-underpaid',
    providerRefundInfo: SwapProviderRefundInfo(
      depositedAmountText: '60.00 USDC',
      refundFeeText: '0.25 USDC',
    ),
    depositDeadline: DateTime(2026, 5, 20, 13, 20),
  ),
  SwapIntent(
    id: 'swap-refund',
    pair: 'ZEC -> USDC',
    sellAmount: '0.9000 ZEC',
    receiveEstimate: '63.16 USDC',
    provider: 'NEAR Intents',
    status: SwapIntentStatus.refunded,
    nextAction: 'Refunded to source address',
    direction: SwapDirection.zecToExternal,
    externalAsset: SwapAsset.usdc,
    depositAddress: 't1refund-zec-deposit',
    oneClickRecipient: '0xusdc-recipient-refund',
    oneClickRefundTo: 'u1wallet-refund-source',
  ),
  SwapIntent(
    id: 'swap-failed',
    pair: 'NEAR -> ZEC',
    sellAmount: '14.00 NEAR',
    receiveEstimate: '0.2778 ZEC',
    provider: 'NEAR Intents',
    status: SwapIntentStatus.failed,
    nextAction: 'Swap route failed',
    direction: SwapDirection.externalToZec,
    externalAsset: SwapAsset.near,
    depositAddress: 'near-failed-deposit.near',
    oneClickRefundTo: 'rowan.near',
  ),
  SwapIntent(
    id: 'swap-2a11',
    pair: 'ZEC -> NEAR',
    sellAmount: '0.7500 ZEC',
    receiveEstimate: '37.8 NEAR',
    provider: 'NEAR Intents',
    status: SwapIntentStatus.complete,
    nextAction: 'Copy redacted receipt',
  ),
];
